### ISSUE TITLE
Poetry doesn't appear to work with pyenv-virtualenv

### ISSUE THREAD

**Issue by reversefold** [python-poetry/poetry#1061]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

The documentation says:

    When you execute the install command (or any other "install" commands like add or remove), Poetry will check if it's currently inside a virtualenv and, if not, will use an existing one or create a brand new one for you to always work isolated from your global Python installation.

I took this to mean that if I had set up a pyenv virtualenv for my project, and was in that virtualenv (usually via a .python-version file in the root of the project) that poetry would use that virtualenv for installing dependencies. This doesn't appear to be the case, though, as when I run `poetry install` it creates a new virtualenv in ~/Library/Caches/pypoetry/virtualenvs.

After running `poetry install` if I run `pip freeze` I don't see the packages that poetry has installed. I would rather have the libraries and commands installed with my dependencies be available in the active pyenv-virtualenv rather than having to prefix everything with `poetry run`.

**Comment by diefans** [comment]
Poetry started quite interesting, with sane dependency and locking feature. But suddenly it evolved into a one-fits-all-monster trying to be smart on virtualenvs.

I use pyenv for a good reason since years. The missing part was just a tool like poetry in its beginnings.

Now it hijacks my virtualenv concept and how I run scripts... You guys should focus on doing your business!
See your amount of issues and open PRs? You will never fix it again, just by blowing up your focus...

**Comment by sdispater** [comment]
@diefans If you have nothing constructive to add, please refrain from commenting. You are criticizing something that is given to you for free, maintained by a group of volunteers that do it on their free time, so the least you can do is being considerate of their time and effort. If Poetry no longer fits your workflow, feel free to use something else. I mean it because I know that sometimes Poetry might not cover some use cases that people are really attached to.

Now, that being said, I use Poetry with `pyenv` and `pyenv-virtualenv` myself without any issue so either there is something wrong with you configuration or there is indeed a bug.

For information, I have in my `.zshrc` the following lines:

```bash
if [[ -z "$VIRTUAL_ENV" ]]; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
```

Normally, `pyenv-virtualenv` should set the `VIRTUAL_ENV`environment variable that is used by Poetry to detect if it's currently inside a virtualenv. If it's not set, there must be something wrong with your configuration.

**Comment by mwchase** [comment]
Something I just noticed looking into this: I've got a bunch of projects that locally use multiple virtualenvs. In that context, the `VIRTUAL_ENV` variable isn't set, while if there's just one, it is set.

I was using multiple virtualenvs because I develop mostly in Python 3, but I'm a mercurial holdout. But, I recently installed pyenv-implicit because some other tooling was interacting badly with pyenv-virtualenv, and I think that means I don't need to explicitly include the mercurial virtualenv any more.

I don't know if pyenv-virtualenv "should" populate that environment variable under all circumstances, but apparently it doesn't.

**Comment by diefans** [comment]
@sdispater I know what open source is. My constructive argument is - since you are nearly the only driver of this project and your time is limited: KISS.

Your project got a lot of traction, but as you might have noticed there are even multiple PRs fixing the same issue. So I would ask myself if there are 6.7k stars, 452 open issues and 89 open PRs where people voluntarily spend their time helping you... why are they not recognized?

**Comment by sdispater** [comment]
@diefans 

> My constructive argument is - since you are nearly the only driver of this project and your time is limited: KISS.

And I already do. I rejected a lot of feature requests because they did not align with the vision I have for Poetry. I know exactly what I want Poetry to be.

> So I would ask myself if there are 6.7k stars, 452 open issues and 89 open PRs where people voluntarily spend their time helping you... why are they not recognized?

They are recognized but my time and the time of the other collaborators is limited and doing code reviews takes time as well as going over a backlog of 400+ issues. I regularly go back to the oldest issues to see if they are still relevant and close or classify appropriately.

**Comment by diefans** [comment]
@sdispater (my last comment on this)
>  they did not align with the vision I have for Poetry. I know exactly what I want Poetry to be.
So it would be sane to communicate this vision, to not distract or even disappoint your valuable contributors, since basically this "mismatch in vision" is just wasting energy...

**Comment by reversefold** [comment]
@mwchase I'm assuming the multiple virtualenvs is in order to use scripts installed by a package while keeping other environments separate. You might look into pipx. I've been using pipx for a while now for managing things such as awscli and aws-utilities and it uses a virtualenv for each while abstracting it away so you don't have to deal directly with the virtualenvs.
