### ISSUE TITLE
sparse documentation about "extras" attribute

### ISSUE THREAD

**Issue by devkral** [python-poetry/poetry#1076]
It would be helpful  to have some documentation/tutorials about the dependencies "extras" attribute and its syntax. I found it only by searching the issues.

Can you please add an example in the documentation of the pyproject.toml (or document the single attributes (option, extras, version)).
Something like
pendelum = {version = "*", extras=["mooncalendar"]}

**Comment by chrahunt** [comment]
It is mentioned in the README. Including in the [dependencies and dev dependencies](https://poetry.eustace.io/docs/pyproject/#dependencies-and-dev-dependencies) section would probably be good.

**Comment by devkral** [comment]
it would be super. Anyway thanks for writing this tool. It is really nice to use.

**Comment by esciara** [comment]
There is an [extras section](https://poetry.eustace.io/docs/pyproject/#extras) in the pyproject.toml file page of the docs... Isn't this what you are looking for ? Although it looks like it might be incorrect (see #1339)

**Comment by matthijskooijman** [comment]
I also ran into this, extras is quite unclear. It *seems* there might be two different kinds of extras, also specified by https://python-poetry.org/docs/pyproject/#extras:

1. optional dependencies, which enhance a package, but are not required; and
2. clusters of optional dependencies.

Extras as in 1. can be specified when adding dependencies, as documented [here](https://python-poetry.org/docs/cli/#add), e.g. 

    poetry add requests[security,socks]

Extras as in 2. can maybe be manually specified in the pyproject.toml project, as suggested [here](https://python-poetry.org/docs/pyproject/#extras), but you would expect that you could also pass the extra "cluster" as an option to `poetry add` when adding a dependency, also to update the lock file. Discussion in #1145 suggests that there is no CLI way for this, so you should [manually add extras to pyproject.toml and then run `poetry lock`](https://github.com/python-poetry/poetry/issues/1145#issuecomment-624187600) to add them to poetry.lock?

There's also some indications that 2. might not be currently working? e.g #2073 and #1145

I also wonder if these two usecases might not actually be two faces of the same thing? E.g. 2. might be considered "extras" of the current package, such that `poetry install -E foo` would be somewhat equivalent to `pip install .[foo]`? This is what the reporter of #1145 seems to imply as well.

For clarity, it might be worthwile to use different terminology for 1. and 2. Since setuptools already uses "extras" for 1., perhaps 2. should be renamed to something else? Especially since `--extras` for `poetry add` might already refer to 1. (suggested at https://github.com/python-poetry/poetry/issues/1145#issuecomment-526161777, though I could not find anything docs for this).

Also note #1463 which fixes an extras-related link in the docs.

**Comment by matthijskooijman** [comment]
> For clarity, it might be worthwile to use different terminology for 1. and 2.

This might also be sidestepped by replacing 2. with "dependency groups", as suggested in #1644.

**Comment by aalok-sathe** [comment]
Whereas `poetry` documentation mentions the support for "optional dependency clusters", there is no example of it. I am inferring that it is specified as a `extra_name = [list, of, packages, that, are, clustered]`, but the documentation doesn't say so.

It is also unclear if the extras should be specified **either** in the `[tool.poetry.dependencies]` section as `... optional = true`, **or** in the `[tool.poetry.extras]` section, or **both**.
