### ISSUE TITLE
How can I install a local version of my package with poetry? non setup.py file

### ISSUE THREAD

**Issue by SHxKM** [python-poetry/poetry#1135]
I know that poetry is supposed to _replace_ `setup.py`, but how can I develop a package on my local machine when using poetry, I've read that the equivalent of `pip install -e .` in poetry is simply `poetry install` from the root directory of the project, but even though poetry does state it finished installing my package, I get import errors everywhere.

I would ideally want to install my package system-wide, or a virtualenv of my choice, so I can run it no after going into `poetry shell`, but even that isn't working.

Edit: one thing I noticed, is that my package is (re?) installed every time I run poetry install..

**Comment by SHxKM** [comment]
I figured out the problem. Because `poetry` is directory based, then I can't import my local package in a file in another directory (I guess the virtualenv isn't activated there). Is there a way around this?

**Comment by jacebrowning** [comment]
> I can't import my local package in a file in another directory

Can you clarify what you're trying to do? Either of the following should work:

```
$ poetry install
$ poetry run python
>>> import my_package
```

```
$ poetry install
$ poetry run python my_script.py
```

**Comment by SHxKM** [comment]
I'm talking about being able to import my package inside a file outside of my package directory.

```python
# ~/Desktop/test_file.py
from mypackage.decorators import deco
```
In Terminal:

```
cd Desktop
./test_file.py
``

This throws an `ImportError` because the file is outside of my package's folder. It also throws an error in VSCode for example, because I'm using it's not using poetry's own virtualenv.

With `pip` and `setup.py` I can simply do `pip install -e .` from within my package's directory, and then use it liberally anywhere, whether working in an IDE or the Terminal.

**Comment by iScrE4m** [comment]
The problem is: when you do `pip install -e`, you're using your system pip, however poetry is installing your package within the virtualenv, so if you don't want to use your virtuelnv for the test_file, you might do `poetry config settings.virtualenvs.create false`, but it is not recommended, it's even discouraged.

**Comment by merwok** [comment]
To answer the original question:

If I understand correctly, poetry is a development tool.  It works in a virtualenv (one it creates or one that is managed externally, depending on your options) and provides commands (including install) to work on a project in an isolated fashion, because that’s what we want when developping.

To have a project globally installable, we shouldn’t reach for a dev tool but for an installation tool: pip!  Thanks to PEP 517 integration, you can use `pip install path/to/project/with/poetry/config` and get your tool installed globally (using any usual pip options such as --user or --target to control where things end up).

Hope this helps!

**Comment by MestreLion** [comment]
> To have a project globally installable, we shouldn’t reach for a dev tool but for an installation tool: pip! Thanks to PEP 517 integration, you can use `pip install path/to/project/with/poetry/config` and get your tool installed globally (using any usual pip options such as --user or --target to control where things end up).

Problem is, `pip install -e` _requires_ `setup.py`, as stated by this error message:

```
01:15:27 rodrigo@desktop ~/work/minecraft/nbtlib master $ pip3 install --user -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/rodrigo/work/minecraft/nbtlib
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

So, if a given library uses Poetry, how can I clone its github repo and install it locally to use in my projects? (in editable mode, so I can also make changes to the library itself)?

**Comment by rmvanwyk** [comment]
> So, if a given library uses Poetry, how can I clone its github repo and install it locally to use in my projects? ~(in editable mode, so I can also make changes to the library itself)~?

I think what may help you is the [poetry build](https://python-poetry.org/docs/cli/#build) command. This will create a wheel and a tar file which you can then pip install into your environment of choice.
ex) `pip install my_package-version.tar.gz`
It won't be in editable mode so you'll have to rebuild the package whenever you make changes but I think this solves your problem quoted above. AFAIK, there is no direct equivalent of `pip install -e` for poetry, as `poetry install` simply [installs the dependencies](https://python-poetry.org/docs/cli/#install) defined in `pyproject.toml`.

**Comment by cgarciae** [comment]
Did this behavior change? I just tried and the package was installed locally with `poetry install`.

**Comment by jaklan** [comment]
> Did this behavior change? I just tried and the package was installed locally with `poetry install`.

The issue is not about a local development of a package, but about installing the package in the editable mode in another project, which normally would be handled via `pip install -e /path/to/package`. Now there's no such an equivalent, there are only dirty workarounds like the one mentioned by @rmvanwyk. @sdispater such issues are a huge blocker to use poetry for a serious development.

**Comment by cgarciae** [comment]
@jaklan I see, thanks for the explanation. So I am guessing that using

```toml
my_package = { path = "my/package/path" }
```
Would not install it in editable mode? 

BTW: is editable mode just putting a symlink in `site-packages`?

**Comment by jaklan** [comment]
@cgarciae Yeah, that would work:
>Path dependencies pointing to a local directory will be installed in editable mode (i.e. setuptools "develop mode"). It means that changes in the local directory will be reflected directly in environment.

But... only when you also use poetry for that second project ;) Which is not always possible, especially with some legacy projects or e.g. Data Science projects, which are often based on conda envs and files (which is not a problem normally, because in environment.yml I can just use `pip install -e some/path`).

Ad. BTW - here's a detailed explanation:
https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode

**Comment by merwok** [comment]
Editable mode can be a symlink in site-packages (flit does that), or a `pth` file (setuptools method), **and** a dist-info directory.  Both the import system and the packaging metadata systems need to find what they’re looking for.

**Comment by hay** [comment]
Maybe this issue should be renamed to something like 'Poetry should support installing local packages in editable mode'? 

What works for me is indeed just symlinking the local library folder to `site-packages` in a venv. It definitely is not very pretty, but it works for me. Here are all the commands needed to set up a venv, install a local package, and then replacing it with the symlinked version.

```bash
    # I'm assuming your package is called 'my-lib' and your folder where
    # you want to test is called 'my-code'

    # Create venv first
    cd ~/my-code
    virtualenv env
    source env/bin/activate

    # Now install the local library
    pip install ~/my-lib

    # And delete the directory, assuming you're using python 3.6
    rm lib/python3.6/site-packages/my-lib

    # Now add a symlink
    ln -s ~/my-lib ~/lib/python3.6/site-packages/my-lib
```

**Comment by tbsexton** [comment]
@jaklan The data science worflow is exactly how I found this issue. Building a toolkit that will likely serve as a jupyter-centric assist within conda env. rather than require jupyter as a hard dependency, my plan was to have a notebooks top-level folder with an `environment.yml` file that allows a reader to reproduce locally.

 This conda env would depend on a pypi-hosted version of my package eventually, but in development I'm used to satisfying that dependency via a local development installation (`pip intstall -e .`, etc). 

Loving poetry so far but this is a bit of a roadblock to clean conda-centric dev.

**Comment by NeilGirdhar** [comment]
Can we not add a `poetry develop` command that does:
```
poetry build
pip install dist/***.whl
```
?

**Comment by rosejn** [comment]
Yeah if poetry is meant to be a development focused tool, then it seems to be missing a primary piece of developing a larger project: libraries.  Ideally there is a clear and simple workflow to handle the situation where I'm working on server application X, which uses custom libraries A and B which my team is also developing.  As I add a new endpoint to server X which needs a new function in library A, I should be able to just edit a file in A and have it instantly available in X during development.  The symlink approach above seems sensible, so maybe that could be built-in as a poetry command.

    poetry extern /path/to/library/A

**Comment by yanniskatsaros** [comment]
Following this for future updates. For now, the following workaround seemed to work alright for me:

- `poetry shell`
- `pip install -e .`

This is an okayish approach for local testing, but probably not the best. I tried to install using `poetry add ./my-package/` that didn't seem to work as my `pyproject.toml` and my `setup.py` file are on the same level in my directory as such:

```
├── LICENSE
├── README.md
├── my-package
├── poetry.lock
├── pyproject.toml
├── setup.py
```

**Comment by NeilGirdhar** [comment]
@yanniskatsaros How does that help if you don't have a setup.py at all?   Isn't that the point of using pyproject.toml?

**Comment by yanniskatsaros** [comment]
@NeilGirdhar you're right - I didn't realize that `poetry` could also be used for building/deploying your package as well. I was only using it for environment management and exporting my dependencies to a `requirements.txt` file.

So you're right, relative to this thread, my answer isn't helpful. My apologies 😅

**Comment by adamal** [comment]
I am not entirely sure what to conclude from this discussion.
The way I understand it:

Say I have 
```
- app1/
- app2/
- shared/
```
, where `app1` and `app2` are managed with Poetry.

I could then import `shared` from `app1` or `app2`  using
```
my_package = { path = "my/package/path" }
```

For this to work (i.e. `poetry build` from `app1` or `app2` will also include dependencies of `shared`), Poetry also "needs to be used" for `shared`. 
Being more explicit: `shared` needs to have a Poetry-parsable pyproject.toml at its root, but does not need to be separately built.

Is this understanding correct?

**Comment by jaklan** [comment]
@adamal exact opposite ;) It's more about such a scenario:
```
- lib1/
- app2/
```
where `lib1` is managed with Poetry, but `app2` is not, so if you try to install the local version of `lib1` in the editable mode (`pip install -e .../lib1`) in `app2` virtual env - it would fail then, because you would miss `setup.py`.

**Comment by rgerkin** [comment]
I'm a long-time fan of `pip install -e .`, but for my main case (just being able to import and use an in-development package while working on another package or project), just symlinking into site-packages seems sufficient:
`ln -s /path/to/my/package /path/to/site-packages/`, taking care to make sure that first path is the path to the package itself not to the parent directory (previously) containing `setup.py`.
Since the simple symlink does not actually install any dependencies, you are responsible for having installed them already, but if you are using a conda environment then you probably already did.

**Comment by finswimmer** [comment]
Lot's of confusion here. I try to summarize it:

* The current project is installed in development mode within the venv with `poetry install` by default.
* You can add other poetry and setup.py managed project as dependencies in development mode with `poetry add ../relative_path/to/package_folder`
* Installing a poetry managed project - or better: any project managed by `pyproject.toml` instead of `setup.py` - in development mode by `pip`, is currently not possible. But that's on `pip`'s side and not on `poetry`'s. See also: https://github.com/pypa/pip/issues/6434

**Comment by NeilGirdhar** [comment]
@finswimmer What do you propose users of poetry do to achieve editable installs?

**Comment by rosejn** [comment]
I struggled with this, and then learned that you can poetry add with a
relative path.  So inside of poetry project A, you can do

$ poetry add ../other_project_b

And then it will be available in your project A.

**Comment by jaklan** [comment]
> I struggled with this, and then learned that you can poetry add with a relative path. So inside of poetry project A, you can do $ poetry add ../other_project_b And then it will be available in your project A.

Thanks for repeating exactly the same what @finswimmer wrote 2 comments above and not understanding the question at all - we're talking here about:
> Installing a poetry managed project - or better: any project managed by pyproject.toml instead of setup.py - in development mode by pip

@NeilGirdhar it seems @rmvanwyk workaround with `poetry build` is one way (but still - it's not editable mode), another - generating `setup.py` from `pyproject.toml` with `dephell`, so `pip install -e` would work.

**Comment by NeilGirdhar** [comment]
@jaklan Right, I'm asking about editable mode.  Generating setup.py is unfortunate since the whole point is to just rely on modern pyproject.toml.  finswimmer might be right that this is pip's problem, but it doesn't seem that pip is going to fix this.  Therefore, I would prefer if poetry simply added a `develop` command or `editable` flag to the install command.  I currently do this:
```
function pyinstall {
    local package=${PWD##*/}
    ln -s -f $PWD/$package `python -c 'import site; print(site.getsitepackages()[0])'`/$package
    echo Installed $package
}
function pyuninstall {
    local package=${PWD##*/}
    rm -r `python -c 'import site; print(site.getsitepackages()[0])'`/$package
    echo Uninstalled $package
}
```
I'm sure it could be better.

**Comment by jaklan** [comment]
@NeilGirdhar I fully agree. The topic on `pip` side seems to be frozen, so we're completely stuck at the moment...

There was also some discussion here, but it's also dead for months... I really don't understand the `pip` core team approach to that, very important after all, issue.
https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553/62

**Comment by mosesontheweb** [comment]
Hi,

just stumbled over this ticket. I had about the same problem, I wasn't able to install a package in editable mode within an environment created with poetry.
I used setup.py and setup.cfg to define all options for my package. Using it with pyproject.toml might be quite ok, but I miss somehow a good documentation for it. Additionally the support for data files is quite poor. So that's why I go for setup.py.

Anyway, whenever I ran `poetry run python setup.py bdist_wheel`, everything is fine. Also the installation in a different virtual environment worked pretty well. But stepping into the virtual Python environment (`poetry shell`) and running `pip install -e .` ends up with the error `ModuleNotFoundError: No module named 'setuptools'`.

My installed modules in the Poetry virtual environment:
```
Package     Version
----------- -------
autopep8    1.5.4
flake8      3.8.4
mccabe      0.6.1
pip         20.2.3
pycodestyle 2.6.0
pyflakes    2.2.0
setuptools  50.3.0
toml        0.10.1
wheel       0.35.1
```
setuptools is there, but why the heck it's not usable by setup.py? Any ideas?

I solved it by removing pyproject.toml, delete poetry.lock and created a normal virtual environment using `venv`

Regards, Thomas

**Comment by NeilGirdhar** [comment]
@mosesontheweb So basically you got it working by not using poetry?  I don't see how that helps.  We want to use poetry and have an editable install.  That means, keeping pyproject.toml and poetry.lock, and not having setup.py.

**Comment by NeilGirdhar** [comment]
@mosesontheweb That particular error of missing setuptools is resolvable by having:
```
[build-system]
requires = ["setuptools", "poetry_core>=1.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by cglacet** [comment]
@finswimmer 's [answer](https://github.com/python-poetry/poetry/issues/1135#issuecomment-647390686)  makes me wonder why there is no way to **pin an answer**.  In threads like this one that would really be helpful.

**Comment by sinoroc** [comment]
@cglacet GitHub has a (beta) feature called _discussion_. I wonder if _poetry_ is eligible. That would maybe a better fit for such questions that are not bugs.

https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by max-sixty** [comment]
We have it enabled if you want to check it out — it's pretty good! 
https://github.com/pydata/xarray/discussions

**Comment by sinoroc** [comment]
https://github.com/python-poetry/poetry/discussions

I don't know if we are idiots, or blind, or if someone just played a trick on us... :D
