### ISSUE TITLE
tool.poetry.packages handles wildcards * and ** incorrectly in pyproject.toml

### ISSUE THREAD

**Issue by maggyero** [python-poetry/poetry#1379]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The [documentation gives the following example](https://poetry.eustace.io/docs/pyproject/#packages) for using the `tool.poetry.packages` property of the `pyproject.toml` file:

```
[tool.poetry]
# ...
packages = [
    { include = "mypackage" },
    { include = "extra_package/**/*.py" },
]
```

However the command `poetry build` raises the following error when the` "extra_package/**/*.py"` path pattern matches multiple files/directories in at least one the of its path segments:

```
[ValueError]
/Users/maggyero/Desktop/project/extra_package/bar/baz.py is not a package.
```

with the following directory layout:

```
project
├── .git
├── mypackage
│   └── foo.py
├── extra_package
│   └── bar
│       ├── baz.py
│       └── qux.py
└── pyproject.toml
```

Here the last `*.py` path segment of the `"extra_package/**/*.py"` path pattern matches `baz.py` and `qux.py`, which triggers the `ValueError`. Deleting the `project/extra_package/bar/qux.py` file removes the `ValueError`. And adding a `project/extra_package/quux` directory raises the same `ValueError`, since this time the second `**` path segment of the `"extra_package/**/*.py"` path pattern matches `bar` and `qux`. So it seems that matching multiple files/directories in the path segments of a path pattern is not allowed. It looks like a _bug_, because each item of the `tool.poetry.packages` list is supposed to include a single top-level module or package and optionally specific submodules (like `"extra_package/**/*.py"` which includes the top-level `extra_package` package and submodules that have a `.py` extension).

Also, since the `tool.poetry.packages` property of the `pyproject.toml` file can include both directories and files, that is to say both packages and non-package modules, I think we should rename to `tool.poetry.modules`.

**Comment by maggyero** [comment]
FYI @sdispater, @brycedrennan.

**Comment by finswimmer** [comment]
Hello,

that's the code that is responsible for this:

https://github.com/sdispater/poetry/blob/8fd63110b8de2479f3d65a86209ade65c788d96a/poetry/masonry/utils/package_include.py#L37-L63

So, whenever a glob is used, the poetry builder expect to find a `__init__.py` in the list of files after expanding the wildcards. But it doesn't expect one if only one specific folder or file is given.

To fix this issue, it is necessary to define the expected behavior. Is one allowed to include module files only? If a package should be included, is a `__init__.py` necessary (which isn't for python version > 3.3)?

fin swimmer

**Comment by finswimmer** [comment]
@sdispater , @stephsamson: I would like to work on that, but need some guidance/decision about what should actually get included if the `packages` option is used.

Would be nice if you find some time to discuss this :)

**Comment by stephsamson** [comment]
@finswimmer thanks for volunteering to work on this issue :) I am already currently working on this ticket actually which is why this has been self-assigned but there are other bugs in the low priority lane [here](https://github.com/sdispater/poetry/projects/2) which need help!

But indeed you are right, the work necessary to be done is in `package_include` and `include`. Both of them have functional tests but no unit tests which may be one reason why this issue was not caught in the first place until reported.
