### ISSUE TITLE
Build and install the root package as a wheel in one invocation

### ISSUE THREAD

**Issue by maggyero** [python-poetry/poetry#1382]
@sdispater, in https://github.com/sdispater/poetry/issues/730 you said:

> The `install` command installs the current project in editable mode by internally creating a temporary `setup.py` file and executing `pip install -e .`. It does it each time `install` is executed to ensure that any new elements like entrypoints are properly installed.

Could you allow [non-editable installations](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) by adding a `--no-editable` _command-line parameter_ for these three commands:

- `poetry install --no-editable`
- `poetry add --no-editable`
- `poetry update --no-editable`

The [documentation](https://poetry.eustace.io/docs/cli/#add) states that it is already possible for local dependencies, but with a `develop` _file parameter_ in the `pyproject.toml` file:

> If you don't want the dependency to be installed in editable mode you can specify it in the pyproject.toml file:
>
> [tool.poetry.dependencies]
> my-package = {path = "../my/path", develop = false}

Here I think that a command-line parameter would be more appropriate than a file parameter, as it is something that you want to configure at the command-line level rather than at the project level (like with `pip` where sometimes you want to run `pip install .` and sometimes `pip install -e .`). So if you could also drop the `develop` file parameter that would be awesome.

Being able to install projects in non-editable mode is so important, especially for deployment on servers. Currently we cannot use the `poetry install` command exclusively for such installations, we still have to resort to the `pip install` command.

**Comment by maggyero** [comment]
Up.

**Comment by cjolowicz** [comment]
This is an important feature for multi-stage Docker builds. 

Multi-stage Docker builds for Python typically install the project into a virtualenv during the build stage, and then copy the virtualenv over into a slim final image. An editable install creates a .egg-link file that links to the source code, and this link would only be valid for the duration of the build stage.

Currently my build stage installs projects by exporting from Poetry to pip:

```Dockerfile
COPY pyproject.toml poetry.lock ./
RUN /root/.poetry/bin/poetry export -f requirements.txt | /venv/bin/pip install -r /dev/stdin 
COPY . ./
RUN /root/.poetry/bin/poetry build && /venv/bin/pip install dist/*.whl
```

The requested feature would allow us to use Poetry directly:

```Dockerfile
COPY pyproject.toml poetry.lock ./
RUN /root/.poetry/bin/poetry install --no-root
COPY . ./
RUN /root/.poetry/bin/poetry install --no-editable
```

**Comment by arbroen** [comment]
I am using the exact same scenario as @cjolowicz but with the added configuration of a private PIP server. I cannot use the PIP_EXTRA_INDEX_URL due to security issues. Thus the solution is: 

`
RUN poetry install --no-dev
RUN rm .venv/lib/python3.7/site-packages/*.egg-link
RUN poetry build
RUN pip install dist/*.whl --target=.venv/lib/python3.7/site-packages/ --no-deps
`

A `poetry install --no-dev --no-editable` would be an improvement.

**Comment by maggyero** [comment]
@sdispater @finswimmer According to the number of thumbs up, this is an important feature. Being able to install projects in _non_ editable mode is so important. Without this, we cannot use `poetry` exclusively and still have to rely on `pip` (by calling `pip install` explicitly). Any chance this get prioritised?

**Comment by rainyday** [comment]
Currently the cleanest way I've found to do this is along the lines of

```sh
python3 -m venv /venv && \
. /venv/bin/activate && \
poetry install -n --no-dev --no-root && \
poetry build -f wheel -n && \
pip install --no-deps dist/*.whl && \
rm -rf dist *.egg-info
```

Adding this feature would cut the number of commands in half and I wouldn't have to worry about dist files getting left over in the event of a failure.

**Comment by ketozhang** [comment]
If you have your package uploaded on a online repo, `poetry add` behaviors normally.

```
poetry add git+https://github.com/user/name.git
```
This is how I've dealt with being unable to install a local package with develop mode off.

PS: I rather see the default behavior be `--no-editable` matching pip.

**Comment by rainyday** [comment]
This is also an issue with `path` dependencies, which also only install as editable rather than actually installing to site packages. Unfortunately using git repositories isn't viable in a lot of situations. Most of the stuff I work on uses a chroot or container for the build process which has no access to the user's git credentials.

**Comment by thejcannon** [comment]
I'd like to see this feature for a reason I haven't seen enumerated yet. I can't validate my wheel has all the files I expect when I run my tests with my package in editable mode. Since the files will correctly be there locally, my tests pass, however it could very well be the case that I'm not including those files in my wheel meaning the package is broken.

My solution would be that PR validation would install the package in non-editable mode. Today that's accomplished by building the wheel and installing that, but would lovee to see `poetry install --bikeshed` "just work".

**Comment by finswimmer** [comment]
> I can't validate my wheel has all the files I expect when I run my tests with my package in editable mode. Since the files will correctly be there locally, my tests pass, however it could very well be the case that I'm not including those files in my wheel meaning the package is broken.

@thejcannon Isn't this exactly why [tox](https://tox.readthedocs.io/en/latest/) exists?

**Comment by thejcannon** [comment]
@finswimmer It may/may not be, but at this point `tox` is certainly more than that feature.

I hope you aren't advocating for a testing solution that involves both `poetry` and `tox`. They overlap in responsibilities (virtual environment management and command running), and I would much prefer to stay _just_ using `poetry` 😄 .

**Comment by ckp95** [comment]
> I'd like to see this feature for a reason I haven't seen enumerated yet. I can't validate my wheel has all the files I expect when I run my tests with my package in editable mode. Since the files will correctly be there locally, my tests pass, however it could very well be the case that I'm not including those files in my wheel meaning the package is broken.
> 
> My solution would be that PR validation would install the package in non-editable mode. Today that's accomplished by building the wheel and installing that, but would lovee to see `poetry install --bikeshed` "just work".

Echoing this post -- today I couldn't figure out why my CI test for whether `py.typed` is included in the package wasn't working right. I have to use `pip install .` to make sure it's done right, but I'd like to be able to use Poetry instead.

**Comment by ShuzZzle** [comment]
Any Update?

**Comment by maggyero** [comment]
@ShuzZzle It is still in the To-do list: https://github.com/python-poetry/poetry/projects/3#card-31617262
@sdispater According to the number of thumbs up on this feature request, is there any way to make it a priority? It has been two years now.

**Comment by rszamszur** [comment]
> This is an important feature for multi-stage Docker builds.

@cjolowicz I agree. Moreover, this applies to the build process, CI/CD as well.

@maggyero In PR I've implemented `--no-editable` option just for the install command.

For add if I understand correctly `poetry add` will by default install dependency in none editable mode unless specified otherwise in `pyproject.toml`. 

Lastly, there is `poetry update` command. From the code, it seems it only updates the dependencies, not the root package (it makes sense, since it always was in editable mode). However, it'll probably require some logic to update the root package if the project is installed with `--no-editable`. Fortunately, this can be detected automatic based on if `package_name.pth` file is in project `.venv/lib/python3.x/site-packages/` directory. If so, reinstall, else do nothing. But first I'll wait for the feedback from Poetry maintainers.

Have a good one!

**Comment by johnthagen** [comment]
As @cjolowicz [mentions](https://github.com/python-poetry/poetry/issues/1382#issuecomment-564909194), this feature is **really** essential for a cleanly working with multi-stage Docker builds purely within Poetry.

If both this and venv path configuration were implemented (#1579), Poetry would have a **super** great story for Docker ❤️. Currently, it's a bit clunky to have to essentially shell out to the [`venv` stdlib module](https://docs.python.org/3/library/venv.html), an exported `requirement.txt` file, and `pip` to get the correct behavoir.
- #1579

**Comment by neersighted** [comment]
Closing this for now as covered by the `bundle` plugin, which is intended for this use case. It's still very much in development/a little rough, but that is where this functionality is going to live:

https://github.com/python-poetry/poetry-plugin-bundle

**Comment by Keramblock** [comment]
I dont think, that it should be designed as a plugin. I suggest to reopen this issue =(

**Comment by smcoll** [comment]
@neersighted i don't believe the plugin you mentioned handles the case raised by this issue. https://github.com/python-poetry/poetry-plugin-bundle/issues/37#issue-1441210576

**Comment by neersighted** [comment]
Editable mode orthogonal to whether the ability to install a package and its deps into an environment in non-path mode is possible; indeed, that is what bundle currently does. You want it to grow a --no-editable or similar flag; your issue on the other repo is the correct place to track that.

**Comment by link89** [comment]
https://github.com/python-poetry/poetry/issues/1382#issuecomment-564909194 this workaround is great but I think it is a bug of `poetry-plugin-export`  that didn't handle `develop = true` correctly. Once they fix the bug there will me no clear way to work around this problem.
