### ISSUE TITLE
Fix virtualenv to specific pyproject.toml

### ISSUE THREAD

**Issue by bsdz** [python-poetry/poetry#1403]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I've successfully converted all my projects to use poetry now. I work with a lot of repos and corresponding virtualenvs.

One thing that often bites me is accidentally installing packages into the wrong virtualenv. For example, I might have a project activated using a local virtualenv folder called ".venv". Unhelpfully, in a shell, this is displayed as "(.venv) login@host:~/some/folder $". This doesn't give any indication of the project it is in or where the virtualenv is located. So I might accidentally cd to another project folder and start adding packages using poetry to only realise when it's too late that i am adding packages to the wrong virtualenv that has same shell prefix, ie "(.venv)". 

To give a step by step:

```bash
/projects/proj_a$ poetry config --list
virtualenvs.in-project = true
...
/$ cd projects/
/projects$ mkdir proj_a proj_b
/projects$ cd proj_a
/projects/proj_b$ python3.7 -mvenv .venv
/projects/proj_a$ poetry init
/projects/proj_a$ cd ../proj_b
/projects/proj_b$ python3.7 -mvenv .venv
/projects/proj_b$ poetry init
/projects/proj_b$ . .venv/bin/activate
(.venv) /projects/proj_b$ cd ../proj_a
(.venv) /projects/proj_a$ poetry add iso8601
!! oops - installed that in proj_b not proj_a !!
```

Perhaps this only happens to me but I notice it's quite common in vscode as typically only your primary project's virtualenv tends to be activated there.

It would be nice, if poetry could somehow raise a warning or prevent you from adding packages into a pyproject.toml file (and installing them into a virtualenv) when you're in the wrong folder. One way might be to inject a "meta" package into a repo that poetry can examine. This package could store the location of the corresponding pyproject.toml or poetry.lock file.

Note: I now see there's a "--prompt" switch for venv that will override the default folder name prompt. I will use that from now although I still feel the above feature would be very useful.

**Comment by justinmayer** [comment]
Hi Blair. I think this is outside Poetry's scope. If I run `source MyProject/bin/activate`, the `activate` shell script will assume `MyProject` is the name of the project and prepend `(MyProject)` to the shell prompt. As you already seem to understand, because you are naming your virtual environment `.venv`, that is what is being prepended to your shell prompt, resulting in the ambiguity that ultimates causes your problem.

I empathize with your plight but humbly suggest that you keep your virtual environments outside of your projects in a centralized location such as `~/virtualenvs/` instead. While you may not want to change your workflow, doing so and giving your virtual environments distinct names would neatly resolve your problem.

Moreover, you've already discovered the `--prompt` flag, and I don't think Poetry should try to handle this situation any further. Attempting to handle edge cases, particularly by injecting meta-package cruft into environments, would be emblematic of the kind of overreach and scope creep from which Pipenv suffers badly.

**Comment by bsdz** [comment]
Actually it does make me wonder if perhaps poetry should apply the "--prompt" command based with a file safe version of the project name when one uses "virtualenvs.in-project = true" option. So one doesn't end up with a bunch of indistingusable virtual environments called ".venv".

**Comment by wakemaster39** [comment]
I implemented this as I was also having lots of troubles determining which virtual environment I was working inside of when they were in the project root.

I agree that exposing arguments to allow customization is a bit much in this case, but I think providing the project name instead of the default of `.venv` when in a project root provides enough value.  

I have bounced back and forth with having having my virtual environments inside the project root or outside in a centralized location. Having a specific name of `.venv` makes managing virtual environments so much easier when it comes to IDEs. 

PyCharm if I keep my virtual environment centralized and I want to change the python version I need to remap my virtual environment using the poetry naming scheme. By having it as a constant of .venv it transfers across user, systems and python versions. It also reduces complexity working with new developers on my team in that if they mess with something it is always the same command to nuke out the virtual environment and start over.

**Comment by anthem-bmk** [comment]
`poetry shell` opens a new shell with the new virtual environment activated unless you're already in _any_ virtual environment, in which case it just gives you a warning message (that actually looks a bit like a success message).

It seems like `poetry shell` could easily detect if it's in the _right_ virtual environment (i.e. if you weren't already in a virtual environment, which one would you activate/create and is it the same one you're already in?). Likewise, `poetry add` or `poetry run` could (and IMO should) do the same.

Considering commands like `poetry add` don't work without a pyproject.toml in the current or a parent dir (regardless of what virtualenv you're in), I'm not sure in what situation you would expect it to add a dependency to an unrelated virtualenv.

This is also biting me - I'm trying to create a python CLI that uses poetry to install packages for you (something akin to `poetry new asdf && cd asdf && poetry install` or `create-react-script asdf`) but if you're running that python script inside a virtualenv already then it doesn't work as you would expect and I haven't found a workaround yet.

**Comment by neersighted** [comment]
This is mostly addressed by the combination of being able to set the virtual environment prompt with `virtualenvs.prompt`, as well as the fact that Poetry deliberately allows for you to bring your own virtual environment management. Poetry's built-in features are minimal and intended for users to whom virtual environments are a distraction/implementation detail. If you need something more complex, you should simply follow a standard Python development workflow and activate your virtual environment through whatever method you would normally use. Poetry will re-use it rather than creating its own.
