### ISSUE TITLE
Dependency name RuntimeError for git dependencies

### ISSUE THREAD

**Issue by jayanthkoushik** [python-poetry/poetry#1405]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15 Beta (19A558d) 
- **Poetry version**: 1.0.0b1 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jayanthkoushik/95c23e9ef375af68c7c835480fd692b5 

## Issue

Adding a git dependency fails if the package name is different from the repository name. This does not happen with direct (pypi) dependencies. Example

```
$ poetry add git+https://github.com/tarrlab/GPy.git@1.9.2-py37 -vvv
Using virtualenv: /Users/jayanth/Library/Caches/pypoetry/virtualenvs/test-5y_22gLZ-py3.7

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on gpy (*)
   1: fact: test depends on pytest (^3.0)
   1: selecting test (0.1.0)
   1: derived: pytest (^3.0)
   1: derived: gpy (*)
PyPI: 44 packages found for pytest >=3.0,<4.0
   1: Version solving took 13.741 seconds.
   1: Tried 1 solutions.

[RuntimeError]
The dependency name for gpy does not match the actual package's name: GPy
... <TRACEBACK>
```

```
$ poetry add GPy -vvv
Using virtualenv: /Users/jayanth/Library/Caches/pypoetry/virtualenvs/test-5y_22gLZ-py3.7
PyPI: No release information found for GPy-1.0.4, skipping
PyPI: 34 packages found for GPy *
Using version ^1.9.8 for GPy

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on GPy (^1.9.8)
   1: fact: test depends on pytest (^3.0)
   1: selecting test (0.1.0)
   1: derived: pytest (^3.0)
   1: derived: GPy (^1.9.8)
... <SUCCESSFUL INSTALL>
```

**Comment by ssfdust** [comment]
Confirmed here. The same error occurs when adding package 'Flask-Admin' from git.

**Comment by ssfdust** [comment]
Confirm fixed after upgrading to 1.0.0b2. Thanks a lot.

**Comment by johannesjh** [comment]
**Similar problem in poetry 1.1.4**
I am writing this as a Note for further reference: I ran into the same error message using poetry 1.1.4. 

Details: My pyproject.toml file contains this dependency to a locally installed package named fava:

```toml
fava = { path="../fava", develop=true }
```

When running `poetry update` in my project, I got this error message: 
`The dependency name for fava does not match the actual package's name: requests`

I analyzed the problem by stepping through poetry's code. It turned that poetry's `lib.poetry.inspection.info.PackageInfo.from_metadata` function found a package inside a virtualenv instead of the actual package defined by fava/setup.cfg

**Workaround for the problem**: 
Removing the virtualenv folder from the local package folder fixed the issue

**Comment by brandon-leapyear** [comment]
@johannesjh moved this to a separate issue: #5313
