### ISSUE TITLE
poetry 1.0.0a5 has requirement requests-toolbelt<0.9.0,>=0.8.0, but you'll have requests-toolbelt 0.9.1 which is incompatible.

### ISSUE THREAD

**Issue by hvdklauw** [python-poetry/poetry#1465]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue

During installation of my packages the following error shows up:
`poetry 1.0.0a5 has requirement requests-toolbelt<0.9.0,>=0.8.0, but you'll have requests-toolbelt 0.9.1 which is incompatible.`

Everything works, because the package that used requests-toolbelt (zeep) just has the following defined: `requests-toolbelt = ">=0.7.1"`

So it seems it's switching between 0.8.0 and 0.9.1 which isn't causing a hard error right now but might cause issues in the future or for some installations.

In this case poetry is installed in the same virtual environment as the project, so one fix would be to install it outside of it, but then you might still run into the issue that it conflicts with something else installed outside.

**Comment by finswimmer** [comment]
Not sure if this issue still exists. I close this as there are no comments for a long time now.

If you disagree @hvdklauw please just leave a comment.

fin swimmer

**Comment by vgrebenschikov** [comment]
Still happens, poetry refuses to work with requests_toolbelt (~0.9)
% poetry install
Updating dependencies
Resolving dependencies... (26.8s)

[SolverProblemError]
Because no versions of poetry match >1.0,<1.0.1 || >1.0.1,<1.0.2 || >1.0.2,<1.0.3 || >1.0.3,<1.0.4 || >1.0.4,<1.0.5 || >1.0.5,<1.0.6 || >1.0.6,<1.0.7 || >1.0.7,<1.0.8 || >1.0.8,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1
 and poetry (1.0.0) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.0.1 || >1.0.1,<1.0.2 || >1.0.2,<1.0.3 || >1.0.3,<1.0.4 || >1.0.4,<1.0.5 || >1.0.5,<1.0.6 || >1.0.6,<1.0.7 || >1.0.7,<1.0.8 || >1.0.8,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).
And because poetry (1.0.1) depends on requests-toolbelt (>=0.8.0,<0.9.0)
 and poetry (1.0.2) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.0.3 || >1.0.3,<1.0.4 || >1.0.4,<1.0.5 || >1.0.5,<1.0.6 || >1.0.6,<1.0.7 || >1.0.7,<1.0.8 || >1.0.8,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).
And because poetry (1.0.3) depends on requests-toolbelt (>=0.8.0,<0.9.0)
 and poetry (1.0.4) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.0.5 || >1.0.5,<1.0.6 || >1.0.6,<1.0.7 || >1.0.7,<1.0.8 || >1.0.8,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).
And because poetry (1.0.5) depends on requests-toolbelt (>=0.8.0,<0.9.0)
 and poetry (1.0.6) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.0.7 || >1.0.7,<1.0.8 || >1.0.8,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).
And because poetry (1.0.7) depends on requests-toolbelt (>=0.8.0,<0.9.0)
 and poetry (1.0.8) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.0.9 || >1.0.9,<1.0.10 || >1.0.10,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).
And because poetry (1.0.9) depends on requests-toolbelt (>=0.8.0,<0.9.0)
 and poetry (1.0.10) depends on requests-toolbelt (>=0.8.0,<0.9.0), poetry (>=1.0,<1.1) requires requests-toolbelt (>=0.8.0,<0.9.0).

**Comment by abn** [comment]
@vgrebenschikov looks like you have `poetry` as a dependency to your package. This is not something that is recommended. 

No poetry release prior to `1.1.0` will support `requests-toolbelt >= 0.9.0`. The solver error is correct.
