### ISSUE TITLE
`python3.6 get-poetry.py -p` sets poetry up with python 2

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#1637]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**:  RHEL7
- **Poetry version**: 1.0.0b8

## Issue

My system has Python 2.7 from Red hat's python-2.7.5-68.el7.x86_64 and Python3.6 from IUS' python36u-3.6.7-1.ius.el7.x86_64.

I installed with:

```
python3.6 ~/Downloads/get-poetry.py -p
```

...but it appears that poetry has still been installed with python 2.7, so now I get these nasty warnings each time I do a poetry command:

```
$ poetry --help
/home/cwithers/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.  "program uses threads.", RuntimeWarning)
Poetry version 1.0.0b8
...
```

How can I get poetry installed so that it always uses python3.6?

**Comment by cjw296** [comment]
See https://github.com/sdispater/poetry/pull/1494

**Comment by cjw296** [comment]
https://github.com/sdispater/poetry/issues/1381 Also seems related.

**Comment by finswimmer** [comment]
Hello,

this behavior was by design. If poetry was installed with `get-poetry.py` script it would fetch up the current activated python for running due to the shebang line `#!/usr/bin/env python`. This makes it easy to create venvs with different python version just by switching the currently used python with e.g. `pyenv`.

However, `get-poetry.py` is now deprecated and will be replaced by `installe-poetry.py`. Now poetry will have it's own venv  and will therefore use the pyhon interpreter used during installation.

fin swimmer
