### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by pblh123** [python-poetry/poetry#1680]
[root@1c268bf136b9 www]# poetry --version
Traceback (most recent call last):
  File "/root/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/root/.poetry/lib/poetry/__init__.py", line 7, in <module>
    _VENDOR, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
ValueError: zero length field name in format

- **OS version and name**: Linux 1c268bf136b9 2.6.32-642.el6.x86_64 #1 SMP Wed Apr 13 00:51:26 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Poetry version**: poetry-0.12.17-linux.tar.gz
- **Python 3.6.5 (default, Dec  5 2019, 16:57:57) 

## Issue
    _VENDOR, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
ValueError: zero length field name in format

**Comment by finswimmer** [comment]
Hello @pblh123 ,

does this also happens in the latest preview version?

fin swimmer

**Comment by pblh123** [comment]
i didn't test the preview version

**Comment by scharron** [comment]
Hello @finswimmer , I have the same bug, even with the preview version

**Comment by scharron** [comment]
This was caused by poetry using the default python version of the docker image I was using (quay.io/pypa/manylinux2010_x86_64).

**Comment by mkniewallner** [comment]
This issue is quite old, and reported on a Python version (3.6) that the recently released Poetry [1.2.0](https://github.com/python-poetry/poetry/releases/tag/1.2.0) doesn't support any more).
I'm going to assume that this is not relevant any more, but if it is, feel free to reopen this issue or create a new one with a way to reproduce.
