### ISSUE TITLE
Document that `poetry install` modifies PYTHONPATH

### ISSUE THREAD

**Issue by thorbjornwolf** [python-poetry/poetry#1729]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Thank you very much for taking some of your valuable time to read this. I hope it'll be worth it!

### What happens?
`poetry install` with an existing conda environment and `src` layout silently and permanently adds `repo/src` to the environment's PYTHONPATH.
This behaviour is not documented (or, I didn't find it).

<details>

```
$ conda create -n withsrc_py37 python=3.7
$ conda activate withsrc_py37
$ poetry new --src my-src-package
$ cd my-src-package
$ poetry run python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\python37.zip',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\DLLs',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\lib',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\lib\\site-packages']
$ poetry install
$ poetry run python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\python37.zip',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\DLLs',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\lib',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37',
 'C:\\Users\\THW\\AppData\\Local\\Continuum\\anaconda3\\envs\\withsrc_py37\\lib\\site-packages',
 'c:\\users\\thw\\repos\\my-src-package\\src']  # new!
```

This change to `sys.path` persists after `conda deactivate` and `conda activate withsrc_py37`.

</details>

### Why am I surprised?
The idea (for me) with using the `src` layout is to make it really difficult to run tests against my source code. I want the tests to run against the built and installed package instead, as per [hynek](https://hynek.me/articles/testing-packaging/) and [ionelmc](https://blog.ionelmc.ro/2014/05/25/python-packaging/).

Making matters more murky, tox's test environments appear to inherit this PYTHONPATH. This puts the supposedly independent tox runs at risk of using the source code.

### Why not a bug?
I don't know if this is a bug, but I expect not: It seems that there's no consensus in the community whether the `src` layout is a good or bad idea, so this behaviour is quite possibly expected for some use cases. And besides, now that poetry is in stable, I guess documenting the current behaviour should come before changing it :grin:

### Additional details
Output of `poetry debug info`:
<details>

```
Poetry
Version: 1.0.0
Python:  3.7.5

Virtualenv
Python:         3.7.5
Implementation: CPython
Path:           C:\Users\THW\AppData\Local\Continuum\anaconda3\envs\withsrc_py37
Valid:          True

System
Platform: win32
OS:       nt
Python:   C:\Users\THW\AppData\Local\Continuum\anaconda3\envs\withsrc_py37
```

</details>

What seems to be a highly related PR, "Add src to sys.path if module is in src": https://github.com/python-poetry/poetry/pull/123

A PR that added documentation for the `--src` flag: https://github.com/python-poetry/poetry/pull/193

**Comment by pawamoy** [comment]
It's even more surprising that the `src` folder is added to the path only after `poetry install`. What is really changing between before and after the call to `poetry install`?

I tried it on my end as well:

```console
$ poetry new --src myp
Created package myp in myp

$ cd myp
$ poetry install --no-root  # just create the venv
Creating virtualenv myp-4T139N4Z-py3.7 in C:\Users\me\.venvs
Installing dependencies from lock file

No dependencies to install or update

$ poetry run python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\python37.zip',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\DLLs',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\lib',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7\\lib\\site-packages']
$ poetry run pip install .
...
Successfully installed myp-0.1.0
$ poetry run python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\python37.zip',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\DLLs',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\lib',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7\\lib\\site-packages']
$ poetry install -vvv
Using virtualenv: C:\Users\MAZZUCTI\.venvs\myp-4T139N4Z-py3.7
Installing dependencies from lock file

No dependencies to install or update

  - Installing myp (0.1.0)
$ poetry run python -c "import sys, pprint; pprint.pprint(sys.path)"
['',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\python37.zip',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\DLLs',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3\\lib',
 'c:\\users\\me\\appdata\\local\\continuum\\anaconda3',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7',
 'C:\\Users\\me\\.venvs\\myp-4T139N4Z-py3.7\\lib\\site-packages',
 'c:\\users\\me\\data\\dev\\sandbox\\myp\\src']
```

The PR you mention, #123, was sent to fix issue #122, which was an issue with `poetry script` being unable to run a script if the package was in the `src` folder.

Does it still make sense though? The code is now in the `run` command (https://github.com/python-poetry/poetry/blob/master/poetry/console/commands/run.py#L38), but I wonder: if the package was installed, the "script" you call with `poetry run my-script`, which is declared in the `[tool.poetry.scripts]` section, should be installed as well, and be available in the path without needing to add the `src` folder, which is the sources folder, to the Python path, no?

What I mean is that it only makes sense to add the `src` folder to the Python path when the package __is not__ installed, because otherwise of course Python can't find it. But when the package __is__ installed, so are its entrypoints/scripts, which are now in the `bin` or `Scripts` folder of the venv, available in the path.

```console
$ echo $PATH
/c/Users/me/.local/bin:...
$ poetry run bash -c 'echo $PATH'
/c/Users/me/.venvs/myp-4T139N4Z-py3.7/Scripts:/c/Users/me/.local/bin:...
```

Indeed, with 

```toml
[tool.poetry.scripts]
myexec = "myp.console:main"
```

After `poetry install`, in the `Scripts` folder of my venv (which is equivalent to the `bin` folder for venvs on Linux I think), I have

```console
$ ls ~/.venvs/myp-4T139N4Z-py3.7/Scripts/
activate      Activate.ps1    easy_install.exe      myexec.exe        pip.exe     pip3.exe    pythonw.exe
activate.bat  deactivate.bat  easy_install-3.7.exe  myexec-script.py  pip3.7.exe  python.exe
```

What I'm not sure to understand is why calling `poetry run python ...` seems to execute the command as if it was a Poetry script (and therefore adding `src` to Python path) instead of a normal command, passing through this code (`self.env.execute`):

https://github.com/python-poetry/poetry/blob/754dbf80dc022b89974288cff10b40ab2f1c2697/poetry/console/commands/run.py#L22-L30

https://github.com/python-poetry/poetry/blob/754dbf80dc022b89974288cff10b40ab2f1c2697/poetry/utils/env.py#L897-L935

**Comment by gkedge** [comment]
This definitely should be documented... and, I think there should be a work-around to prevent that (with caveates 

My program is augmenting `sys.path` in my `pytest`'st `conftest.py` so all the tests can find the package-under-test. Since I wanted to expect that it needed to be set, I did't test whether it was in 'sys.path' already, I asserted it wasn't in there. As I am new to poetry, I spent an afternoon attempting to figure out why was after swapping over from `pipenv`... Did not expect.

I finally figured it out with:
```
(.venv) ➜  project_dir git:(master) ✗ python -m site
sys.path = [
    '/Users/greg/PycharmProjects/project_dir',
    '/Users/greg/.pyenv/versions/3.7.8/lib/python37.zip',
    '/Users/greg/.pyenv/versions/3.7.8/lib/python3.7',
    '/Users/greg/.pyenv/versions/3.7.8/lib/python3.7/lib-dynload',
    '/Users/greg/PycharmProjects/project_dir/.venv/lib/python3.7/site-packages',
    '/Users/greg/PycharmProjects/project_dir/src',
]
```

**Comment by dedale** [comment]
Thanks a lot @thorbjornwolf for creating this issue, I've been scratching my head for two hours trying to figure out why in some cases my modules were found and ModuleNotFoundError in other cases.

**Comment by finswimmer** [comment]
Hello everyone,

as written in the [docs](https://python-poetry.org/docs/basic-usage/#installing-dependencies-only) a `poetry install` installs the current project in editable mode. This is necessary to be able to run your code immediately after changing it, without going through the cycle "edit file" -> "build package" -> "install package" -> "run command".

To achieve this poetry uses the path configuration file method described here https://docs.python.org/3/library/site.html

You can avoid installing the package itself by running `poetry install --no-root` instead.

If you want to make sure your tests are running against the builded packages, your tests should run in an isolated environment as well using e.g. tox. With pytest 6.0 `--import-mode importlib` was [introduced](https://docs.pytest.org/en/stable/pythonpath.html) to make sure to run against the builded package. I wrote about it at [stackoverflow](https://stackoverflow.com/questions/66090538/moved-from-pip-to-poetry-and-now-pytest-cov-wont-collect-coverage-data/66125760#66125760) as well.

fin swimmer

**Comment by dedale** [comment]
Thanks @finswimmer for these insights 👍.

In my case, the problem was: after `poetry new` & `poetry add` everything was running fine (`pytest`, importing my module in `ipython`, autoreload, etc.) except from the jupyter notebooks in `notebooks` folder. I had a discrepancy with another computer where I had run `poetry install` (I do not remember why). So I was confused because I needed to run `poetry install` only to be able to import my module from `notebooks` folder.
