### ISSUE TITLE
installing dephell fails 

### ISSUE THREAD

**Issue by joseph-vedadi** [python-poetry/poetry#1766]
[SolverProblemError]
Because no versions of dephell match >0.7.9,<0.8.0
 and dephell (0.7.9) depends on fissix (*), dephell (>=0.7.9,<0.8.0) requires fissix (*).
So, because no versions of fissix match *

**Comment by sdispater** [comment]
@joseph-vedadi Please fill in the issue template properly next time, thanks :-)

Regarding you issue, this is the expected behavior. Poetry will never install prereleases unless explicitly told to do so and since fissic only has prereleases available the resolver cannot find a proper solution.

This is on dephell's end and they should not use a `*` contraint for fissix but rather a constraint that includes a prerelease like `>=19.2b1`.
