### ISSUE TITLE
Poetry installation instructions for offline machine

### ISSUE THREAD

**Issue by Derynect** [python-poetry/poetry#1783]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Can we please provide instructions on how to reasonably install poetry to a machine without Internet access? Such a server would use internal pip repos and of course poetry can be installed via pip but I understand the standalone installation is preferable.

**Comment by n8sty** [comment]
Isn't it the same process as installing any other lib from a private pypi on an intranet and then managing environments / Python paths correctly?

**Comment by Derynect** [comment]
poetry's documentation states that it's preferable to install via the shell script and not via pip. I'm specifically curious about how to perform the shell install if the target machine doesn't have direct access to the internet.

**Comment by n8sty** [comment]
I poked around the `get-poetry.py` script and it looks like the `Installer.make_lib()` downloads the requested Poetry version from https://github.com/python-poetry/poetry/releases/download/{version}/. I think what needs to be done to make the above case useful is to split the downloading into it's own method and then have `make_lib` act on a file specified. If the file is already present, then that file can just be passed to the `make_lib` function instead of having to download it. I'm happy to take a crack at this in the near future assuming I'm understanding your use case @Derynect. I'm envisioning an experience sort-of like:

`python get-poetry.py --file poetry-1.0.0.tar.gz`

**Comment by Derynect** [comment]
I think that would be a great solution!

**Comment by labdmitriy** [comment]
I found pipeline for installing poetry offline with [new installer](https://python-poetry.org/docs/master/#installation) for the current implementation:  

**1. Create and navigate to temporary directory**
`cd ~ && mkdir tmp && cd tmp`

**2. Prepare required packages (with internet)**
- Save current installation code to the local file
`curl -o poetry_install.py -sSL https://install.python-poetry.org`
- Modify code to use local folder with wheels to install (poetry and its dependencies)
`sed 's/"install", specification/"install", "--no-index", "--find-links=.", specification/g' poetry_install.py > poetry_install_offline.py`
- Check which poetry versions are available (for pip >= 21.2)
`pip index versions poetry`
- Select version and download all required packages (example for version 1.1.12)
`VERSION=1.1.12; pip download poetry==$VERSION`

**3. Copy tmp directory to the machine without internet**

**4. Install poetry (without internet)**
- Uninstall existing version of poetry (if any):
`python poetry_install_offline.py --uninstall`
- Install poetry from local file (example for 1.1.12)
``VERSION=1.1.12; python poetry_install_offline.py --path `ls poetry-$VERSION*.whl` ``
- Check that it was installed successfully

**5. Remove temporary directory**
`cd ~ && rm -rf tmp`

**Comment by neersighted** [comment]
Closing as Poetry is just a wheel now -- you simply need to download the wheels with `pip download` or similar, like any other Python package.
