### ISSUE TITLE
Add flag to skip deleting unneeded libraries

### ISSUE THREAD

**Issue by aviramha** [python-poetry/poetry#1889]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Right now when I'm building my docker container I install some of the python dependencies in a custom version in the base, but when running `poetry install` it removes the package, because it's not part of the dependencies.  
Would like to hear input before submitting a PR :)

**Comment by ali-tny** [comment]
I believe that poetry doesn't remove packages that aren't in the lock file - eg, if you have no dependencies in `pyproject.toml` and install something in the venv via pip, then `poetry install`, nothing will be removed.

However, poetry doesn't seem to differentiate between the dev & main environment in this case. For eg, I include tensorflow as a dev dependency, because in production I build docker images that already have the appropriate tensorflow installation (ie CPU or GPU). I include tensorflow in the dev requirements for development. Running `poetry install --no-dev` when building production docker images removes the existing tensorflow installation!

A minimal example:
pyproject.toml:
```
[tool.poetry]
name = "test"
version = "0.0"
authors = ["Somebody <somebody@somewhere.com>"]
description = "Minimal example of poetry removing existing installations"

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]
requests = "*"
```

Simulating the requests being provided already via `poetry shell` and `pip install requirements`:
```
$ poetry lock
Creating virtualenv ...
$ poetry shell
Spawning shell ...
(venv...) $ pip install requests
Collecting requests
...
Successfully installed certifi-2019.11.28 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.8
(venv...) $ exit
$ poetry install --no-dev
Installing dependencies from lock file


Package operations: 0 installs, 0 updates, 5 removals

  - Removing certifi (2019.11.28)
  - Removing chardet (3.0.4)
  - Removing idna (2.8)
  - Removing requests (2.21.0)
  - Removing urllib3 (1.22)

```

**Comment by Mazyod** [comment]
I would also like to raise another painful issue from this side effect (of how `--no-dev` removes installed packages).

- We are attempting to build a `python:3.9` based docker image, and use poetry to install dependencies.
- For testing FastAPI, the test client uses `requests` package, which depends on `certifi`.
- Since `requests` is in the dev dependencies, `certifi` package is removed when running `poetry install`.
- This leads to `OSError: Could not find a suitable TLS CA certificate bundle` when poetry attempts to install the packages.

The workaround I applied for this is to `poetry add certifi` to explicitly tell poetry to keep this package, although my app doesn't really need it per se.

**Comment by finswimmer** [comment]
The current preview release 1.2.0a2 no longer removes packages unless the `--sync` flag is provided.
