### ISSUE TITLE
Some PyPI dependencies not installed when installing a package from a private repository

### ISSUE THREAD

**Issue by vladimir-genkin** [python-poetry/poetry#1897]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.2

## Issue

When running ``poetry install`` with the ``pyproject.toml`` containing a package from a private repository, poetry does install most of the packages from PyPI, but when it comes to installing the private package itself, it fails to install some dependencies:
```
 Looking in indexes: https://private-repository-url/+simple, https://pypi.org/
 Collecting poetry>=0.12
   ERROR: Could not find a version that satisfies the requirement poetry>=0.12 (from versions: none)

```
The workaround was to specify the PyPI source in ``pyproject.toml``:
```
[[tool.poetry.source]]
name = "pypi-repository"
url = "https://pypi.org/simple/"
default = true
```

So it seems that a possible fix is to add ``simple/`` at the end of PyPI url.

**Comment by finswimmer** [comment]
Hello @vladimir-genkin ,

what you describe is exactly this what is written in the docs: https://python-poetry.org/docs/repositories/#install-dependencies-from-a-private-repository

fin swimmer

**Comment by peterdeme** [comment]
Hey guys, we just spent 3 hours debugging this issue. @finswimmer why not auto-append /simple from the end of the URL if it's missing?

**Comment by declension** [comment]
See near-duplicate: #1942

**Comment by aperiodic** [comment]
@finswimmer the docs say that the private repository will take precedence over PyPI, but will not be used exclusively unless that source is configured as the default source. But precedence should only matter when packages with the same name (but different code) exist in multiple sources. It should not apply here, when the package that poetry cannot find -- in this case, poetry, in #1942, setuptools -- does exist, but only on PyPI. The expected behavior is that poetry falls back to PyPI when a package is not found in the private repository.

The bug here (and in #1942) is that when a package is installed from a private repository, dependencies of the private package that are on PyPI are not found (even though the private repository is not configured to be the default) because the PyPI URL that poetry passes to pip is incorrect. To demonstrate that this is the case, I added `secondary = true` to the source definition for our private repository in our `pyproject.toml`, exactly as recommended by the docs you linked to, but poetry still cannot find setuptools when trying to install a direct dependency from our private repository:

```
[EnvCommandError]
Command ['/Users/Daniel/src/work/redacted/data-atlas/env/bin/pip', 'install', '--no-deps', '--cert', '/Users/Daniel/.pip/certs/PythonIndicesCerts.pem', '--index-url', 'https://redacted.com/api/pypi/redacted-pypi/simple', '--extra-index-url', 'https://pypi.org/',
 'fucine==0.2.0'] errored with the following return code 1, and output:
Looking in indexes: https://redacted.com/api/pypi/datsci-pypi/simple, https://pypi.org/
Collecting fucine==0.2.0
  Using cached https://redacted.com/api/pypi/datsci-pypi/fucine/0.2.0/fucine-0.2.0.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /Users/Daniel/src/work/redacted/data-atlas/env/bin/python3.6 -m pip install --ignore-installed --no-user --prefix /private/var/folders/hc/c5w3vvjs221c7bbb50m9lyn40000gp/T/pip-build-env-qpmwx5_4 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://redacted.com/api/pypi/datsci-pypi/simple --extra-index-url https://pypi.org/ -- setuptools wheel:
  Looking in indexes: https://redacted.com/api/pypi/datsci-pypi/simple, https://pypi.org/
  Collecting setuptools
    Could not find a version that satisfies the requirement setuptools (from versions: )
```
Note the incorrect PyPI URL `https://pypi.org/` appears throughout, instead of the correct URL `https://pypi.org/simple`. Adding PyPI explicitly to our `pyproject.toml` as a poetry source with the correct URL `https:///pypi.org/simple` resolves the problem.
