### ISSUE TITLE
`'BinOp' object has no attribute 's'` when trying to add a git dependency with poetry

### ISSUE THREAD

**Issue by herochao** [python-poetry/poetry#1900]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Archlinux with Kernel Linux 5.4.11-arch1-1 & CentOS7 with Kernel Linux 3.10.0-1062.9.1.el7.x86_64
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml Gist](https://gist.github.com/herochao/dd49324f06582f60be349c3428bbc66c)

## Issue

When trying to add statsmodels in dev version to the project on either of the two systems using
```
poetry add git+https://github.com/statsmodels/statsmodels.git -vvv
```
(and without -vvv), I get `'BinOp' object has no attribute 's'` [(full output with -vvv)](https://gist.github.com/herochao/dd49324f06582f60be349c3428bbc66c#gistcomment-3140322)
`pip install git+https://github.com/statsmodels/statsmodels.git` works fine though.

**Comment by abn** [comment]
The reason why the add is failing is because the fallback setup.py reader does not like complex setup files very much. Same with the original issue - ast evaluation craps out.

The `extras_requires` extracted from this line is assumed to be a `List[str]` in the fallback reader.

https://github.com/statsmodels/statsmodels/blob/9bf1d0734dbb45abcfc6db7fab4564db851babeb/setup.py#L348-L348

Unfortunately for us, it is a binary operation in the AST and hence the failure.

https://github.com/statsmodels/statsmodels/blob/9bf1d0734dbb45abcfc6db7fab4564db851babeb/setup.py#L73-L77

The fallback itself is triggered when the `python setup.y egg_info` command fails when determining package information of the fresh clone. There are various reasons why this might happen. Most common in these scenarios is that the build envrionment (a clean venv as used by poetry) does not contain build time dependencies (which may include platform deps too).

Workaround for local development, would be to build a wheel and add it to the dependencies section.

```toml
statsmodels = { file = "/path/to/wheel" }
```

**Comment by jayvdb** [comment]
I have a similar case, where there is a named variable in extra_requires.

I was hoping that using the old `#egg=` suffix might work.

```py
poetry add "https://github.com/jayvdb/django-oscar/archive/release_2_0.zip#egg=django-oscar-2.0.5dev1"
An error occurred when reading setup.py or setup.cfg: 'Name' object has no attribute 's'

  RuntimeError

  Unable to determine the package name of /tmp/tmpi9nnq23l/release_2_0.zip

  at ~/projects/python/poetry/poetry/puzzle/provider.py:267 in get_package_from_file
      263│     @classmethod
      264│     def get_package_from_file(cls, file_path):  # type: (Path) -> Package
      265│         info = Inspector().inspect(file_path)
      266│         if not info["name"]:
    → 267│             raise RuntimeError(
      268│                 "Unable to determine the package name of {}".format(file_path)
      269│             )
      270│ 
      271│         package = Package(info["name"], info["version"])
```
