### ISSUE TITLE
poetry version should optionally apply an SCM tag as well

### ISSUE THREAD

**Issue by thedrow** [python-poetry/poetry#1949]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

My current workflow uses [`bumpversion`](https://pypi.org/project/bumpversion/) to search and replace all the occurrences of the version.
bumpversion also creates a git tag for us.

It'd be great to have this feature in poetry as well.

**Comment by finswimmer** [comment]
Hey, 

`poetry version` accepts a valid version number as an argument. Combining with a sub-shell command you can create any version you like in one line, e.g. `poetry version $(<command_to_get_tag>)`.

**Comment by thedrow** [comment]
But it doesn't replace all occurrences of the version in the codebase.

**Comment by neersighted** [comment]
That's a bit out of scope for Poetry proper -- `importlib.metadata` will let you get that version metadata at runtime by querying the installed package.

**Comment by georgkrause** [comment]
> poetry version accepts a valid version number as an argument. Combining with a sub-shell command you can create any version you like in one line, e.g. poetry version $(<command_to_get_tag>).

Thats true, of course, but the idea here is to gain a single point of truth for the version. Its basically error prone to run poetry version, commit the changes and set a tag (It does not really make sense the other way round, since this way the version number in the repository is not aligned to the tag). So I have to type or stack commands in three commands. 

With yarn you run yarn version, which commits the changes and set a tag - And you are done. 

If poetry rejects to provide this simple functionality, external tools are required to achieve the same workflow and we miss a chance to gain a really well integrated package manager from my point of view. Please consider to reopen this.

**Comment by thedrow** [comment]
At the very least it should be optional as an extension.
