### ISSUE TITLE
Proper one-file documentation pdf 

### ISSUE THREAD

**Issue by ghost** [python-poetry/poetry#1991]
can you please provide an all including pdf like all mature projects do. i greatly repudiate the shiny click thingy https://python-poetry.org/docs/basic-usage/  with onstop overview all 

example: https://setuptools.readthedocs.io/_/downloads/en/latest/pdf/

**Comment by dev-mbusch** [comment]
Hi there @hivemall, 

the example link you've provided doesn't work. AFAIK poetry doesn't use readthedocs as the backend for it's documentation. Otherwise you could have just used this chrome extension: https://chrome.google.com/webstore/detail/readthedocs-to-pdf/dmfcmcedgbdphhgclpffblcdlndidfmc

But you are right a one stop all pdf might be useful for some people.

**Comment by keevi-dev** [comment]
I have something; it's not very beautiful because I used "pandoc" with "xelatex" PDF engine but it has everythin what you need.
[poetry-documentation.pdf](https://github.com/python-poetry/poetry/files/7626916/poetry-documentation.pdf)

**Comment by finswimmer** [comment]
Hello everyone,

at the moment we don't plan to provide a PDF of  the documentation. If you still think this is something useful and know how to implement it, a PR is welcome :)

fin swimmer
