### ISSUE TITLE
Bundle command

### ISSUE THREAD

**Issue by sdispater** [python-poetry/poetry#1992]
As suggested in https://github.com/python-poetry/poetry/issues/537, the addition of a `bundle` command could prove useful.

There are two cases that we've seen pop up here: the ability to bundle the project and its dependencies in an arbitrary virtual environment and the ability to download the distributions to a specific directory. The former should be implemented directly into Poetry since generating a complete virtual environment makes sense to deploy a Poetry-managed project and the latter could be implemented in a plugin since it's a less common case.

### Implementation

Basically the `bundle` command will be a top-level command (similar to `env`) which will expose various sub commands.

Initially, only the `venv` sub command will be available:

```bash
poetry bundle venv my-venv/
```

If the virtual environment directory already exists it will be removed and regenerated.

Specifying a Python version to use to generate the virtual environment will also be possible:

```bash
poetry bundle venv my-venv/ --python 3.8
poetry bundle venv my-venv/ --python python3.8
poetry bundle venv my-venv/ --python /usr/local/bin/python3
```

### Extensibility

The `bundle` command should be extensible so that new sub commands can be added with the use of plugins. This means that this feature depends on the implementation of the plugin system (which is in progress, see #1237)

**Comment by kapilt** [comment]
something that came up in the context of #537  and something i've been interested in is the ability to publish packages to pypi that are fully frozen (ie incorporating lockfile deps into the upload), but keep the dev dependency set a bit more loose (per pyproject.toml). the issue we've found is semver isn't universal adhered to, and i've realized that many of our project's older pypi releases from an even a year ago aren't even installable by users due to dep graph version drift even with semver pins. 

unfortunately its not clear if thats really the intent with bundle, i'm a little unclear on the use case w/ the current description, ie. how is bundle differentiated to install command. afaict download / extract use case is a bit more common, because its a useful cache artifact for offline install or particular serverless environments, but virtualenvs aren't easily relocatable/portable per se.

**Comment by zdog234** [comment]
Is there a PR in progress for this? I'm going to have a forced staycation next week, so if I have any time left after installing ethernet, I'd love to spend some time getting the ball rolling on this

**Comment by sdispater** [comment]
@zdog234 No PR yet but a WIP branch : https://github.com/python-poetry/poetry/tree/bundle-command

Only tests are missing but the feature is almost ready.

**Comment by jtc42** [comment]
Any updates on this? The WIP branch seems to have gone a bit quiet. This would be super useful for a bunch of projects I’m involved in.

**Comment by AndrewGuenther** [comment]
@sdispater Anything I can do to help push this forward? I'm happy to do test writing grunt work if that's what's needed.

**Comment by ZlatyChlapec** [comment]
If I understood it correctly this feature should be covered by https://github.com/python-poetry/poetry-bundle-plugin. Is there anything that still needs to be done on the plugin? Can we help somehow?

**Comment by apollo13** [comment]
Given that this is covered by a plugin, can we remove the 1.2 milestone and migrate the issue (if there is anything remaining) over to the plugin repo? I feel like this shouldn't hold up the 1.2 release especially since the plugin repo can iterate more quickly.

**Comment by jwillikers** [comment]
It would be nice if the plugin worked... Any way someone can merge python-poetry/poetry-bundle-plugin#1?

**Comment by neersighted** [comment]
The plugin is exists now -- I am closing this as completed and asking that any feature requests are opened against the plugin.
