### ISSUE TITLE
On windows poetry shell always start a cmd

### ISSUE THREAD

**Issue by ggtools** [python-poetry/poetry#2030]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

On Windows it looks like `poetry shell` always spawn a cmd even when run from a Powershell window. As expected the `$SHELL` environment variable is not working. This could be worked around by using `poetry run "C:\Program Files\PowerShell\7-preview\pwsh.exe"`

**Comment by TBBle** [comment]
I'm not sure why `shellingham.detect_shell()` is not working, but always starting `cmd.exe` is because on Windows, Poetry [ignores `$SHELL` and uses `$COMPSEC` instead](https://github.com/python-poetry/poetry/blob/258ba2992309544213cbf9c9410de9b35349d8c1/poetry/utils/shell.py#L50-L51).

A quick test suggested that `shellingham.detect_shell()` should work, returning `('pwsh', 'C:\...\pwsh.exe')` as I'd expect when I just install `shellingham` from PyPI.

I tried setting `$ENV:COMSPEC` before running `poetry shell` and it broke `poetry shell`, and also `poetry run ...` and in fact any other `poetry` command, because the installation of Poetry has put a `poetry.bat` in my path, which tries to use `$ENV:COMSPEC` if it's set, to run.

So if I in-line the batch file, and set `$ENV:COMPSEC`, it works...
```
$ENV:COMSPEC="C:\Program Files\PowerShell\7\pwsh.exe"
py -3 "${ENV:USERPROFILE}\.poetry\bin\poetry" shell
```

Of course, that's not a workaround, but suggests that if Poetry honoured `$SHELL` if present, and only if absent fell back to `$COMPSEC`, it'd be doing that the help says it does.

**Comment by Issam-seghir** [comment]
> 
py -3 ${ENV:USERPROFILE}\.poetry\bin\poetry shell
this command work for me 💯
