### ISSUE TITLE
Run `pip check` during the CI

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#2043]
This little command might help to find different issues with the packages installed.
Possibly related to https://github.com/python-poetry/poetry/issues/2042

**Comment by abn** [comment]
See: https://github.com/python-poetry/poetry/pull/2044#issuecomment-803678435

Additionally, the issue here is more to do with the environment to which poetry is installed. The error in #2042 is a consequence of depenedency constraint as required by poetry it feels like.

I am closing this for now, but happy to hear back if there is still value in this change.
