### ISSUE TITLE
Unhelpful/wrong error message

### ISSUE THREAD

**Issue by nicolas-leydet** [python-poetry/poetry#2054]
On Poetry version 1.0.3

Steps to reproduce:
```
mktmpenv -p python3.7
pip install poetry
poetry init
poetry add fluent-logger
```

Error message: 
```
Using version ^0.9.4 for fluent-logger

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (^3.7) is not compatible with some of the required packages Python requirement:
  - fluent-logger requires Python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<3.9

Because no versions of fluent-logger match >0.9.4,<0.10.0
 and fluent-logger (0.9.4) requires Python >=2.7,!=3.0,!=3.1,!=3.2,!=3.3,<3.9, fluent-logger is forbidden.
So, because tmp-ef8119aac07c59ce depends on fluent-logger (^0.9.4), version solving failed.
```

The same error happens with python version 3.6 but not with 2.7
A classic `pip install fluent-logger` is installing the package without error

There's maybe an issue with fluent-logger but the message doesn't seem to describe the issue correctly.

**Comment by absassi** [comment]
I have a similar issue with PySide2, which also limits itself to `<3.9`.

I had to set my Python dependency to match exactly the PySide2's Python dependency (which is also the intersection of all Python version constraints in my set of dependencies) to be able to resolve:

    python = ">= 3.7, != 3.8.0, < 3.9"

One can argue that Poetry is correct, since `^3.7` includes Python versions `>3.9,<4.0`, for which there is no `fluent-logger` (or `PySide2`) available, so it can't really resolve them (for all allowed Python versions and platforms).

I agree the message could be more clear, stating the range of versions where the requirement fails, as I spend quite some time trying to figure out what was happening. Maybe Poetry should be clear in the error message and in the docs that dependency resolution must satisfy all allowed Python versions and platforms, and not just the currently selected environment.

**Comment by jules-ch** [comment]
@absassi

> One can argue that Poetry is correct, since ^3.7 includes Python versions >3.9,<4.0
 There is an error, the python constraint here, python=^3.7 translates to >=3.7,<4.0 during the python constaint resolution process in poetry 1.0.5.

So poetry should be able to resolve <3.9 constraint.
