### ISSUE TITLE
Support for BSDs systems (FreeBSD)

### ISSUE THREAD

**Issue by sjfbsd** [python-poetry/poetry#2159]
I can't install on freebsd.

RuntimeError: could not find poetry-1.0.5-freebsd12.sha256sum file

**Comment by abn** [comment]
@sjfbsd can you provide a bit more information on how you are trying to install poetry? 

If this is a packaging request (ie. Port Request), it might be better raised with the FreeBSD project. Relevant resources:
- https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/
- https://wiki.freebsd.org/WantedPorts

**Comment by sr-rolando** [comment]
You get this precise error when you try to install poetry via the recommended path:

`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`

**Comment by abn** [comment]
Ah this is a defficiency in the distribution packaging. I think there are a few improvements that the project might benifit from. Will try and write up a proposal soon.

You might have already done so, but I'd suggest installing poetry using pip as a workaround.

```sh
# if current user does not have su privileges
pip install --user poetry

# for global installation
pip install poetry
```

**Comment by sr-rolando** [comment]
Thanks! And yes, indeed: at least I did the installation by means of pip, of course.

If you have a pointer on how to support providing a FreeBSD build for the distribution packaging (or the like), I'm happy to pick that up.

**Comment by abn** [comment]
@sr-rolando the best I can do is point you to the relevant parts of the code for building the release. I am by no means a FreeBSD user and only have a passing familiarity with it. I should also point out that GitHub Actions does not (atleast as far as I am aware) provide a FreeBSD runner. So we'll have to either host our own runner for build, bootstrap a bsd vm or use  something like [Cirrus CI](https://cirrus-ci.org/guide/FreeBSD/) for testing and release (similar to what is being done for MacOSX and Windows).

The linux release is created by the following snippet. The release script is available at the repo root.
https://github.com/python-poetry/poetry/blob/05a3c85f8a7902f572cbda8eb23701a9a56dafa2/Makefile#L49-L52

Since the `manylinux` container used to build the linux release, you will need a similar mechanism for BSD builds. Note that the use of `manylinux` allows for ABI compatibility between different distros and their corresponding releases.

On a relevant note. iiuc, FreeBSD provides [Linux Binary Compatibility](https://www.freebsd.org/doc/handbook/linuxemu.html), if this works then it might simply be a matter of checking for `freebsd*` platform in the `get-poetry.py` script and using the `linux` platform tarball. You could test this by hardcoding the urls in the script to perform the install.

https://github.com/python-poetry/poetry/blob/bb9582c98d21a4f6340b049c9d7ab41f51e74c3f/get-poetry.py#L527-L529

But yes, here be dragons. :dragon: 

For the other platforms, it seems that the following commands on the correct host will suffice. Although, I am not sure how platform independent the [sonnet](https://github.com/python-poetry/poetry/blob/master/sonnet) script is.

https://github.com/python-poetry/poetry/blob/05a3c85f8a7902f572cbda8eb23701a9a56dafa2/Makefile#L39-L42

The entire process is automated in the [Github Actions Release Workflow](https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml).

Hope this helps!

**Comment by sr-rolando** [comment]
@abn Thanks, that's surely something to work on. Currently, I'm not aware of a FreeBSD-based Docker image. But we'll see what we can do here.

**Comment by eugenetriguba** [comment]
Has this been resolved with the new install-poetry script that I believe will be officially used for v1.2?

```
~/src/poetry/install.python-poetry.org (main) % python -V
Python 3.8.13
 ~/src/poetry/install.python-poetry.org (main) % python install-poetry.py
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/eugene/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13): Done

Poetry (1.1.13) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

 ~/src/poetry/install.python-poetry.org (main) % poetry --version
Poetry version 1.1.13
 ~/src/poetry/install.python-poetry.org (main) % freebsd-version
13.0-RELEASE-p11
```

```
~/src/poetry/install.python-poetry.org (main) % curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.zshrc

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.13
Traceback (most recent call last):
  File "<stdin>", line 607, in _make_lib
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1118, in <module>
  File "<stdin>", line 1114, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 555, in install
  File "<stdin>", line 575, in make_lib
  File "<stdin>", line 610, in _make_lib
RuntimeError: Could not find poetry-1.1.13-freebsd13.sha256sum file
```

**Comment by abn** [comment]
@eugenetriguba you are correct. This has been resolved with the [new installer script](https://python-poetry.org/docs/master/#installation). This can be used for older Poetry versions as well. The source for the installer is available at https://github.com/python-poetry/install.python-poetry.org and is considered stable.

The `get-poetry.py` script will officially be removed from the main branch once we release 1.2.0.

Closing this as there is no action left.
