### ISSUE TITLE
Non-greedy version of adding/updating/locking

### ISSUE THREAD

**Issue by spapanik** [python-poetry/poetry#2201]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When adding a new package, or running `poetry lock` after updating the version for a dependency, the lock is greedy; all packages are updated as much as possible.

This is behaviour is not always ideal. It's better (as a logical separation of commits) to have a non-greedy version to updating the package, and then to run the greedy version of update

**Comment by finswimmer** [comment]
`poetry add` only updates other dependencies if the dependency tree cannot be resolved otherwise.

The intention of `poetry lock` is to discard the current locked version reevaluate the dependency tree. There is a `--no-update` flag which is useful, if you've edit the `pyproject.toml` by hand and the lock file should be updated without updating the locked version where possible.
