### ISSUE TITLE
Timer appears dark on dark terminal

### ISSUE THREAD

**Issue by jtrakk** [python-poetry/poetry#2228]
With a dark terminal background, the timer is hard to see.

![image](https://user-images.githubusercontent.com/43392409/77696726-1011b080-6f6b-11ea-8185-6992b68704ac.png)

**Comment by bhaveshpraveen** [comment]
I'd like to work on this issue if no one's picked it up yet.

**Comment by abn** [comment]
@bhaveshpraveen feel free to, but @sdispater might have some thoughts here. I'd suggest creating a draft PR if you have a solution to propose.

**Comment by sdispater** [comment]
This issue was caused by the fact that we were using a black color in bold which could be too dark in some terminals and this has already been fixed in this PR: #2230.

This was already reported in https://github.com/python-poetry/poetry/pull/2150.

So I am closing this since it's already been handled.
