### ISSUE TITLE
OS-specific requirements ignored when installing conan on OSX

### ISSUE THREAD

**Issue by StefanUlbrich** [python-poetry/poetry#2269]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX Catalina (10.15.4)
- **Poetry version**: 1.0.1 and 1.1.0a1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/StefanUlbrich/a96db0c6258a4d61e43c9cf85390862f

## Issue

Problem occurs when installing conan (C++ dependency manager) in Poetry. Their setup.py has special requirements on OSX(`if platform.system() == "Darwin"`) but they are ignored when installing through poetry. However, installation with plain pip in a virtual environment works fine. See the gist for pyproject.toml, poetry.lock, output for `poetry run conan --help` and `poetry add -D conan -vvv`

**Comment by abn** [comment]
### Workaround
As a temporary workaround you can add the dependency as a git dependency.
```
conan = { git = "https://github.com/conan-io/conan.git", tag = "1.24.0" }
```

### Root Cause
The root cause for this is the way we identify requirements from sdist. Right now, we attempt the following in order finishing at the first successful case.

1. Gather requirements from `PKG-INFO`
https://github.com/python-poetry/poetry/blob/7b1fd0cd0888f0f97db647fddf3d86052bbabd82/poetry/utils/inspector.py#L103-L106

2. Find and retrive information from existing `egg-info` directories in source bundle.
https://github.com/python-poetry/poetry/blob/7b1fd0cd0888f0f97db647fddf3d86052bbabd82/poetry/utils/inspector.py#L154-L176

3. Inspect setup using our fall back setup reader implementation.
https://github.com/python-poetry/poetry/blob/7b1fd0cd0888f0f97db647fddf3d86052bbabd82/poetry/utils/inspector.py#L178-L196

In the case of `conan` the project's sdist already contains `egg-info` generated by their build system. However, `PKG-INFO` does not containe `Requires-Dist` entries. The `requirements.txt` included here only contains the requirements for their build environment, this means no darwin dependencies are included when we complete inspection at (2).

### Possible Resolution(s)
While in theory this is an issue of the `sdist` not being in the expected format, considering this is a common scenario we should make our handling of `sdist` insepection unified (eg: pypi download vs url package). We should investigate improvements to make this a bit more robust.

Additionaly we should also add some additional information in the debug logs to facilitate debugging such issues.

**Comment by dimbleby** [comment]
conan has used markers since https://github.com/conan-io/conan/pull/6798, this can be closed
