### ISSUE TITLE
On Windows: poetry env use an exist environment still create an new environment 

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2316]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## On Windows: poetry env use an exist environment still create an new environment 

i have create an environment `` using `virtualenvwrapper-win` 
1. create an environment `evntest`
```sh
E:\>cd envtestproject

E:\envtestproject>workon envtest

    virtualenv "envtest" does not exist.
    Create it with "mkvirtualenv "

E:\envtestproject>mkvirtualenv envtest
Using base prefix 'c:\\python36'
New python executable in C:\Users\lei\Envs\envtest\Scripts\python3.exe
Also creating executable in C:\Users\lei\Envs\envtest\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

(envtest)  E:\envtestproject>
```
2. use the created environment, **But** the poetry create an new environment again.
```sh
(envtest)  E:\envtestproject>poetry env use C:\Users\lei\Envs\envtest\Scripts\python.exe
Creating virtualenv envtestproject-jc1tUJqj-py3.6 in C:\Users\lei\AppData\Local\pypoetry\Cache\virtualenvs
Using virtualenv: C:\Users\lei\AppData\Local\pypoetry\Cache\virtualenvs\envtestproject-jc1tUJqj-py3.6

(envtest)  E:\envtestproject>

(envtest)  E:\envtestproject>poetry env use python3
Using virtualenv: C:\Users\lei\AppData\Local\pypoetry\Cache\virtualenvs\envtestproject-jc1tUJqj-py3.6
```

Should not it use the environment i wrote on comand line?

**Comment by finswimmer** [comment]
Hello @leileigong,

there is no way to tell poetry explicit which env it should use. There is a feature request somewhere.

With `poetry env use` you tell poetry which python interpreter it should use. And based on that, it will create an environment or looks up, if there is already one it knows about.

If you don't like the places where poetry places it's environments (`.venv` within the project folder if `virtualenvs.in-project true ` otherwise `{cache-dir}/virtualenvs`), you can activate the venv manually before starting to work with poetry. poetry will than use the activated env.

fin swimmer
