### ISSUE TITLE
WIN: Missing __init__.py in nested packages directory

### ISSUE THREAD

**Issue by ryshu** [python-poetry/poetry#2335]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Family - 2004
- **Poetry version**: 1.0.5

## Issue

On windows, during `poetry install`, all succeed but installer build packages without `__init__.py` files between nested directory of package, and then all imports on modules are unresolved.

![image](https://user-images.githubusercontent.com/22155261/79884550-98159980-83f5-11ea-8fa0-ceff705aeb0f.png)

Full path in `.venv`: `.venv/Lib/site-packages/spikeelabs/common/*`

Unable to reproduce the error on WSL / WSL2

## Config

```toml
virtualenvs.in-project = true
```

**Comment by abn** [comment]
@ryshu are you able to share the `pyproject.toml`? Would I be correct in assuming the problem occurs when building the pakckage from PowerShell?

**Comment by abn** [comment]
It appears that you are talking about `__init__.py` not being present for `spikeelabs.common` namespace once you execute `poetry install`. If this is the case, and it is a packaged as a [native namespace](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages), there will not be an `__init__.py` file associated with it. If it is not, all packages providing the namespace must include either a [pkgutil-style](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages) or [pkg_resource-style](https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages) `__init__.py` files.

I have attempted to reproduce the issue with little luck. I attempted to emulate your project structure without the private dependencies. The following command succeeds after a `poetry install` in WSL, git-bash and PowerShell.

```sh
poetry run python -c "import spikeelabs.common.api"
```

From the information provided, I'd think that the issue lies within how the namespace package is defined and not necessarily how poetry handles the included files. If you think this is not the case, it would be immensly helpful if you can provide a sample project where this occurs without any private dependencies.

**Comment by ryshu** [comment]
Hum, try to re-install all and got expected `__init__.py` files.

Maybe due to memory overflow on local computer but still inexplicable (got some issue for multiple projet).

Try to reproduce it with with exactly the same repository without owner code but could never reach the same bug.

Sorry and thank you for your time

**Comment by abn** [comment]
@ryshu happy to help. Will close this issue for now, feel free to open a new one if you are able to reproduce this issue.
