### ISSUE TITLE
Don't use 1.x for 1.1 release, use a 2.x

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#2384]
2c - looks like release 1.1.x will break all the projects using any 1.0.x versions of poetry because the TOML specs/schema is changing, so this should be a 2.x release and then any patches for bug-fixes etc. can be applied to the 1.x series as expected.

**Comment by sdispater** [comment]
Is this related to #2361?

> This introduces changes to the lock file which are backwards compatible (new versions of Poetry won't break with the older lock files) but not forward compatible (older versions of Poetry might break with this new lock file format).

If so then I don't think it warrants a major version bump since it's backwards compatible. Forward compatibility was never a promise and does not affect the versioning whatsoever.

And even if people need to downgrade their Poetry version for any reason, executing `poetry lock` will create a new lock file compatible with the current version so complete breakage of current projects is unlikely.

That being said, we will see if we can alleviate this in the next `1.0.6` bugfix release to make sure that downgrading is possible even though there is no guarantee there because the resolution logic has changed quite a bit on the `develop` branch so that might prove difficult.
