### ISSUE TITLE
Packaging instructions for Debian, Ubuntu, etc.

### ISSUE THREAD

**Issue by venthur** [python-poetry/poetry#2486]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Trying to package poetry for Debian, it is unclear what needs to be done. Usually Python packages come with a setup.py which makes packaging straightforward -- but this package does not.

Next stop is the Makefile. Looking at it, it seems like poetry is using poetry to build itself, which creates a circular dependency.

Since the Debian build machines are not allowed to download stuff from the internet at build time, all the vendored dependencies must be in the source tree before the build starts. The package maintainer will probably include it in its version of the source tree.

So I assume what needs to be done in order to bootstrap is:

* have one command to fetch all dependencies
* install dependencies
* use something like `$ python -m poetry.console build` to break the circular dependency and use poetry from the source tree?

If that is correct, it would be nice to have one command that downloads all dependencies poetry needs to bootstrap itself (but does not install them or poetry immediately).

**Comment by jaredvacanti** [comment]
I'm also interested in getting poetry into a Debian package. I've noticed here: https://github.com/python-poetry/poetry/blob/master/get-poetry.py#L1046 that it is possible to install from an offline file. I'm not sure yet what file it expects or where it is available. (Any objections? I am just doing preliminaries. Maybe it's used for something else.)

For reference, there is a Debian bug tracking this as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947261

**Comment by abn** [comment]
Poetry's `get-poetry.py` is used as an installer not necessarily built for distribution packaging. Poetry should be treated as any other python package that support [PEP 517](https://www.python.org/dev/peps/pep-0517/), ie. built using a PEP 517 build frontend.

The (upcoming) desired way to build such wheels are to rely on [python-build](https://github.com/pypa/build). If this is not available couple of options are available; 

1. bootstrap poetry and use `poetry build`.
2. use `pip`
    a. `pip wheel` to build the package wheel, however this will also download and build dependency wheels.
    b. `pip install --prefix=/buid/root/ --no-deps /path/to/src`

**Comment by venthur** [comment]
@abn I think you're missing the point. We're asking for a list of dependencies, or a way on how to get those dependencies **before build** -- otherwise we can't package poetry for Debian, Ubuntu, etc. As the build machines are not allowed to download stuff from the internet at build time.

The way a build works in a nutshell is that you provide the source, a list of build-dependencies and a script and then build everything on a machine w/o internet. In this case here, we probably have to add the vendored dependencies to the source and use that as "the source". In order to do that, we need a way to get the dependencies before the build starts.

**Comment by abn** [comment]
@venthur I am not sure I follow why you need the dependencies in-tree. Since, I suspect similar to RPMs, you'd want to declare the dependencies as package metadata and not include in your package. 

The vendored dependencies are only used for poetry installed using `get-poetry.py` and the platform specific distribution files used are attached to the release tags. But, I do not recommend using this for system packaging. 

Poetry itself is the same as any other PEP 517 python package. It does not rely on vendored packages or sources that are not in the vcs tree. 

The dependencies of `poetry` and any `poetry` (or other PEP 517 backend) managed package can be found in `tool.poetry.dependencies` section of the `pyproject.toml`.

**Comment by sinoroc** [comment]
@venthur Thanks to _PEP517_ it is pretty standardized now. As @abn mentioned you might want to look at [_PyPA_'s _build_ tool](https://pypi.org/project/build/)  and _PEP 517_ in general, so that you can solve the packaging process once and for all for all projects that use a _PEP 517_ conform builder (instead of solving just for one project: _poetry_).

**Comment by venthur** [comment]
@abn thanks! I was missing the `tool.poetry.dependencies` which was exactly what I was looking for.

Of course vendoring is basically the last resort, and having the dependencies as Packages in Python and use those is the preferred solution. But sometimes that is not possible as either some packages require specific pinned versions of dependencies or the dependencies are not packaged at all for Debian.

**Comment by abn** [comment]
I am going to close this as it seems the original question has been answered.
