### ISSUE TITLE
Feature Request: Include folder without being installed

### ISSUE THREAD

**Issue by msiemens** [python-poetry/poetry#2513]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'd like to include tests in my project within the distributed source distribution. But of course I don't want the tests to be installed as a package.

My project layout is like this:

```
- project_name
- tests
```

When I set `includes = ['tests/*']`, the tests will be installed as a package. This is due to the generated `setup.py` file containing:

```
package_data = \
{'': ['*']}
```

This means that all Python packages are installed which includes the `tests` folder. But I want to include the tests in the source package WITHOUT them being installed.

**Comment by JWCook** [comment]
I was trying to figure this out as well, and I think this works the way you want if you use `include` instead of `packages`. Also, 
the per-format packages support added in https://github.com/python-poetry/poetry/pull/1133 appears to also apply to `include`, although I don't see that in the docs.
```toml
include = [
    { path = "tests", format = "sdist" }
]
```

I noticed this in poetry's own `pyproject.toml`, recently updated in #4007.

**Comment by finswimmer** [comment]
Works exactly as @JWCook said :+1:
