### ISSUE TITLE
Fix subdependency versions, while keeping subdeps separated from direct dependencies.

### ISSUE THREAD

**Issue by stefanoborini** [python-poetry/poetry#2546]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

In my current employment I have regulatory needs to ensure a given environment is always reproducible and well specified. Examples of this process can be found e.g. in IEC-62304 software for medical devices and it's common in high-risk software industry.

At the moment, if I have a python package with dependencies and create a lock, that lock is well defined and addresses the requirement above. However, if I keep on developing, maybe add a new dependency, other packages that are subdependencies of my packages may be bumped up, e.g. because pypi has now a new version.

I would like to be able to constrain, or preserve, the current versions of subdependencies. I am developing a similar tool to poetry for R packages (unfortunately not publicly available, for now, but I am working on it) so I gave the problem a thought already.

One option is to get poetry to upgrade the lock by examining the current lock, creating the new one, and try to preserve the old versions. In other words, with the addition of a new dependency, the most recent dependency tree must be found, and then the tree must be checked with the current tree available in the lock.

The second option is to have an additional section in the pyproject.toml to specify subdependency constraints manually. At the moment one can certainly enforce specific versions of subdeps by specifying them as dependencies, but it would be nice to be able to differentiate direct dependencies and subdependencies in separate categories.

Do you have any ideas, considering your experience against my requirement?

**Comment by ruidc** [comment]
Perhaps this new feature will help us with this: [dependency groups](https://python-poetry.org/blog/announcing-poetry-1.2.0a2/#dependency-groups)

**Comment by absassi** [comment]
I'm not 100% sure, but I believe this is fixed already with the new resolver in versions 1.1.x. At the very least, Poetry is able to do that if you add the dependency manually to pyproject.toml and then run `poetry lock --no-update`.

**Comment by finswimmer** [comment]
Hello,

Poetry won't update any dependency on `poetry add` if it's not  necessary. If you find a case where this happens, please report it :pray: . For the case of manually editing the `pyproject.toml` running `poetry lock --no-update` - as suggested by @absassi - is the way to go.

fin swimmer

**Comment by fievelk** [comment]
@finswimmer Just to have a confirmation on this: what's the current best practice to update a sub-dependency of a project? Do you recommend explicitly adding the sub-dependency in `pyproject.toml`, even though it's not directly used anywhere in the project?

**Real example (to provide more context)**
A security vulnerability has been recently identified in `certifi` ([CVE-2023-37920](https://nvd.nist.gov/vuln/detail/CVE-2023-37920)) and was fixed in version `2023.7.22`. However, `requests` defines [`certifi>=2017.4.17`](https://github.com/psf/requests/blob/8b560ecb24ee4fa4e839272dcf2653a4fa525a34/setup.py#L65) in its dependencies. 
So Poetry can use a version where the vulnerability issue is still present. What's the best way to tell poetry to install the fixed version of certifi (`>=2023.7.22`)?
Please note that this has been disclosed to the `requests` team, and they have decided to not fix the `certifi` version on their side: https://github.com/psf/requests/pull/6494
> This change isn't required. Requests already supports the latest version of cryptography and users are free to upgrade as needed.
