### ISSUE TITLE
Poetry 1.1.0a2 includes python code in the version string

### ISSUE THREAD

**Issue by PetterS** [python-poetry/poetry#2597]
To reproduce:

1. `poetry init` with default choices; no dependencies.
1. `poetry add pytest-cov`
1. `poetry install`

The last command prints:
```
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

- Updating pytest-cov (2.10.0 import os, sys;exec('if \'COV_CORE_SOURCE\' in os.environ:\n try:\n  from pytest_cov.embed import init\n  init()\n except Exception as exc:\n  sys.stderr.write(\n   "pytest-cov: Failed to setup subprocess coverage. "\n   "Environ: {0!r} "\n   "Exception: {1!r}\\n".format(\n    dict((k, v) for k, v in os.environ.items() if k.startswith(\'COV_CORE\')),\n    exc\n   )\n  )\n') -> 2.10.0) 
```

**Comment by PetterS** [comment]
This means that `pytest-cov` is always updated on install.

**Comment by snejus** [comment]
Same here:
```bash
Package operations: 0 installs, 8 updates, 0 removals
  ...
  - Updating pytest-cov (2.10.0 import os, sys;exec('if \'COV_CORE_SOURCE\' in os.environ:\n try:\n  from pytest_cov.embed import init\n  init()\n except Exception as exc:\n  sys.stderr.write(\n   "pytest-cov: Failed to setup subprocess coverage. "\n   "Environ: {0!r} "\n   "Exception: {1!r}\\n".format(\n    dict((k, v) for k, v in os.environ.items() if k.startswith(\'COV_CORE\')),\n    exc\n   )\n  )\n') -> 2.10.0)
  ...

**Comment by abn** [comment]
The root cause of the issue is the content of the `pytest-cov.pth` file.
```py
import os, sys;exec('if \'COV_CORE_SOURCE\' in os.environ:\n try:\n  from pytest_cov.embed import init\n  init()\n except Exception as exc:\n  sys.stderr.write(\n   "pytest-cov: Failed to setup subprocess coverage. "\n   "Environ: {0!r} "\n   "Exception: {1!r}\\n".format(\n    dict((k, v) for k, v in os.environ.items() if k.startswith(\'COV_CORE\')),\n    exc\n   )\n  )\n')
```

Poetry, when detecting installed packages attempts to read the `pth` file associated with the package if one is available. However, we do not execute the code to detect dynamic path not doe we handle multiple directories. This could be done, but might open up a few other concerns. This part of the code needs to be revisited at somepoint anyway. As a temporary fix, we can simply ignore the file if it is not a valid directory. However, a proper fix will need to take into consideration that this file [can contain executable code as well as multiple entries](https://docs.python.org/3/library/site.html).

https://github.com/python-poetry/poetry/blob/687a897e85ce1668ffee746bf050cc9f0bdf0fb1/poetry/repositories/installed_repository.py#L52-L63
