### ISSUE TITLE
Path dependencies cannot have version constraints

### ISSUE THREAD

**Issue by jonapich** [python-poetry/poetry#2693]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). (not applicable)

- **Ubuntu 18.04**: 
- **Poetry version 1.0.9**: 

## Issue
I am making a quite extensive use of `path` dependencies. Unfortunately, poetry's schema will not allow you to write this:
`package = { path = "../package/", version = ">=0.10" }`

Doing so will cause poetry to complain that this is invalid under any of the provided schemas.

I have worked around the issue by moving the path to the dev section:

```
[tool.poetry.dependencies]
package = { version = ">=0.10", source = "private.pypi" }

[tool.poetry.dev-dependencies]
package = { path = "../package/" }
```

This seems to work, and might actually be the correct way to do it. If it's correct, I think an example should make it to the documentation. If it's a bug, then please don't break my working scenario while fixing it :sweat_smile: :sweat_smile:

**Comment by tomzx** [comment]
I'm not sure whether it makes sense to have the same package available both as a full dependency and a dev dependency. This could technically be seen as having the same dependency twice in either section (`tool.poetry.dependencies`/`tool.poetry.dev-dependencies`).

If you were to create a `poetry.lock` file where you have those constraints and the package defined in the `dependencies` has dependencies that are widly different than those in the `dev-dependencies` package, I would assume that poetry just picks one out of the two.

Being able to specify a constraint on a package that is path defined does make sense so it would probably be preferable to only define the initial version you tried, since it's also the most intuitive.

**Comment by jonapich** [comment]
With 1.1.0, it is now necessary to use `develop = true` with local paths in my scenario. (ref: #3275 ) Therefore, here's an update of the use case which currently work:

```
    [tool.poetry.dependencies]
    package = { version = ">=0.10", source = "private.pypi" }

    [tool.poetry.dev-dependencies]
    package = { path = "../package/", develop = true }
```

- This will work as direct dependencies: the dev version is considered and no version is checked
- This will work as a transitive dependency if the version exists in the private repo

This will not work as a transitive dependency until the package is published because then the dev section is ignored, leaving only { version = ">=0.10", source = "private.pypi" } to be evaluated. This is "annoying" because when you want to bump the constraint, it's because you need the changes that you are currently working on.

Perhaps this could be an interesting way to support it:

```
    [tool.poetry.dependencies]
    package = { version = ">=0.10", source = "private.pypi", develop = "../package/" }
```

This lets us keep the dependency outside the dev section while providing a way for devs to use the in-tree code by reading the non-dev section?

**Comment by jonapich** [comment]
We have since made that project open source, so if you need a working copy, it's [here](https://github.com/coveooss/coveo-python-oss).
