### ISSUE TITLE
What is egg-info folder

### ISSUE THREAD

**Issue by bartekpacia** [python-poetry/poetry#2757]
Hi! I've just started using Poetry because it looks awesome. I created a new project using `poetry new ...` and then `poetry install`, and a folder called `<my_project_name>.egg-info` was created in my root directory. I've searched for some info about info but I didn't find anything. I think it should be better documented, e.g I don't know whether it should be checked into git or not.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by abn** [comment]
Hi @bartekpacia the creation of the `egg-info` is done by [distutils](https://docs.python.org/3/library/distutils.html) as described in [PEP 376](https://www.python.org/dev/peps/pep-0376/).

The reason why `poetry install` causes the creation of this is because, `poetry <= 1.0.10` relies on [setuptools](https://setuptools.readthedocs.io/en/latest/) to for the editable installation of the project under development. This is the same if you were to `pip install -e .` a project using `setuptools`.

This and similar directories are generally included in common python ignore files.

https://github.com/github/gitignore/blob/218a941be92679ce67d0484547e3e142b2f5f6f0/Python.gitignore#L9-L27

This behaviour is changing as of `1.1.0` (including current pre-release) as we have moved away from needing to generate a `setup.py` file to enable editable installs. Although, it is a good idea to base your ignore file off the above file.

**Comment by bartekpacia** [comment]
Thank you @abn! This is a good clarification:)

**Comment by athuljain2311** [comment]
What does '-e .' do?

**Comment by jtbrower** [comment]
### Over a Decade and I am still Learning git
Hello @athuljain2311, I could tell by the class content in your "FSDS_Assignments" repository, and the nature of your question that you have, I am logically guessing, only recently embarked on a new journey with Python, Poetry, and 'git' too. 

First of all, I hope your class went really well and secondly, I may feel really dumb if you know the details I am about to mention, but just know I responding only because your question has not been answered and most likely nobody saw it, but just as likely is that they did see it and are intentionally ignoring it due to convention.

The software system behind github.com is called git and in addition to git being a file version control system, it provides other collaborative features such as Issue Tracking.  At the top of this page is a title and a number that represent this current issue being tracked. The reason nobody responded to your very valid question is because this issue you commented on has been marked as closed. (In the top left-hand corner of the screen there is a purple elliptical shape that states "Closed" inside of it.)

For the folks managing large public repositories such as python-poetry, in a best-case scenario, once an issue is Closed, they would never have to deal with it for as long as they live (Joking but not Joking! This repository has seen 4,752 closed issues with 583 currently open. Neither indicate a state of stability or instability and I mention them only to give an idea how busy a public repository owner can be.) 

That said, you are going to find that the etiquette on when it is "ok" to comment on a closed issue varies by context, content, project and repository owner to name a few. 

That said, the one unwritten rule is **NOT** that you should never comment on a closed issue, on-topic comments are often the reasons why closed issues get re-opened. The repository owner has the rarely used lock that ensures nobody can write a comment, but it's often used for Issues that get out of control in length or tones between those commenting (to provide two of many examples). 

The unwritten rule **is** that you should **not** expect a reply from anyone.

The exception being cases where you direct the question to a specific person using the at symbol followed by the person's git username.

Finally, I want to emphasize that the amount of text I typed in this reply should not be viewed as proportional to the severity of commenting on a closed Issue. I just wanted to share a little about how git works so you can get answers to all your questions. If I were you, I would have tagged one of the participants directly. There are just some topics so new that you may not even be sure what to Google.

If you have any questions about anything I am talking about, feel free to reach out to me through my git profile.

### What that '-e' does that @abn Mentioned
The -e option in pip install stands for "editable". When you use pip install -e path/to/package, it installs the package from a local path in editable mode. This means the package is installed in such a way that changes to the source code immediately affect the installed package without needing a reinstall. This is useful for development on a Python package.

### As for me Commenting on this Closed Issue
I have never commented on a closed git Issue with the intent of helping others and admit that making a habit doing so in itself would not be acceptable either.

**Comment by bartekpacia** [comment]
wtf is that

**Comment by bartekpacia** [comment]
that's a mouthful

**Comment by bartekpacia** [comment]
wow
