### ISSUE TITLE
"Install" hangs with poetry as a forgone dependency with "virtualenv.create false"

### ISSUE THREAD

**Issue by bentheiii** [python-poetry/poetry#2766]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS:** docker linux
- **version:**: 1.1.0b2
- **Gist with the contents of your pyproject.toml file**: https://gist.github.com/bentheiii/df07d92cdc978b5d6742670a50f2405f

## Issue
When specifying `poetry` as a dev-dependancy (or optional dependancy), any attempt to install it with `virtualenvs.create false` hangs indefinitely, even if the dependency is not to be installed (and thus should not affect the installation).

**Comment by abn** [comment]
@bentheiii this could be an issue because you are using `--no-dev` option. This will mark the already installed `poetry` dependencies in your system environment as removable. This could potentially be causing issues with poetry's runtime.

As a workaround you could do something like this;
```Dockerfile
RUN poetry config virtualenvs.create false
RUN poetry export -f requirements.txt > /usr/src/app/repoet/requirements.txt
RUN pip install -r /usr/src/app/repoet/requirements.txt
```

As a side note, adding poetry as a package dependency is not recommended as this can cause more issues than it solves. Is the motivation here to ensure that developers have a certain version of poetry installed?

**Comment by bentheiii** [comment]
The motivation is that the project could be installed both as a non-virtual env (in docker) and as a virtual env in development environments.

**Comment by sohaiberrabii** [comment]
Closing as this is no longer an issue with Poetry 1.2.1
