### ISSUE TITLE
env script failes on centos uses export not setenv

### ISSUE THREAD

**Issue by saarwasserman** [python-poetry/poetry#2775]
running $HOME/poetry/env script in order to add 'poetry' to PATH **fails on centos**.

need to add to the script support for centos and its family to run setenv PATH $HOME/.poetry/bin:$PATH

**Comment by abn** [comment]
@saarwasserman `setenv` is for `csh` shells. CentOS uses `bash` as it's default shell and hence export is supported. This might be an issue caused by the shell you are using.

**Comment by saarwasserman** [comment]
@abn So, shouldn't it be based on the shell used and not the os or both?

**Comment by abn** [comment]
@saarwasserman the issue is the shell detection, as far as I am aware, on RH distros using `tcsh` (which I suspect is how you are getting `csh` - guessing as I do not have any information regarding your environment), the environment variable `SHELL` is set to `/usr/bin/bash` which I think is coming from the login shell.

The following was executed on a fedora installation with `tcsh` installed.
```console
$ csh -c 'echo $SHELL'
/bin/bash
```

The `get-poetry.py` script does not support `csh` explicitly and assumes that a POSIX compliant shell being used (which `csh` is not). And without any clear way to detect it and the considering the use of it is quite sparse, I doubt it is worth the effort to make it support it. The `env` file is designed to work for all POSIX compliant shells (as this is what is supported by the installer on non-windows platforms). This means the use of `export` command is relied upon when generating the `env` file.

https://github.com/python-poetry/poetry/blob/fa87f7be55abd45520283ff7844feb3052f78e8e/get-poetry.py#L703-L708

That said, if you want to support `csh` environments by ensuring we use `setenv` instead of `export`, contributions are always welcome. The key will be to have a reliable mechanism to detect `csh`. 

Alternatively, you can also try installing using `pip` so that `poetry` gets put into either the system (as root) or user site (`--user`).

**Comment by dimbleby** [comment]
this relates to the get-poetry script which is now retired - therefore it can be closed.

(current installation tells the user how they can update their path if they want to, but does not try to do it for them)
