### ISSUE TITLE
The dumbest most useless tool , I have ever seen

### ISSUE THREAD

**Issue by Mohamed209** [python-poetry/poetry#2784]
Open Source dev , is not about wrapping few lines from existing tools and say hi i have a new tool
this tool is literally wrapper around pip package and every single feature introduced can be done in pip much more easily , so what the problem did this silly tool solved ! , no problem , it just replaces commands for example `pip install` >> `poetry install` , `pip list >> `poetry show`
if there was unlike button in githup API , I would have pressed it 10000 times for this piece of shit

**Comment by dimitern** [comment]
After a lot of frustration with `poetry`, I'm switching back to uising `pipenv`, which might have its own issues, but at least is solid and works for most cases I had to deal with so far, but most importantly:
 - Uses familiar pip-compatible dependencies specifications for version, especially git, path, zip-based dependencies.
 -  Supports `.env` file loading
 - No need to learn yet another configuration format like TOML
 - Compatible with `pyenv` for pinning python version easily, rather than trying to always use the system one (at least it has a --python argument I can specify right away)

 Sorry for the rant, but it looks too opinionated.

I **do** like the interactive search / dependencies specification though (I had to Google search `black`'s version that works in a particular Python 3.x more often than not, otherwise it doesn't work usually).

**Comment by Rexogamer** [comment]
While I'm not a maintainer for Poetry I'm pretty @dimitern's feedback is a lot more constructive/helpful for them than a rant about how this "isn't what open source is". I mean technically open source is just any program whose code is available to the public for usage and editing.
