### ISSUE TITLE
Poetry 1.1.0b1 missing dependencies

### ISSUE THREAD

**Issue by brendongo** [python-poetry/poetry#2876]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14
- **Poetry version**: 1.1.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
https://gist.github.com/brendongo/bc30924ffa50892c65a2b895af1901f4

## Issue

Hi, I was trying out the beta release and thought you might find this bug interesting.

When switching from 1.0.10 to 1.1.0b1 poetry misses two sub-dependencies. To reproduce: run poetry install with 1.0.10 and note that jsonschema is in the poetry.lock file. When using 1.1.0b1 jsonschema is no longer in the lockfile.

**Comment by abn** [comment]
This was resolved with https://github.com/python-poetry/poetry-core/pull/55 will be fixed in mainline poetry with the next `poetry-core` release. In the meanwhile if you wish to use the fix you can do so by updating `poetry-core` manually.

If you have installed poetry using `pipx` you can do something like this. Obviously this assumes this is a fresh install of poetry.
```sh
pipx install --pip-args='--pre' poetry
pipx inject --pip-args='--force' poetry 'poetry-core @ git+https://github.com/python-poetry/poetry-core.git'
```
