### ISSUE TITLE
poetry run foo.py should work when foo.py is an existing file

### ISSUE THREAD

**Issue by dmerejkowsky** [python-poetry/poetry#2893]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently, if you want to run a Python script (say  `foo.py`) at the top of your project, you have to type:

```
$ poetry run python foo.py
```

It would be nice to be able to just run:

```
$ poetry run foo.py
```

**Comment by dmerejkowsky** [comment]
Note: a solution would be to make `foo.py` executable and add a shebang like  `#!/bin/env python` at the top, but this may not work everywhere (for instance on Windows)

**Comment by abn** [comment]
Honestly, I do not see the value here.  This will simply ease a very minor use case, but introduces maintanence complexities and ambiguity. It is important to note that run's purpose is to run a command in your project's environment and nothing else. 

To me `poetry run python foo.py` is rather clear and even preferred.

Additionally you'd probably be better of adding this to your scripts instead.

```toml
[tools.poetry.scripts]
foo = foo:main

```

This will work if `foo.py` is in your project root, but is not an ideal solution since this will not work when your project is distributed. Ideally you'd want make sure `foo` is more like `project.namespace.foo`. 

Anyway, at this time I do not think this is something we would want to support.

**Comment by dmerejkowsky** [comment]
Fair enough. Thank you for the detailed answer :+1: 

Feel free to close, then
