### ISSUE TITLE
sorting packages

### ISSUE THREAD

**Issue by tkossak** [python-poetry/poetry#312]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
When I use 'poetry init' and get to the step for searching packages, it looks like huge mess: https://imgur.com/a/WA9CcnJ
Maybe we can get this list sorted alphabetically? Or/except maybe display packages that are most likely what I look for (because the name is exactly what i typed) on the bottom, so I don't have to scroll the list in search for its number.

**Comment by nchammas** [comment]
I found this to be a minor issue with `poetry init`, too. One easy improvement that could be made would be to always rank any exact match at the top.

Further improvements are certainly possible (perhaps Poetry could somehow leverage the search result rankings returned by https://pypi.org/), but just placing exact matches at the top would be a nice improvement by itself.

**Comment by tkossak** [comment]
Not at the top - at the bottom (like https://github.com/Jguer/yay is doing) so we don't have to scroll for best matches but see them instantly where the cursor is (on the bottom that is).

**Comment by sdispater** [comment]
I agree that it is a usability issue. The idea of putting the more relevant packages at the bottom seems a good improvement to start with.

**Comment by rafalkrupinski** [comment]
I'd sort dependencies alphabetically even in pyproject.toml, I find that  helps with merging branches if they both have new entries added

**Comment by n8sty** [comment]
I took a crack at trying to fix this to learn a bit more about Poetry's guts and contribute to a tool that's made my work a bit easier. I think I may have discovered another issue that relates to specifying packages interactively, and is potentially solved by sorting.

When I go through a `poetry init` flow in an empty directory and specify either `Django` or `django` I can't actually get either one picked up by https://github.com/sdispater/poetry/blob/f4803e91bca440e6f4af6ad54e396d01c024a76f/poetry/console/commands/init.py#L189-L193. I believe this happens because the `choice` method of `cleo.Command` only allows what's returned in the array of choices to be selected from. And, the array of responses when using either of those search terms doesn't include `[dD]jango`. Digging more, I tried using `xmlrpc.client.ServerProxy` to query PyPi by `xmlrpc.client.ServerProxy("https://pypi.python.org/pypi").search({'name': 'django'}, "or")[0]` which returned (what I'm looking for)

```
{'name': 'Django',
 'summary': 'A high-level Python Web framework that encourages rapid development and clean, pragmatic design.',
 'version': '2.2.4',
 '_pypi_ordering': False}
```

So, I think @nchammas 's suggestion above about using the search result ordering from PyPi potentially solves this problem. For reference, I'm using the latest version of master https://github.com/sdispater/poetry/tree/f4803e91bca440e6f4af6ad54e396d01c024a76f. I'm happy to try and throw a fix together assuming it's not already in the works.

**Comment by Vozf** [comment]
I also believe that alphabetical storage is the best choice as it is done by npm
For example when I do 
```
poetry remove some-package
poetry add some-package
```
It deletes the entry of some package from pyproject.toml and adds it in the end. I would expect the pyproject to stay the same

**Comment by VikashKothary** [comment]
Until this gets implemented, I've been using the `toml-sort` package:

```
poetry add -D toml-sort
poetry run toml-sort pyproject.toml --all --in-place
```

The downside is that it sorts the entire file and not just the dependencies, but that was an acceptable trade-off for me. You should also be careful because it seems to remove comments if they're on a new line by themselves.

**Comment by andrei-shabanski** [comment]
Since Poetry 1.2 introduces the plugin system, this kind of job can be delegated to plugins. That's what I did

(poetry-plugin-sort)[https://pypi.org/project/poetry-plugin-sort/] sorts dependencies every time after running `add`, `remove`, or `init` commands. To install the plugin run:

```bash
poetry self add poetry-plugin-sort
```

Note that it's a beta. Please, let me know how it works if someone will try it

**Comment by VikashKothary** [comment]
You didn't like your repository so I did it for you: https://github.com/andrei-shabanski/poetry-plugin-sort.

I look forward to checking it out.

**Comment by rafalkrupinski** [comment]
@tkossak Does Andrei's plug-in solves the problem? Can the issue be closed?

**Comment by tkossak** [comment]
I don't know because i stopped using interactive package searching;/additions in poetry. Nowadays I just `poetry add PKG` and that's it.

**Comment by dimbleby** [comment]
poetry has shown only 10 results for some years now - https://github.com/python-poetry/poetry/commit/2e579c7486578f37ddda07636793dff077bf32f4 - this should probably be closed

**Comment by jason-curtis** [comment]
I would still find it helpful for packages to be sorted in `pyproject.toml`, which is the issue that most folks are commenting on here. Could we reopen this specifically for that issue, or would it be better to file a new one?

FWIW, to deal with existing (un-sorted) pyproject.toml files or comments that caused #3996 to get hung up, I would probably just have poetry insert lines into a sorted list at the top of `[tool.poetry.*.dependencies]` and leave any manually curated deps (or deps with comments) at the bottom.
