### ISSUE TITLE
Poetry does not respect local .gitconfig

### ISSUE THREAD

**Issue by pikeas** [python-poetry/poetry#3271]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.6
- **Poetry version**: 1.1.3

```
# pyproject.toml
[tool.poetry.dependencies]
foo = { git = "https://github.com/org/foo.git", branch = "master" }
```

This dependency prompts for a Github username and password. However, I have the following `.gitconfig` file in the same directory:

```
# .gitconfig
[url "ssh://git@github.com/"]
insteadOf = https://github.com/

# ~/.config/git/config
[includeIf "gitdir:~/[this directory/"]
path = ~/[this directory]/.gitconfig
```

Everything works as expected if I place the `[url]` block in `~/.config/git/config` directly, so it appears to be an issue of poetry not respecting the includeIf.

**Comment by mikeroll** [comment]
Have you tried testing this with a plain `git clone`? Yields the same results for me, so it's an issue with git, not poetry.

**Comment by silverwind** [comment]
I think git config can only live in `~/.gitconfig`, `$XDG_CONFIG_HOME/git/config` or `.git/config`, not `.gitconfig`.

**Comment by toanant** [comment]
Agree with @silverwind comment as mentioned in `git config` doc - https://git-scm.com/docs/git-config#FILES

**Comment by mikeroll** [comment]
@silverwind @toanant please read the OP again - this is in essence a random file that just so happens to be named `.gitconfig` to confuse y'all :). It is indeed ignored by git, but it doesn't matter since we are explicitly including it from the main `~/.config/git/config`. And it gets included alright, which can be verified via `git config --list --origin`. The only question left is why the `url` directive is ignored by `git clone` in such a configuration – but anyway, as I said, this question is unrelated to poetry.

**Comment by finswimmer** [comment]
Closing this as it seems not a problem related to poetry.
