### ISSUE TITLE
Re-running `poetry install` "updates" packages to already existing versions

### ISSUE THREAD

**Issue by marhoy** [python-poetry/poetry#3299]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Debian Buster
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with Dockerfile and poetry-files**: https://gist.github.com/marhoy/c3850f122f5f2f801c5c3ff916b7fd0e

## Issue
When NOT using a virtual environment (`POETRY_VIRTUALENVS_CREATE=false`) and running `poetry install` multiple times, already installed packages will be "updated" to the already installed versions. This does not happen with poetry-1.0.9 (change line 29 in provided Dockerfile to confirm).

Running `docker build .`with the provided files causes:

First run (line 33 in Dockerfile):
```
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 5 installs, 0 updates, 0 removals

  • Installing six (1.15.0)
  • Installing numpy (1.19.2)
  • Installing python-dateutil (2.8.1)
  • Installing pytz (2020.1)
  • Installing pandas (1.1.3)
```

Second run (line 42 in Dockerfile):
```
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating six (1.15.0 /home/user/.local/lib/python3.8/site-packages -> 1.15.0)
  • Updating numpy (1.19.2 /home/user/.local/lib/python3.8/site-packages -> 1.19.2)
  • Updating python-dateutil (2.8.1 /home/user/.local/lib/python3.8/site-packages -> 2.8.1)
  • Updating pytz (2020.1 /home/user/.local/lib/python3.8/site-packages -> 2020.1)
  • Updating pandas (1.1.3 /home/user/.local/lib/python3.8/site-packages -> 1.1.3)
```

PS: The reason for doing this is to make docker cache the project dependencies. So when I change my own code, only my own package will be installed, the project dependencies are cached.

**Comment by jacek-jablonski** [comment]
Same problem here. Seems that using `POETRY_VIRTUALENVS_CREATE=false` causes reinstallation of all packages to the current versions.

**Comment by dynamicmindset** [comment]
I can confirm this issue with Poetry 1.0.4. As a result caching does not work resulting in really long build pipelines
```
 Skipping virtualenv creation, as specified in config file.
 Installing dependencies from lock file
 Package operations: 0 installs, 210 updates, 0 removals
   - Updating six (1.15.0 -> 1.15.0)
   - Updating docutils (0.15.2 -> 0.15.2)
   - Updating jmespath (0.10.0 -> 0.10.0)
   - Updating python-dateutil (2.8.1 -> 2.8.1)
   - Updating urllib3 (1.25.11 -> 1.25.11)
   - Updating botocore (1.15.37 -> 1.15.37)
   - Updating pyasn1 (0.4.8 -> 0.4.8)
   - Updating attrs (20.2.0 -> 20.2.0)
   ...
```

I did not encounter this issue with Poetry 1.0.5

**Comment by mattmm1** [comment]
Any updates on this? Is this the way it should be behaving without `POETRY_VIRTUALENVS_CREATE`? Can confirm same behaviour as outlined above in poetry 1.1.12 and python 3.9.9.

**Comment by dimbleby** [comment]
switching in poetry 1.2.0b3, the given dockerfile now fails because the non-root user doesn't have permission to install to `/usr/local/lib/python3.8/site-packages`, which seems reasonable.

shuffling things around to use the root user, the second `poetry install` does nothing as desired.

(Generally it's a bad idea to install without creating a virtual environment: you usually want a virtual environment whether or not you made poetry responsible for creating it.  Might get away with installing at the system level as root in a docker container I suppose, if you're really sure you're not going to break anything else)

Anyway, this seems fixed.

**Comment by mnieber** [comment]
@dimbleby I'm sorry to be blunt, but isn't a virtual environment intended as a drop-in replacement for the system environment? Imagine if in general python tools would say "I must be used in a virtualenv" or "I must not be used in a virtualenv". I know I'm also being pedantic now (sorry for that as well), but as a software developer this really annoys me, also since Poetry is used as a foundation for python projects, not as some add-on.
