### ISSUE TITLE
poetry install: skip dev dependencies on env var

### ISSUE THREAD

**Issue by HoneyryderChuck** [python-poetry/poetry#3328]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi,

I've looked for something like this in the documentation, and didn't find it. I'd like to have the same feature as the `--no-dev` flag when running `poetry install`, declared as an envvar.

A very quick suggestion of how this could be implemented is by [checking how pipenv does it with PIP_INSTALL_OPTION envvar](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#configuration-with-environment-variables), where command line options are passed in an env var.

The use case for this is for docker, where I'd like to tell the build step **not** to install dev dependencies when building the production image. An envvar is a trivial thing to implement in a CI setup, compared to bash my way inside the dockerfile.

**Comment by sinoroc** [comment]
I would like to refer you to #2458 and [this comment](https://github.com/python-poetry/poetry/issues/2458#issuecomment-713043646) in particular. This looks like a valid feature request, but it most likely won't happen until after the code handling configurations (`poetry.toml`, `poetry config`, environment variables, CLI flags, etc.) is rewritten.

**Comment by neersighted** [comment]
I'm closing this as unplanned for now -- it's tangentially related to #1132, but not the same thing. There is an intention to generally support more ergonomic defaults for different scenarios.

However, this is pretty unique -- CI is better when it's explicit instead of implicit, and I would generally assert that you're better off modifying your invocation of Poetry directly, versus complicating your environment to do things indirectly.

Without a concrete example of how this is in-scope and desirable to many users, I'm going to close this as unplanned for now.
