### ISSUE TITLE
enable `--ansi` by default on Windows

### ISSUE THREAD

**Issue by ericfrederich** [python-poetry/poetry#3354]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

The `--ansi` option should be default on Windows.

On a fresh install of Windows 10 with a fresh install of the Windows version of Python 3.9.0
Install Poetry via:

```bash
py -m pip install --user pipx
py -m pipx ensurepath
# need to get a new console now for pipx to be on PATH
pipx install poetry
```

Now in both PowerShell and in cmd.exe running `pipx --ansi` produces nice colors.

Is there a reason not to default `--ansi` on Windows?

**Comment by TBBle** [comment]
This is actually decided by an underlying library ([clikit](https://github.com/sdispater/clikit)), and is probably due to a bug there: https://github.com/sdispater/clikit/issues/35.

> As a workaround, you can set the ANSICON env-var to something non-empty to force ANSI support.

**Comment by passionsfrucht** [comment]
I hope I'm not totally wrong in this thread, but I have actually seen different behaviours between `ANSICON` and `--ansi`, as seen here: 
![image](https://user-images.githubusercontent.com/9266591/107042342-edbf0500-67c1-11eb-9362-74ddb7ae9c96.png)

Hunting down the problem made me a bit crazy as it seems to be an endless loop about `conemu`, `windows`, `python`, `git-bash` for windows, `termcap` and numerous other potential culprits.

To break the loop I just made the comment here to show the interesting different behaviour between `ANSICON` and `--ansi`.

My environment surely is interesting as it is but in a strange circle of modern Windows environment, too:
* Windows Terminal Preview 
  Version: 1.6.10272.0
* `WSL2` with `fish` as log-in shell
* tmux
* new fish shell in tmux
* in there git-bash for windows is started

```bash
$ poetry --version
Poetry version 1.1.4
lord@Bratwurst ~/configs/python windows *6 !1 ?1
$ which poetry
/c/Users/lord/.poetry/bin/poetry
lord@Bratwurst ~/configs/python windows *6 !1 ?1
$ env | rg TERM
TERM=screen-256color
WSLENV=WT_SESSION::WT_PROFILE_ID:TERM/w
```

But I can reproduce such behaviour in simpler set-ups, too.

If there is any more info I can provide or a pointer in the right direction I'd be glad to provide or take it.
Actually it is not only poetry showing such or similar errors, but so far only poetry did this difference between the environment setting and command line option. But `ANSICON` was new to me in any way.

So thanks for this new bit of knowledge and for the really great piece of software!

**Comment by TBBle** [comment]
I can't reproduce your result under PowerShell 7.1.1, under the same Windows Terminal Version:
![image](https://user-images.githubusercontent.com/138397/107106284-e9a4ed00-687e-11eb-8d94-a740e9f33183.png)

I also couldn't reproduce it under git-bash `git version 2.28.0.windows.1`:
![image](https://user-images.githubusercontent.com/138397/107106342-34266980-687f-11eb-8c56-c059d7158f7d.png)

[`--ansi`](https://github.com/sdispater/cleo/blob/a77238428517842babfc5aa8b74ba9d50d8e9c84/cleo/application.py#L477-L478) and [`ANSICON=1`](https://github.com/sdispater/cleo/blob/a77238428517842babfc5aa8b74ba9d50d8e9c84/cleo/io/outputs/stream_output.py#L92-L99) should have the same effect, [marking the output streams as decorated](https://github.com/sdispater/cleo/blob/a77238428517842babfc5aa8b74ba9d50d8e9c84/cleo/io/outputs/stream_output.py#L33-L34).

That said, I'm not totally clear from your comment... Are you testing this inside WSL? I assume so based having `WSLENV` set. That isn't Windows as far as Python is concerned, so `ANSICON` won't have any effect.

I'd suggest trying to get a simpler reproduction case, in terms of the applications involved in handling the output stream. Due to the recency of real PTY support in Windows, older Windows apps would often mangle ANSI codes as they passed through, and git-bash being Cygwin based has definitely been one of those in the past.

**Comment by passionsfrucht** [comment]
Hi again, I did some further tests, now with a bit of simplified setup.

As I said my setup is weird due to other codebases I'm usually working on. My typical shell setup is in WSL, but for different reasons I need to drop into msys bash from time to time.

That said I tried to simplify the test setup, with similar results in git-bash, but not in `powershell`.

powershell:
![image](https://user-images.githubusercontent.com/9266591/107145449-c7c06e80-6941-11eb-9d41-c3cc29c13526.png)

bash (msys):
![image](https://user-images.githubusercontent.com/9266591/107145471-f50d1c80-6941-11eb-9b0c-81bd3f694b85.png)


This time git-bash was started directly from Windows Terminal, via:
```jsonc
            {
                "guid": "{f8346d0a-b08a-48db-a12a-abb322e5b278}",
                "commandline": "\"C:\\Program Files\\Git\\bin\\bash.exe\" -i -l",
                "historySize": 9001,
                "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
                "name": "Git-Bash",
                "snapOnInput": true,
                "startingDirectory": "%USERPROFILE%"
                //"background": "#332222"
            },
```

Same result when git-bash is started from the start menu, in the 'classic' terminal, with whatever settings they use there exactly:
![image](https://user-images.githubusercontent.com/9266591/107145615-25a18600-6943-11eb-95d4-25a7209d7891.png)

**Comment by TBBle** [comment]
I had a quick check, and on a different machine (with git `git version 2.29.2.windows.2` and Windows Terminal `1.5.10271.0`) it _does_ reproduce.

![image](https://user-images.githubusercontent.com/138397/107172309-26a4e700-6a19-11eb-811c-e1f91086936a.png)

~~So I suspect this is a bug in git-bash (or rather, its Cygwin-based MSYS2 layer) introduced with [2.29](https://github.com/git-for-windows/git/releases/tag/v2.29.0.windows.1). I would guess related to the Cygwin 3.1.7 upgrade mentioned there, since it seems something is corrupting [U+001b](https://util.unicode.org/UnicodeJsps/character.jsp?a=1b&B1=Show) into [U+2190](https://util.unicode.org/UnicodeJsps/character.jsp?a=2190). It's weird that it only affects `ANSICON` but not `--ansi`, so I'm wondering if perhaps Cygwin is _also_ changing behaviour based on the `ANSICON` env-var? I can't see `ANSICON` in [the source](https://github.com/msys2/msys2-runtime) though.~~

A quick test by piping to `less` shows that `less` sees the `<ESC>` correctly in both `--ansi` and `ANSICON=1` cases, so unless [clikit](https://github.com/sdispater/clikit) is doing something _very_ weird in checking for tty output, it must be something in Cygwin. Piping through `cat` didn't have the same effect though, so it might be something specific that `less` is doing.

Confounding the above, my MSYS2 installation with runtime `msys2-runtime 3.1.5-3` (i.e. the same Cygwin base as git for windows 2.28) _also_ reproduces this issue on this machine.

I'll have to check on my other machine, but now I'm wondering if there's something else system-wide which is changing the results. It's not Windows Terminal, since my home machine is running the same version you used.

And one last test, it's not `ANSICON` specifically, as I can use [`ConEmuANSI=ON` or `Term=xterm`](https://github.com/sdispater/clikit/blob/ead8dd5375d5c16fd9c9730a012a53d580201f62/src/clikit/io/output_stream/stream_output_stream.py#L46) and see the same bug. Other random env-vars don't have this effect.

The only thing that comes to mind, is that by passing in these env-vars, [the code that tries to activate VT processing](https://github.com/sdispater/clikit/blob/ead8dd5375d5c16fd9c9730a012a53d580201f62/src/clikit/io/output_stream/stream_output_stream.py#L64-L99) is bypassed. I haven't checked, but perhaps when using `--ansi`, that code is called, but the result is ignored.

And I therefore guess that for Cygwin-based console apps (as opposed to Powershell or CMD), VT processing is not enabled by default? Although that would imply that _detection_ _should_ work, since the underlying bug that blocks that is that [if VT processing is already enabled, clickit returns "ANSI not supported"](https://github.com/sdispater/clikit/issues/35). I'm not sure what piping through `less` is changing.

This wouldn't technically be a bug, because we're setting env-vars that claim things that aren't actually true (i.e. that we're running under [ansicon](https://github.com/adoxa/ansicon/blob/37f92009f6ca4938a34a1d7cecff41d331c7423c/ANSI.c#L3863-L3884), [ConEmu](https://conemu.github.io/en/ConEmuEnvironment.html) or xterm.

I'd have to do some more debugging to track this down, but I think getting https://github.com/sdispater/clikit/issues/35 fixed first would be better, since it's possible that that will function correctly under Cygwin anyway, removing the need for the `ANSICON` workaround.

**Comment by passionsfrucht** [comment]
I just want to say thanks for the effort, I did not have the time to look further into the issue right now, but FYI:

```bash
$ git --version
git version 2.30.1.windows.1
```

Did not bring any relief.

**Comment by johnjohnk2** [comment]
Hi @passionsfrucht @ericfrederich @TBBle. Thanks a lot for your work. I have this issue so far ->no colors at all in Arch, some colors in powershell, both started from windows terminal. Not sure about the best solution to implement at this stage ...
Thanks a lot for your help

**Comment by TBBle** [comment]
@johnjohnk2 I don't see Poetry in your screenshots. Are you on the correct bug-tracker? I sounds like you are looking for [Windows Terminal  support](https://github.com/microsoft/terminal/blob/main/SUPPORT.md)?

**Comment by johnjohnk2** [comment]
@TBBle Hi Thanks a lot for your time.  Not sure to understant as yes it is WSL2 but I came here from your 4 Jan commet where you said that the bug comes from clikit, isn' it ?

**Comment by TBBle** [comment]
The issue _in Poetry_, yes, appears to actually be a bug in clickit, a Python library used by Poetry.

You appear to just be having trouble with bash (under WSL2?) and PowerShell under Windows Terminal, so no connection to Poetry or clikit. You should follow up according to the [Windows Terminal support](https://github.com/microsoft/terminal/blob/main/SUPPORT.md) instructions, as this is the wrong place to ask.

**Comment by johnjohnk2** [comment]
Ok OK sorry for my misunderstanding !

**Comment by Jhraumg** [comment]
I could reproduce it from my Windows Terminal + git bash and poetry 1.1.6 (while it worked flawlessly with the same git bash and cmder)

With poetry version 1.2.0a1, it seems all fixed (thanks to  #3618 I guess): 
* poetry displays color automaticaly on Windows Terminal
* poetry does accept global parameter *before* command (which could help aliasing `poetry` to `poetry --ansi`, but it is non necessary anyway 😉 )

**Comment by KuSi833** [comment]
I've installed Poetry version 1.2.0a1, but the color still doesn't display by default in the Windows Terminal

![image](https://user-images.githubusercontent.com/46829331/125075461-f09a8a80-e0be-11eb-99ef-da598aed26db.png)

**Comment by passionsfrucht** [comment]
Hey again, unfortunately

![image](https://user-images.githubusercontent.com/9266591/129360773-7553ca55-97c2-4288-b199-d78f87a742e4.png)

Did not bring the fix for me either.

But by being able to alias `poetry` to `poetry --ansi` I was able to mitigate this for me in a manner that I can move on.

If I can help to debug some deeper causes, I'd be happy to help!

**Comment by TBBle** [comment]
I also see Poetry 1.2.0a2 failing to auto-detect ANSI support:
* Windows Terminal Preview 1.10.1933.0
* PowerShell 7.1.3
* Python 3.9.6
* pipx 0.16.4

![image](https://user-images.githubusercontent.com/138397/129397153-5a22f2fb-687e-4890-b4ed-a1d36ead8c27.png)

![image](https://user-images.githubusercontent.com/138397/129397189-a840034b-eb3f-4286-84a6-f8ee636e8417.png)

The `ANSICON` env-var workaround still successfully enables ANSI.

![image](https://user-images.githubusercontent.com/138397/129397279-0bbc680a-09f8-43a5-ae11-160c442481c0.png)

(Ignore the warning about Poetry already existing, that's noticing my Poetry 1.1.7 installation)

I also checked `pipx run --spec poetry==1.2.0a1 poetry` just in case it was working in a1 but broken in a2, but the result was the same.
