### ISSUE TITLE
Does Poetry support recursive extras?

### ISSUE THREAD

**Issue by alexifm** [python-poetry/poetry#3369]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Does Poetry support recursive (for lack of a better term, it's early) extras best exemplified by this `pyproject.toml` snippet?

```
[tool.poetry.dependencies]
attrs = "~19.3"
pandas = "~1.1"
# optional
quandl = { version = "~3.5.2", optional = true }
matplotlib = { version = "~3.3.0", optional = true }
networkx = { version = "~2.4.0", optional = true }
scikit-learn = { version = "~0.22.0", optional = true }

[tool.poetry.extras]
quandl = ["quandl"]
viz = ["matplotlib", "networkx"]
ml = ["viz", "scikit-learn"]
all = ["ml", "quandl"]
```

**Comment by sinoroc** [comment]
I don't think so. Did you try it? What was the result?

**Comment by alexifm** [comment]
Did not work.  Can you suggest a location in the codebase to look for where I could potentially add this contribution if it's considered desirable?

**Comment by alexifm** [comment]
Seems like it could be here?
https://github.com/python-poetry/poetry/blob/8b8b97a652178788bf5751ad8a372ceb161965be/poetry/utils/extras.py#L10

**Comment by n8sty** [comment]
This might be too pedantic of a concern but you should make sure to guard against situations where an extra and a package could have the same name. In your example file, whatever algorithm you implement would need to know that the `quandl` referenced in the `all` section is different than the "quandl" referenced in the `quandl` extras line.

I'm not sure the increased ease of nesting optional dependencies is worth the potential brittleness of solving for the above.

**Comment by alexifm** [comment]
@n8sty Yes, that is something I avoid but unfortunately didn't pay close attention to in that example.  

As for an implementation, I think the simplest thing would be to just fail and have the error suggest picking a different name that doesn't create a conflict.

Another thing is that it seems like `poetry-core` is where package building is handled and it's much less clear to me how it resolves the packages in an extras definition than this function I identified earlier.

**Comment by sinoroc** [comment]
Personally I am not convinced there is a need for such a feature with such a notation. Seems to be adding more confusion. You may want to give the UX a second look

See if it would make sense in the context of the [_dependencies groups_ feature](https://github.com/python-poetry/poetry/issues/1644) (planned for [_v1.2_](https://github.com/python-poetry/poetry/projects/6)).

---

If I were to change _extras_ in order to avoid repetition for dependencies that are in multiple extras (in a way this is what you are trying to solve, right?), this is what I would aim for, but I think the _dependencies groups_ feature already covers this (I have not read the full discussion on this, so I might be wrong):

```
libraryA = { "*", in_extras = [ "alpha", "bravo" ] }
ilbraryB = { "*", in_extras = [ "alpha" ] }
```

**Comment by finswimmer** [comment]
Is this something that is defined in any PEP? If so, `poetry` should support it. If not, then probably the corresponding wheel/sdist will not be interpreted correct by other tools and `poetry` should not support it as well.

**Comment by sinoroc** [comment]
@finswimmer I think they want enhancements to the notation in `pyproject.toml`, that would avoid some repetition of dependencies in that file. And _poetry_ should take care to expand the notation to make it standard-conform in the distribution's metadata.

**Comment by sinoroc** [comment]
For comparison, this is how it can be done with _setuptools_ `setup.cfg`: https://stackoverflow.com/a/61610341/

**Comment by alexifm** [comment]
@sinoroc I'm okay with dropping this in favor of the groups approach mentioned for the upcoming release.  Not worth it to support two approaches, even if it's not that far off what setuptools allows.

**Comment by smheidrich** [comment]
Probably worth pointing out that since the last comment here, recent versions of setuptools+Pip have started [supporting recursive extras specified without any hacks](https://hynek.me/articles/python-recursive-optional-dependencies/) (i.e. not like in that StackOverflow answer), by simply having dependencies on the current package itself with `[extra1,extra2,...]` appended.

As far as I can tell that wouldn't work with how extras and dependencies are currently specified in Poetry, as dependencies can only be listed once and so there is no way to have e.g. extra A depend on `currentpackage[X, Y]` and extra B depend on `currentpackage[Z]`. So that's a shame.

And by the way, I don't see how groups solve this issue at all - they are only meant for development of the package itself, aren't they? Whereas extras are user-facing. Reopen?
