### ISSUE TITLE
Immitate `pip install --no-deps` / Add `--only-root`

### ISSUE THREAD

**Issue by Natureshadow** [python-poetry/poetry#3377]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be great if Poetry could support installing only the root of the project, but leave all dependencies untouched, much like the `--no-deps` option to pip does.

The use case is a development environment where the code being worked on is spread across several packages, and I want to keep several of them editable in the same poetry environment without having to temporarily change/remove a dependency from `pyproject.toml`.

Poetry ould optionally still check whether the installed packages fulfill the dependencies or not, but with such an option that developers will explicitly use, this is not necessary I suppose.

**Comment by sinoroc** [comment]
To make sure I understand, you have tried the following and it does not fit your workflow, right?

```
[tool.poetry.dependencies]
# ...
library = "^0.1.0"

[tool.poetry.dev-dependencies]
library = {path = "../library", develop = true}
```

**Comment by Natureshadow** [comment]
Well, this is a nice hack, but it would require one of manipulating pyproject.toml every time I start developing on such a situation, or forcing relative paths on every developer in the project (given that the library is, or might be, in a different Git repository/whatever).

**Comment by wom** [comment]
I'd like to add a +1 here; sometimes upstream packages are too conservative when pinning dependencies. I'd rather avoid having to add a `pip install --no-dep <package==...` after my initial  `poetry install`.

**Comment by cglacet** [comment]
Does anyone found a way to prevent install sub-dependencies? It would also be interesting when trying to generate documentation for another package (where you only want to be able to read the package's code).

**Comment by 1oglop1** [comment]
I have a use case for this as well. 
I'm developing IaC with Pulumi [python] and at the moment `pulumi_aws` package is auto-generated from the terraform package.

Then when it comes to describing complex resources eg. `pulumi_aws.cloudfront.Distribution` which require a lot of nested objects however many of them are also just plain strings that allow only specific values to be set eg: [viewer_protocol_policy](https://www.pulumi.com/docs/reference/pkg/aws/cloudfront/distribution/#viewer_protocol_policy_python) which allowed values are:  `allow-all`, `https-only`, or `redirect-to-https` [API Reference](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CacheBehavior.html).

Objects like this can be simply represented as `Enum`s. And convenient way to get access to these enums is to install a CDK package `aws-cdk.aws-cloudfront` and then import it like a so:
```
import aws_cdk.aws_cloudfront as cf

cf.ViewerProtocolPolicy.ALLOW_ALL
```
But the package itself has a lot of extra dependencies I do not need and want so I installed it with `--no-deps` to get access only to enums: `pip install aws-cdk.aws-cloudfront --no-deps`

It would be nice if `poetry` could support this in `pyproject.toml` because `requirements.txt` cannot.

**Comment by cmin764** [comment]
I'm interested into this!

Use case: installing locally for development a package that requires a main dependency which **isn't available anymore** given the upgraded Python interpreter version for this local case only. Therefore I'm manually installing another version of the dependency, one that is available but can't continue on `poetry install` the project itself because that specific pinned down version isn't satisfied. (and I don't want to edit _pyproject.toml_ or the lock file neither)

**Comment by iamhatesz** [comment]
@Badg 100% agree with this use case. I noticed the same issue in my setup.

**Comment by caniko** [comment]
+1

**Comment by abn** [comment]
Poetry on master should make this possible, albeit, via misfeature.

```sh
poetry install --only=non-existent-group
```

**Comment by MikiGrit** [comment]
I'm also interested in this functionality.

Our usecase... [pytorch-toolbelt](https://github.com/BloodAxe/pytorch-toolbelt) depends on any opencv package and have specified `opencv-python` as a dependency. This is unfortunately problem for us since the opencv-python package have also dependency on OpenGL library which is difficult to install in our Gitlab CI. On the other hand it would be perfectly fine to install non-opengl variant (`opencv-python-headless`) ourselves but we also need a way how to tell poetry that we don't want to install dependencies for `pytorch-toolbelt`.

**Comment by cristianmtr** [comment]
Is this possible now? Couldn't figure it out from perusing the docs. We hit the problem:

- we have project A
- project A has a dependency on project B
- proj B has strict dependencies (versions) on projects C, D, etc.
- in proj A we don't want to install the specific versions of projects C, D, etc. that proj. B requires, but use other versions

Currently we solve this by having a two-step process:

```
pip install -e .[dev,whatever,etc.]
pip install --no-deps projB
```

It would be nice to find a packaging system that can add the `--no-deps` functionality in the requirements file itself (setup.py, project.toml, etc.)

**Comment by sinoroc** [comment]
@cristianmtr There is now `poetry install --only-root`:

* https://python-poetry.org/docs/cli/#options-2
* https://github.com/python-poetry/poetry/pull/5783

**Comment by cristianmtr** [comment]
> @cristianmtr There is now `poetry install --only-root`:
> 
>     * https://python-poetry.org/docs/cli/#options-2
> 
>     * [Add `--only-root` option to install command, excluding all dependencies. #5783](https://github.com/python-poetry/poetry/pull/5783)

But this is only for the installation of the main project (project A) itself, not for the installation of dependencies (project B).

How can I add a dependency in my `pyproject.toml` and specify that I want to do `--only-root` for that dependency (project B in my above example).

**Comment by charlienewey-odin** [comment]
As @Maciej-Zwolinski has said, this poses difficulties for when certain libraries have unusual package suffixes.

For example, the official NVIDIA PyTorch image (`nvcr.io/nvidia/pytorch:23.12-py3`) comes preconfigured with at least 3 packages that cause errors:

```
numba = "0.57.1+1.g4157f3379"
torch = "2.2.0a0+81ea7a4"
torchvision = "0.17.0a0"
```

This makes poetry a bit frustrating to use in some edge cases.

**Comment by Natureshadow** [comment]
It seems for such cases, an override mechanism for recursive dependencies would be more appropriate.

**Comment by sinoroc** [comment]
> But this is only for the installation of the main project (project A) itself, not for the installation of dependencies (project B).

If it is for dependencies, then yes it needs a different GitHub issue, yes.


> It seems for such cases, an override mechanism for recursive dependencies would be more appropriate.

I started a discussion on this here (not limited to Poetry): https://discuss.python.org/t/proposal-overrides-for-installers/23666
