### ISSUE TITLE
How to pass --no-use-pep517 to a particular dependency

### ISSUE THREAD

**Issue by mgresko** [python-poetry/poetry#3433]
Is there a way to specify pip install flags for a particular package?  Specifically --no-use-pep517

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by sinoroc** [comment]
As far as I know, you can't.

---

Why? What is failing? Is that a public project?

**Comment by mgresko** [comment]
https://github.com/snowflakedb/snowflake-connector-python/issues/382

This is the issue.  Building pyarrow on alpine fails.

**Comment by sinoroc** [comment]
Pyarrow seems to have a correct `pyproject.toml`, so I am not sure deactivating the build isolation would make a change. Would it?

**Comment by mgresko** [comment]
Disabling the build isolation does fix the issue if I try `pip install --no-use-pep517 snowflake-connector-python`

**Comment by kriansa** [comment]
Are there plans to add support to that? What's the official poetry's take on this issue?

**Comment by nikneroz** [comment]
@mgresko @kriansa 
```
poetry add snowflake-connector-python
poetry run python -m pip install snowflake-connector-python --no-use-pep517
poetry install
```

**Comment by lars20070** [comment]
On Apple M1 silicon, flags are required for the installation of `numpy`. Support for flags in `pyproject.toml` would be helpful indeed.
```
poetry run python -m pip install --no-use-pep517 --no-binary :all: numpy
```
Or is there an alternative to specify `numpy` in `poetry` projects on Apple M1 silicon?

**Comment by gianfa** [comment]
I don't know if it is too late, but if the problem is only with PEP517 this may help

You have to disable the experimental.new-installer configuration of poetry.
If you want to do this locally, you can make use of [poetry.toml](https://python-poetry.org/docs/configuration/#local-configuration), not to be confused with pyproject.toml.   
Just open a terminal in the project folder you are interested in (the one with "old" dependencies that won't install), run
`poetry config experimental.new-installer false --local` and it will generate the file.

other info: https://python-poetry.org/blog/announcing-poetry-1.2.0/#usefulness-of-experimentalnew-installer-false

**Comment by neersighted** [comment]
This is not something we aim to solve in Poetry; building packages in the destination environment is problematic (as said packages may install different packages/versions from what Poetry is setting up, and installing random packages/changing the setuptools version during a parallel install is fraught and has caused a massive support burden in the past).

Poetry is going to insist on requiring that packages build in an isolated environment -- all that is necessary is properly declaring their build-time dependencies. This has been best practice since before PEP 517 (as the `setup_requires` argument to `setup()`), and is made simpler with the declarative `build-system.requires` in `pyproject.toml`.
