### ISSUE TITLE
Resume interrupted downloads

### ISSUE THREAD

**Issue by CTimmerman** [python-poetry/poetry#3453]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be nice to resume a download instead of restarting it.

**Comment by P0oOOOo0YA** [comment]
I don't know if this feature is implemented or not but it is vital and to be more concrete this feature is fundamental to a package manager simply since not everybody is sitting behind a GB speed internet connection.  I think to deal with this crappy connection issue the best strategy is to delegate the downloading phase to an external tool (noting better than aria2 exists) and then pick the downloaded package from a cache folder ( poetry config set cache-folder)

**Comment by neersighted** [comment]
The immediate ask is not compatible with the direction we are going as per https://github.com/python-poetry/poetry/commit/cc3f99425206aa2507af6779b1943cfa751206cc. #2184 and #3322 are more indirect solutions to similar problems, but more likely to be implemented/compatible with Poetry's design.

**Comment by SichangHe** [comment]
For future people, this may help: https://gist.github.com/tobiasraabe/58adee67de619ce621464c1a6511d7d9
