### ISSUE TITLE
Poetry parsed a wrong version constraint from the specified one

### ISSUE THREAD

**Issue by hyliu1989** [python-poetry/poetry#3471]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Just two simple pyprojects, one in the top level and one in the only path dependency of the top level project. 
```
+ poetry_test/
    + pyproject.toml (1)
    + sub_project/
        +pyproject.toml (2)
```

In pyproject.toml (1), I have 
```
[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sub_project = {path = "./sub_project"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

In pyproject.toml (2), I have
```
[tool.poetry]
name = "sub_project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.7, <3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

And I got this error:
```
Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.7,<4.0) is not compatible with some of the required packages Python requirement:
    - sub-project requires Python >=3.7, <3.9, so it will not be satisfied for Python >=3.9,<4.0

  Because poetry-test depends on sub-project (0.1.0 C:/Users/Imaging/Desktop/poetry_test/sub_project) which requires Python >=3.7, <3.9, version solving failed.

  at ~\.poetry\lib\poetry\puzzle\solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For sub-project, a possible solution would be to set the `python` property to ">=3.7,<3.9"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

It seems like **Poetry wrongly takes ^3.7 as ^3.9 in the top level project**.

**Comment by sinoroc** [comment]
The python requirements for the top level project are wrong. There is no way it can be compatible with 3.9 if one of its dependencies is not compatible with 3.9. Or how do you see that playing out?

**Comment by hyliu1989** [comment]
Yeah that is the change I made. But maybe I am missing something, wouldn't package compatibility manager try to find the intersection of all constraints and install appropriately? In this case, the Python >=3.7, < 3.9 should be automatically selected, even with the top level module specifying a broader constraint?

**Comment by sinoroc** [comment]
As far as I can tell, _poetry_ decides which Python interpreter only based on the python constraints on the top level project and the python interpreter available on the host system. Poetry does not try to check the python restrictions on the dependencies (direct or indirect). 

I guess, theoretically it would be possible for _poetry_ to 

* pick version 3.9 as a start point (valid for the top level project and available on the system)
* do the dependency resolution
  * if all goes well, it's done
  * if a dependency requires a different python version
    * pick a different python and restart the dependency resolution with that interpreter

But that would be quite complicated for not much gain, I think. There are not that many python versions available so that job can be left to a human.

**Comment by finswimmer** [comment]
> But maybe I am missing something, shouldn't the package compatibility manager try to find the intersection of all constraints and install appropriately? In this case, the Python >=3.7, < 3.9 should be automatically selected, even with the top level module specifying a broader constraint?

That's the big advantage of `poetry` not to just looking for the intersection that would be valid for the current python interpreter in use. It's telling you, that you've define an invalid package definition. It might work on your PC because you are running a python version, that satisfy the version constraint. But now let another user try to install the package on their pc where python 3.9 is running. They are looking at the top level definition, seeing it should work and than are surprised that the installation will fail. This is what poetry prevents already during development.

fin swimmer
