### ISSUE TITLE
If poetry support install all dependencies in certain path?

### ISSUE THREAD

**Issue by innerNULL** [python-poetry/poetry#3489]
Thanks for help

If poetry can manage dependencied as the effect of ```python -m pip install -r requirements.txt --target myapp```

**Comment by sinoroc** [comment]
Dependencies need to be added to `pyproject.toml` in order to be taken into account. This can be done either by calling `poetry add ...` or by editing the `pyproject.toml` file directly.

The next best thing is probably to use [dephell](https://dephell.readthedocs.io/cmd-deps-convert.html). Maybe something like (untested, tweaking needed):

```
dephell deps convert --from=requirements.txt  --to=pyproject.toml
```
or
```
dephell deps add --from=requirements.txt  --to=pyproject.toml
```

**Comment by innerNULL** [comment]
thanks~
