### ISSUE TITLE
Create a .exe file using Default Installer

### ISSUE THREAD

**Issue by naveen521kk** [python-poetry/poetry#3534]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

First, using the default installer as specified in the documentation, https://python-poetry.org/docs/#windows-powershell-install-instructions, it creates a `.bat` file in `%USERPROFILE%\.poetry\bin` folder. I want it to create an `exe` file instead of a batch file.

It can be done using the way `setuptools` does it. Essentially, it would be to find `cli.exe` or `cli-64.exe` and rename it to `poetry.exe` and create a file called `poetry-script.py` instead of the currently present, `poetry`(without any extension) file.
Usually, `setuptools` is installed by default. If it not, the `.tar.gz` for windows, can include a copy of `cli.exe` and `cli-64.exe` which can be easily compiled using, https://github.com/pypa/setuptools/blob/main/launcher.c

Note: `poetry-script.py` needs to have proper shebang with full paths.

**Comment by TBBle** [comment]
The [`distlib.scripts package`](https://distlib.readthedocs.io/en/stable/reference.html#the-distlib-scripts-package) is what Pip uses to generate executables for this use-case. Rather than bundling a stock executable that runs a script by the same name, it generates an executable with the script text appeneded, taking advantage of a Python 3 feature (I think).

**Comment by naveen521kk** [comment]
Well, sorry for this late response. I think it would be better to use distlib because it provides some API. but still unsure how to...

**Comment by abn** [comment]
@naveen521kk happy to look at clearer proposal on how we might do this. If using `pip` or `pipx` to install `poetry` does this anyway, I would be inclined to rather make a not int he documentation and move on. 

Since the bootstrap script is intended to work with no or limited dependencies, I would be hesitent to even require `distlib`. As this is not necessarily always available and there are known issues inconsistencies with distro vendored installations of the package (eg: ubuntu).

However, if we indeed proceed to making changes, they will need to be on top of #3706 as that will be the new bootstrap mechanism. It might also be a good idea to verify if the problem goes away by virtue of the new changes, specifically how `poetry` installed into the virtual environment. Test this out and let us know.

Note: I am not recommending either of the following options, but simply identifying a way forward in the discussion.

#### Option 1
If the new bootstrap mechanism does nto solve the issue, a draft PR to that branch or mainline (once merged) might be a good way to consider any changes required.

#### Option 2
Another option (more effort) is to setup a windows installer for poetry (this might require a new issue and proper discussion).  I am not even sure if this is an option that the community wants, and I do not develop on windows myself to comment qualitatively. I am also unsure how much effort this would be to maintain going forward either. If we go down this path, an outline of steps required would be:

1. Proof of concept source in an isolated repository building a windows installer from a Poetry release. There seems to be a few frameworks one can choose from for this.
2. A github action pipeline that produces the release artifacts for testing.
3. Once we have a working-good solution, we bring this repo into the poetry org and run this as part of the poetry release pipelines.

**Comment by sdispater** [comment]
The new bootstrapping method (see https://github.com/python-poetry/poetry/pull/3706) will solve this. Basically, the new method uses `pip` which in turn creates the `poetry.exe` script which is then symlinked (or copied if symlinks are not available) to the destination directory.

**Comment by naveen521kk** [comment]
> If using pip or pipx to install poetry does this anyway, I would be inclined to rather make a not int he documentation and move on.

Yes, `pipx` or `pip` creates a `.exe` file and I have seen `pipx` and `pip` both using distlib.

> Since the bootstrap script is intended to work with no or limited dependencies, I would be hesitent to even require distlib. As this is not necessarily always available and there are known issues inconsistencies with distro vendored installations of the package (eg: ubuntu).

I would say doing this only on Windows is fine actually because that's the place where an exe is required.
