### ISSUE TITLE
Poetry source fallback fails when a source is unreachable

### ISSUE THREAD

**Issue by logangrado** [python-poetry/poetry#3565]

**Comment by sinoroc** [comment]
Exactly for cases like this, I believe the (URLs of) source repos should not be in `pyproject.toml` to begin with.

Related:
* https://github.com/python-poetry/poetry/issues/3479
* https://github.com/python-poetry/poetry/issues/3547
* https://github.com/python-poetry/poetry/issues/3552
* https://github.com/python-poetry/poetry/issues/3553

**Comment by a-recknagel** [comment]
@sinoroc I would be curious to hear your reasoning. Is it something along the lines of "adding an index makes dependencies concrete" as it is described in https://caremad.io/posts/2013/07/setup-vs-requirement/ ?

**Comment by sinoroc** [comment]
@a-recknagel 
I think I have expanded on this in one of the threads I linked.

In short: if you put the URLs of the source repositories in the `pyproject.toml` then you have to guarantee that those URLs are available for anyone from anywhere at anytime (even long in the future).

The example that keeps coming up is: if you are working on a project with some contributors based in China, then they might not be able to access some URLs (_PyPI_, being one of them), so they need to use a different URL (a mirror of PyPI), but of course it also does not necessarily make sense to hard code those mirror URLs in the `pyproject.toml` because for the rest of the contributors they are pointless. And so on and so forth...

Any contributor to a project should be free to pick the source repos URLs they want to.
