### ISSUE TITLE
Unable To Install Tensorflow on macOS Big Sur

### ISSUE THREAD

**Issue by timkofu** [python-poetry/poetry#3566]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.1
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/timkofu/415a82acc732e1aafe105961992818fc

## Issue

`poetry add tensorflow` fails in a fresh `Python 3.8.7` .venv with the final exception `distutils.errors.CompileError: command 'clang' failed with exit status 1`.

`pip install tensorflow` fails with the error `Could not find a version that satisfies the requirement tensorflow (from versions: none)`. 

I upgraded pip and setuptools to the latest releases `pip install -U pip setuptools` and rerun `poetry add`; It failed with the same exception, and the following error:
```
ERROR: Command errored out with exit status 1: /private/tmp/test_poetry/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-req-build-mqwpjztf/setup.py'"'"'; __file__='"'"'/private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-req-build-mqwpjztf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-record-be6ffsck/install-record.txt --single-version-externally-managed --compile --install-headers /private/tmp/test_poetry/.venv/include/site/python3.8/grpcio Check the logs for full command output.
```

<b>However</b>, `pip install tensorflow` now works:
```bash
python -c "import tensorflow;print(tensorflow.__version__)"
2.4.0
```

**Comment by alexpdr** [comment]
You can confirm this yourself in a minute or two by:
- Creating a new virtual environment `python -m virtualenv testenv && source testenv/bin/activate`
- Installing your affected packages `pip install numpy tensorflow pandas` etc
- Try to run a file that just imports the affected packages, if it still breaks its 100% for sure on your system 👍

**Comment by timkofu** [comment]
@alexpdr In my last few sentences, I showed that it does work with an updated pip and setuptools, but not with poetry. Im current working with plain `activate .venv/bin/activate` and `deactivate`. Pandas, Tensorflow, Seaborn et al are all working well with plain pip.

**Comment by alexpdr** [comment]
----> https://github.com/grpc/grpc/issues/24677 
You might be able to find additional help here, but I'd resubmit the error message on the framework/tool that produces the error (which here is grpc)

> ERROR: Command errored out with exit status 1: /private/tmp/test_poetry/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-req-build-mqwpjztf/setup.py'"'"'; __file__='"'"'/private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-req-build-mqwpjztf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/22/yt1nh2rd27x1pjfv0zvq0c9w0000gn/T/pip-record-be6ffsck/install-record.txt --single-version-externally-managed --compile --install-headers /private/tmp/test_poetry/.venv/include/site/python3.8/grpcio Check the logs for full command output.

**Comment by timkofu** [comment]
Had seen that thread before reporting this; it's where I got the idea that using (the latest) plain pip would solve the DS stack (and other) install issues. Specifically [this comment](https://github.com/grpc/grpc/issues/24677#issuecomment-749773641). "It's working fine with pip, have you tried that?" will probably be the first comment.

The `activate .venv/bin/activate` and `deactivate` (and manually managing the prod and dev deps) workflow is working well for us, but Poetry is such a great tool, and we like reporting issues as soon as we find them, so we can all keep having great DX.

**Comment by finswimmer** [comment]
Which versions of `pip` and `setuptools` are installed in the venv created by poetry?

**Comment by loganjhennessy** [comment]
I came across the same issue when attempting to install `google-cloud-bigquery` which also depends on `grpcio`.

There is a lot going on here, but the offending line in `grpcio` is https://github.com/grpc/grpc/blob/master/setup.py#L358.

The return value from `sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')` has always been a `str` (e.g. `10.14`, `10.15`, etc.) but in Big Sur, it is possible to get a `MACOSX_DEPLOYMENT_TARGET` value of just `11`. Config values that look like integers are interpreted as integers by cpython, see https://github.com/python/cpython/pull/23622 and https://github.com/python/cpython/pull/23556. So on Big Sur, `sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')` returns an `int`.

I was able to get this to work by downgrading my Python distribution to 3.7 since, for whatever reason, `sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')` returns `11.0`, which gets passed through as a `str`.

I don't know exactly where the fix for this should be made. It is frustrating that the value gets cast to an `int`. One solution would be to have the return value from that call in `grpcio` be cast to `str` before being passed to `pkg_resources.parse_version()`.

By the way, I'm using Brew for this. Someone mentioned hardcoding the value in the Brew formula as a workaround (see https://github.com/python/cpython/pull/23556#issuecomment-737958574) although I don't think this is a good long-term solution.

**Comment by timkofu** [comment]
@finswimmer with the venv created with `poetry env use ~/.pyenv/versions/3.8.7/bin/python`:
```python
>>> import pip, setuptools
>>> pip.__version__
'20.2.2'
>>> setuptools.__version__
'49.6.0'
```

**Comment by nacaclanga** [comment]
Wheel installation was fixed in packaging (https://github.com/pypa/packaging/pull/319) and the newer version is used in pip (https://github.com/pypa/pip/issues/9138), but not in poetry or poetry-core. I suspect that this kind of issue could be fixed by providing a new version of poetry-core, where the vendored packaging dependency is updated to the latest release and then fix the requirements of poetry itself.

**Comment by damienrj** [comment]
I think this would also solve the issue with needing pip 20.3.0> to be able to download wheels.
https://github.com/python-poetry/poetry/issues/3591

**Comment by bajohn** [comment]
I had a similar issue as described by @loganjhennessy , regarding `google-cloud-bigquery` being unable to install `grpcio`.

A quick fix that worked for me was running 
```
export SYSTEM_VERSION_COMPAT=1
```
Afterwards, clang errors were no longer thrown and I was able to install via pipenv. Not sure if this fix applies to the original issue but hope it helps!

**Comment by timkofu** [comment]
This is now working perfectly with release [`1.1.5`](https://github.com/python-poetry/poetry/releases/tag/1.1.5).
