### ISSUE TITLE
Poetry Install fails when remote repo sends ConnectionReset

### ISSUE THREAD

**Issue by jjeff07** [python-poetry/poetry#3572]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When a Python repo is having issues and sends a Connection Reset during the a fresh poetry install the installation errors and does not retry.

Creating virtualenv package-z2q3sM71-py3.8 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...
  ConnectionError
  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  at /usr/local/lib/python3.8/site-packages/requests/adapters.py:498 in send
      494│                     low_conn.close()
      495│                     raise
      496│ 
      497│         except (ProtocolError, socket.error) as err:
    → 498│             raise ConnectionError(err, request=request)
      499│ 
      500│         except MaxRetryError as e:
      501│             if isinstance(e.reason, ConnectTimeoutError):
      502│                 # TODO: Remove this in 3.0.0: see #2811

It would be nice to catch this exception and have a flag to have it retry X amount of times before failing.

**Comment by hagaika** [comment]
related to #3219

**Comment by abegun** [comment]
Are you still hitting this issue?  We also hit issues like this consistently on some of our packages.  If you are still hitting it, I forked Poetry a while back to experiment with a change to help with the issues we were hitting with intermittent request failures:  https://github.com/abegun/poetry.  The change is simply to configure retry logic in the request library to not fail immediately.

If you want to try it, would be great to see if this works for others (it is rock solid for myself and teammates who are hitting similar issues.)

1. Clone the fork
2. Run "poetry install" from the source directory you just pulled down
3. Run "poetry shell"
3. Go to your directory that you want to run poetry
4. Run "python -m poetry [command]"

I'm not a Poetry dev so the above steps for running a local version of poetry might not be official but have worked for me.

One gotcha -ensure you like the active version of python when you do step #2 since the local version of poetry's environment will use that.

**Comment by tfishr** [comment]
Although the abegun fork is getting behind now, it still can work on the latest version of poetry. You can clone the official poetry, manually apply the patch to `pypi_repository.py` from this fork onto whatever branch of the official repo you like, and then follow the rest of the instructions above to be able to run `poetry install`.

Without this patch, `poetry install` works only on my slower computers. On my new computer I keep getting `ConnectionResetError`/`ConnectionError` and it just doesn't work until it has this patch applied first. This happens on all operating systems I have tried it on. Just requires the Intel EVO 11th Gen Intel Core i7-1185G7.

**Comment by TNonet** [comment]
Can we open this as a PR? I am hitting this same issue.

**Comment by dimbleby** [comment]
poetry 1.2 includes retries, this can be closed
