### ISSUE TITLE
Oh-My-Zsh Autocomplete Issue

### ISSUE THREAD

**Issue by fishbotics** [python-poetry/poetry#3585]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I downloaded Poetry from the docs (I have version 1.1.4) and set up the autocomplete in Oh-My-Zsh as specified. But when I type `poetry --ver` and hit tab, I get these errors in the terminal:
```
_poetry_b68b21315010d4d8_complete:16: bad set of key/value pairs for associative array
_poetry_b68b21315010d4d8_complete:16: bad set of key/value pairs for associative array
_poetry_b68b21315010d4d8_complete:16: bad set of key/value pairs for associative array
```

**Comment by tcoliver** [comment]
I was having the same issue, so I dug in a little. It appears that poetry is using [cleo](https://cleo.readthedocs.io/en/latest/introduction.html#autocompletion) to power it's autocompletion. On their repo there is a similar open [issue](https://github.com/sdispater/cleo/issues/85) and related [pull request](https://github.com/sdispater/cleo/pull/86/files). The fix listed is to add restrict `coms` and `opts` to local variables. i.e,

```diff
-    local state com cur
+    local state com cur coms opts
```

Making this change in my `$ZSH_CUSTOM/plugins/poetry/_poetry` file seems to have worked for me. Unfortunatly, since the issue appears to be with cleo and not directly poetry, I doubt they can fix it until cleo merges the pull request.

**Comment by mattalexx** [comment]
This is happening without have Oh-My-Zsh.

```shell
~ % poetry add --[TAB]
_poetry_221ff8ff0ccab716_complete:16: bad set of key/value pairs for associative array
```

There's also this, which is wrong too:

```shell
~ % poetry add -[TAB]
No match within `file'
```

Environment:

```shell
~ % zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)
~ % poetry --version
Poetry version 1.1.12
~ % type -s poetry
poetry is /home/matt/.local/bin/poetry -> /home/matt/.local/share/pypoetry/venv/bin/poetry
~ % cd /home/matt/.local/share/pypoetry/venv/bin/
bin % ./python --version
Python 3.10.1
bin % ./pip list | grep cleo
cleo                              0.8.1
```

**Comment by ethnhll** [comment]
I was having this issue as well, and making the change that @tcoliver suggested in `$ZSH_CUSTOM/plugins/poetry/_poetry` fixed it for me.

**Comment by Secrus** [comment]
This issue was solved on Cleo side: https://github.com/python-poetry/cleo/pull/86 and awaits a release of Cleo (see [release checklist](https://github.com/python-poetry/cleo/issues/248)). When Cleo 1.0 is released, it will be available on current master branch and backported to 1.2 version.
