### ISSUE TITLE
Input Error when poetry run argument starts with double forward-slash

### ISSUE THREAD

**Issue by thejcannon** [python-poetry/poetry#3590]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Build 19041
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

Although the following commands are nonsensical, I would expect Python to be complaining, not Poetry.

```bash
poetry run python //foo
poetry run python "//foo"
```

(The real-world example is me `poetry run`-ing a script and passing an argument that starts with "//").

**Comment by finswimmer** [comment]
Either this is fixed or I don't get the point of your issue, because you don't show the expected and the actual output. For both commands I get:

```
can't open file '//foo': [Errno 2] No such file or directory
```

complained by python.

Closing this, because no more information were added for a long time and I assume it's solved. Feel free to leave a comment if you disagree.
