### ISSUE TITLE
Implement PEP-650

### ISSUE THREAD

**Issue by finswimmer** [python-poetry/poetry#3605]
Currently [PEP-650](https://www.python.org/dev/peps/pep-0650/) is still in [discussion](https://discuss.python.org/t/pep-650-specifying-installer-requirements-for-python-projects/6657). Once it is accepted poetry should implement it.

**Comment by kkirsche** [comment]
I believe you mean "accepted" instead of "excepted":

Accept is a verb meaning "to receive something willingly." One can accept a gift for example, or a club can accept a new member.

The verb 'except' has the meaning of "to leave out or exclude (someone or something)."

The confusion between except and accept most commonly stems from their similarity in sound (homonyms).

**Comment by mkniewallner** [comment]
The PEP [has been withdrawn](https://discuss.python.org/t/pep-650-specifying-installer-requirements-for-python-projects/6657/64), so closing this issue.
