### ISSUE TITLE
Have poetry be able to deal with bad repository metadata

### ISSUE THREAD

**Issue by connerxyz** [python-poetry/poetry#3644]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Make `poetry` look deeper into artifact repositories to avoid bad metadata. I don't understand all the lower-level technical details, but basically I've found `poetry` gets hung up identifying some package versions where `pip` does not. I recall an issue discussing this, something about "poetry only looks at the metadata index"? But I couldn't find it to reference here.

Here's a related StackOverflow post https://stackoverflow.com/questions/65783409/poetry-install-fails-with-envcommanderror-looks-for-version-2020-12-21-3-lambda/66052550#66052550

This issue may also be related https://github.com/python-poetry/poetry/issues/3543

**Comment by finswimmer** [comment]
Hello @connerxyz,

of course we have to look on every case, where people believe poetry doesn't find the correct data. But as a general rule, poetry will not make any wild guesses where to find data, if package maintainers or providers doesn't follow accepted rules. We want force people to correctly build their packages and provide it the correct way.

In your StackOverflow post you've posted that the problem was a misconfigured/poisoned private repository. That's why I will close this issue. If you disagree please just leave a comment.

fin swimmer

**Comment by connerxyz** [comment]
We use Poetry heavily across out team, and this issue caused blockers on projects with no changes (they just suddenly broke).

Our team decided it was worth opening an issue, since whatever checks pip does weren't affected and perhaps poetry could similarly be robust.
