### ISSUE TITLE
Run command in different directory to pyproject.toml file

### ISSUE THREAD

**Issue by pxeger** [python-poetry/poetry#3804]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Often I want to run a command in a different working directory to the one the `pyproject.toml` file is in, especially when the Python project is only part of a larger project.

Currently you can do this as a workaround:

```bash
cd dir
poetry run sh -c 'cd previous_dir; command'
cd previous_dir
```

but this is pretty inconvenient. It would be nice to be able to specify the location of the directory containing the `pyproject.toml` file as an option to the `poetry` command, so instead I could do something like `poetry --project-root dir run command`.

Also, it would be good to be able to specify this as an environment variable as well or instead, so I don't have to type the option every time if I'm hopping around in a project, or invoking `poetry` repeatedly from a script.

This could be specific to the `run` sub-command as that's where I foresee it being most useful, but I think it should be a global option.

This behaviour would be similar to the `--work-tree` flag (or `GIT_WORK_TREE` environment variable, or `core.worktree` configuration option) to `git`.

I can do a PR if consensus is reached.

**Comment by sinoroc** [comment]
The `poetry --project-root path/to/project somepoetrycommand` looks like a very practical feature to have. I would not be surprised if it has been requested already. I would rather go one step further and make it so that the flag expects a full file name, so that it is possible to do something like:

```
poetry --project-file path/to/something.toml somepoetrycommand
```

At probably no additional cost this would cover the case where, hypothetically for whatever reason, one would want to work with a file not named `pyproject.toml`.

Maybe it would be worth to go all the way and allow to specify the configuration file name and the project root dir path separately:

```
poetry --project-file path/to/some.toml --project-root path/to/project somepoetrycommand
```

**Comment by pxeger** [comment]
I don't know if specifically pointing to a file is a good idea, since PEP 621 specifies the file to be called `pyproject.toml` (I think? - https://github.com/python/peps/issues/1897) and all other tools require it to be like that.

**Comment by mykter** [comment]
possibly a duplicate of #2179 ?

**Comment by pxeger** [comment]
Yes, it is, sorry
