### ISSUE TITLE
poetry add pandas fails on Python 3.7.3

### ISSUE THREAD

**Issue by tactlessfish** [python-poetry/poetry#3844]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10 (Buster)
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Here](https://gist.github.com/tactlessfish/fb4f951121ea69904146cc7b6cafb40f)

## Issue

When I run `poetry add pandas` with virtual environment Python 3.7.3, Poetry fails with SolverProblemError. Here is the [command output for poetry](https://gist.github.com/tactlessfish/6bfed3f0bd3405b46072b300503030fe). However, when I run `pip install pytest pandas` in a different project (still with Python 3.7.3), it works. Here is the [command output for pip](https://gist.github.com/tactlessfish/0cb14a0c4749ae2dad7375061fbc998b).

**Comment by abn** [comment]
@tactlessfish this happens because

1. Your project supports python versions >=3.7.0, <4.0.0.
2. Pandas only supports python version >=3.7.1.

So pandas cannnot be installed on `3.7.0`, and since your project claims via `python = "^3.7` that it supports `3.7.0`, resolution fails.

You can prevent this by doing one of the following,
1. Specify that your project requires `python = ">=3.7.1"`.
2. Specofy that pandas is only required when python is `>=3.7.1`. As shown below.

```toml
pandas = { version = "^1.2". python = ">=3.7.1"}
```

**Comment by abn** [comment]
Closing for now. Feel free to re-open or comment if the above does not resolve your issue.

**Comment by tactlessfish** [comment]
That makes sense. Thanks for the clear explanation!
