### ISSUE TITLE
resolve dependencies according to the python version defined in pyproject.toml instead of venv

### ISSUE THREAD

**Issue by sify21** [python-poetry/poetry#3951]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina Version 10.15.7
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/sify21/40580871361097a299eae1e95d219bc7

## Issue
jsonschema requires importlib_metadata for python version < '3.8', you can see it [here](https://github.com/Julian/jsonschema/blob/main/setup.cfg). 
I specified python version as ">=3.5,<4.0" in pyproject.toml. But the python version in virtual environment is 3.9.
```
❯ poetry env info

Virtualenv
Python:         3.9.2
Implementation: CPython
Path:           /Users/sify21/test/.venv
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9
```
As a result, importlib_metadata is not included in my dependencies. I think poetry should respect the version defined in pyproject.toml and include importlib_metadata as a dependency of my project.

**Comment by abn** [comment]
The [`python` version sepcification](https://gist.github.com/sify21/40580871361097a299eae1e95d219bc7#file-pyproject-toml-L8) refers to your projects python requirement. In your case, it says your project is compatible with `>=3.5,<4.0`. However, as you do not explicitly define `importlib_metadata` as a direct dependency of your project, `poetry` correctly resolves this as required only in environments where the `python_version < '3.8'`. This is because it is not required in your active environment. In your case, `jsonschema` does not rely on the dependency if the active environemnt is `<3.8`. This [snippet from `jsonschema`](https://github.com/Julian/jsonschema/blob/833b6a9562487b4c46cd5640de5e2ae074c08796/jsonschema/__init__.py#L35-L39
) only uses this as a fallback, if stdilib is not available. 

If you explicitly want it available in all cases, you should add it to your project's dependencies. 

```sh
poetry add importlib_metadata
```

However, this is not recommended without a python marker as `importlib.metadata` is part of the stdlib from 3.8 onwards. If your project, does indeed use `importlib.metadata`, you will want to [add it with a python restriction](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies).

```sh
poetry add --python "<3.8" importlib_metadata
```

Again, this would mean that if your active environment is not `<3.8`, the dependency will not be required as it is not required for the environment. 

Poetry discovers the a compatible python version from your environment in order to create the virtual environment, which in your case looks like it was 3.9. If you want a specific version of python for your environment you can do so by the following command.

```sh
poetry env use /full/path/to/python
```

See [Managing environments](https://python-poetry.org/docs/managing-environments/) for more information.
