### ISSUE TITLE
'poetry install' fails on Mint with 'system-site-packages' opion

### ISSUE THREAD

**Issue by vlad0337187** [python-poetry/poetry#4022]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux Mint 20.1**: 
- **master**: 
- **doesn't depend on pyproject.toml**: 

## Issue

`poetry install` fails to complete if [system-site-packages option](https://github.com/python-poetry/poetry/pull/1982) was specified to True.

Steps to reproduce.
- install Poetry from master: `pipx install git+https://github.com/python-poetry/poetry.git`
- ensure that `pip list` has `python-debian           0.1.36ubuntu1` package listed, if no - install it (`apt install python-debian`)
- open terminal in any directory, run `poetry init`
- enable system-site-packages: `poetry config virtualenvs.options.system-site-packages true --local`
- run `poetry install`
- see error: ` Invalid PEP 440 version: '0.1.36ubuntu1'`

It fails only on Linux Mint 20.1, should fail and on Ubuntu 20.04 too.

As I see, this is not actually a Poetry but, but but with `python3-debian` apt package, which specified not PEP 440-compliant version.

[Reported this to Ubuntu bug tracker](https://bugs.launchpad.net/ubuntu/+source/python-debian/+bug/1926870)

I think this issue should be here until this will be fixed in Ubuntu or Mint or Debian side.

Workaround:
- specify valid version in `/usr/lib/python3/dist-packages/python_debian-0.1.36ubuntu1.egg-info/PKG-INFO`
- also in `/usr/lib/python3/dist-packages/debian/_version.py`
- valid version: `0.1.36+ubuntu1`

**Comment by abn** [comment]
Considering the issue is, as you have pointed out, in the distro provided package I am wondering what is gained by keeping this one open as there is not real action required on the poetry side.

Or are you considering that poetry should handle this less strict? (this will be a step backwads imho)

**Comment by vlad0337187** [comment]
@abn , I think we should track: will that issue be resolved or at least be going to be resolved.

If no - probably, to don't handle versions naming less strict, but add exception for a specific (python-debian) package.

I consider this to be issue with Poetry too, because freshly installed Poetry will crash on freshly installed system (Mint).

**Comment by dephekt** [comment]
Marked this on Launchpad as affecting me too, so at least it shows `confirmed`. The backstory for me is: for gpgme Python bindings the gnupg-recommend way of installing them is using the system package as that will always be compatible with your system-installed gpg version and is well-maintained by the distribution's maintainers.

The version installed on PyPi with `pip install gpg` is 3 years old and may not be compatible from one developer to the next if their system gpg version does not match. In order to adopt Poetry for the `torbrowser-launcher` project, I need to use the new `system-site-packages` config in 1.2.0a1 so I can tell developers "install python3-gpg using your system's package manager then run `poetry install`" to get their local dev environment configured properly.

I completely agree that the issue is _not_ Poetry, but it would be absolutely fantastic if there was _an option_ to be less strict/pedantic in this particular context. This way, we could still adopt and use Poetry today and not be blocked waiting for the distribution to roll out a fix for the versioning.

**Comment by mmorton** [comment]
I'm running into the same issue on Ubuntu 20.04 LTS.  The project I am working on requires a Python library, `dlib`, which has to be compiled from source in order to use CUDA;  It is then installed into `dist-packages`.  There are other project dependencies that require this one, but right now, my only option is to not track any of those dependencies, neither `dlib` or the packages that depend on it, with Poetry.  Which, in a way, defeats the reason for using something like Poetry in the first place.  

I do understand that the issue is "in the distro provided package", but this is a real-world scenario running on standard (long term support) distro versions.

**Comment by neersighted** [comment]
Dupe #6013
