### ISSUE TITLE
Poetry can't install opencv but pip can (RPI)

### ISSUE THREAD

**Issue by A-Telfer** [python-poetry/poetry#4073]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. NOTE: there are some similar mac os ones, but some of the solutions are targeted at macs and none worked for me.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Raspbian, release 10 
- **Poetry version**: 1.16

## Issue
`poetry add opencv-python-headless` fails, but `pip install opencv-python-headless` works. 

This is my first time using poetry and it's not going very well. I've spent a few hours searching around for solutions but no luck, the closest I've come is  #3621 (I tried many of the solutions in the linked issues), I've tried installing different versions of opencv, upgrading pip, reinstalling poetry... nothing has worked so far.

**Comment by clintonroy** [comment]
What error do you get?

**Comment by A-Telfer** [comment]
```
Unable to find installation candidates for opencv-python-headless (4.5.2.52)
```

**Comment by epower** [comment]
I've found adding 
```
[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"
```
to the pyproject.toml file allows the correct candidate to be installed provided the relevant system dependencies are present.

**Comment by LorhanSohaky** [comment]
That happened to me

![image](https://user-images.githubusercontent.com/16273730/118854399-1370a580-b8ab-11eb-958b-cec72dc006ae.png)

**Comment by jimmywan** [comment]
@A-Telfer Might want to try increasing the verbosity. Might give you more insight into what's going on.
```
poetry add -vvv opencv-python-headless
```

**Comment by A-Telfer** [comment]
Thanks for the suggestions, I got it working

1. Following @epower, I added piwheels to the pyproject.toml file
```
[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"
```
2. Look on [piwheels](https://www.piwheels.org/project/opencv-python-headless/) to find which opencv versions are supported, then explicitly add it. eg `poetry add opencv-python-headless==4.5.1.48`

**Comment by A-Telfer** [comment]
Without specifying the version it tries to install the latest pip version (4.5.2.52) and fails. The reason pip works on the RPI is that it seems to search piwheels first and tries to install `4.5.1.48`.

It would be nice if poetry could be configured to have the same behavior as pip...

**Comment by jlumbroso** [comment]
@A-Telfer Honestly, save yourself the trouble.

I started using `poetry` two years ago because the TOML file format seemed like a major improvement. I believed @sdispater declaring himself a "Proud Pythonista" — and thinking strategically about the Python packages to create (clikit, clio, tomlkit, poetry, etc.) meant that he might be a French @kennethreitz!

But years later, `poetry` is the biggest, most consistent source of trouble of all my projects. Far from helping remove anxiety from Python packaging, it is the biggest source of stress. Can you believe I still can't install `opencv` over a month after you reported this — and six months after #3458 and #3591. If we go from several configuration files, to one configuration file but having to use several installers, is this really an improvement? I don't mean to impeach the meritorious and heroic efforts of all the FOSS maintainers of this repo, but the tool itself was poorly designed and is very, very brittle. Fixing it seems like removing water from a sinking ship with a teacup.

If you are just giving it a try, run now while you can! You're better off with [`pipenv`](https://github.com/pypa/pipenv/)! Not everybody can be @kennethreitz...

**Comment by JexPY** [comment]
Same problem with **PyJSON5** [https://pyjson5.readthedocs.io/en/latest/index.html](https://pyjson5.readthedocs.io/en/latest/index.html),

I tried `poetry add pyjson5 ` but getting:
```PYTHON  
• Installing pyjson5 (1.6.0.post1): Failed

  RuntimeError

  Unable to find installation candidates for pyjson5 (1.6.0.post1)
```

**Comment by clintonroy** [comment]
> Same problem with **PyJSON5** https://pyjson5.readthedocs.io/en/latest/index.html,
> 
> I tried `poetry add pyjson5 ` but getting:
> 
> ```python
> • Installing pyjson5 (1.6.0.post1): Failed
> 
>   RuntimeError
> 
>   Unable to find installation candidates for pyjson5 (1.6.0.post1)

The error's not great, but the problem is that there's no sdist for pyjson5, and only windows builds, check out pypi. Poetry should probably do better here, and take that into account when doing resolving. PyJson5 should definitely upload an sdist though.
