### ISSUE TITLE
"This installer is deprecated" with recommended install

### ISSUE THREAD

**Issue by nzig** [python-poetry/poetry#4128]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker image `python:3.9.5-buster`
- **Poetry version**: Installing from `master`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not relevant

## Issue

When installing Poetry according to the [documentation](https://python-poetry.org/docs/#installation) by running
```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```
The following warnings is printed:

> This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.

This seems to be because of c28728fbe3e69c9995a4ea132dd767074f00e6f8. I think the root of the issue is that the instructions recommend you use `master` to install the current version (1.1), but `master` has already been updated to the 1.2 situation with the deprecation.

I think either the recommended install should use the `1.1` branch, or `master` should be reverted not to issue deprecation warnings until `1.2` is released.

**Comment by finswimmer** [comment]
Hello,

the `get-poetry.py` script doesn't care if its from the master branch or 1.1. It receives the version to install from https://github.com/python-poetry/poetry/releases.

The deprecation warnings arises because this script will be replaced by the `install-poetry.py' script in the future. The scripts differ in the way how and where poetry is installed. This is why you will not be able to run `poetry self update` to update to 1.2.0a1 or later when installing with `get-poetry.py`. Version 1.2.0a1 depends on the new way of installing.

fin swimmer

**Comment by nzig** [comment]
Thank you for your response and your work on Poetry.

I understand that `get-poetry.py` install the version from releases, but the code of `get-poetry.py` itself does depend on the branch, and it's currently issuing a warning that is not yet relevant until 1.2 is released.

I just think it's a bad user experience to follow the official instructions and get a deprecation warning, even though there's nothing you can do about it. If this is the intent, maybe the wording should be changed to still warn the user that 1.2 will require a reinstall, without sending them searching for the non-deprecated installer which isn't released yet.

Thanks again!

**Comment by TRiggAtGM** [comment]
I know this issue is closed but I think @nzig  brings up a very valid and important point. I'm relatively positive that I'm not the only person who clicked the little thumbs up on his comment because we wound up here googling "Okay, so how am I supposed to install poetry if the script from the documentation is the wrong way to do this"

I think perhaps the wording should be changed from saying "This script is deprecated" to something like

```
NOTICE: In the near future this script will be deprecated. If you are using it to install a version prior to 1.2, you should be fine
```

**Comment by zoltanspire** [comment]
I second the previous comments. Had the wording been better, it would have saved me a trip and reading through this thread to find out that the deprecated method is the only method. Bad user experience that could be fixed very easily by using more considerate wording.
