### ISSUE TITLE
Failed to initialize a project without human intervention

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#4129]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.3.1 (20E241)
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```
[tool.poetry]
name = "my_proj"
version = "0.1.0"
description = "my proj"
authors = ["john.doe"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.0"
kkpyutil = "^0.2.1"

[tool.poetry.dev-dependencies]
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
I'd love to initialize a poetry-generated project without going through the interactive shell for versions and dependencies etc. 

However, a few attempts of fiddling around with the command line options all failed: it still forces me to go through the prompts.

Such as 

```sh
poetry init --name my_proj --description  "my proj" --author john.doe --python 3.9 --dependency "pytest:^6.2.0" --dev-dependency coverage -l MIT
```

gives me the interactive shell to **confirm** all the info I have already provided through the commandline above.

## Expectation

I expect that by giving all the dependencies, the command should generate a `pyproject.toml` automatically without me entering anything.

Where am I wrong?

**Comment by finswimmer** [comment]
Hello @kakyoism,

please be so kind to inform if you crosspost you question. This one is also asked on [stackoverflow](https://stackoverflow.com/questions/67802992/initialize-a-python-poetry-project-without-human-interaction).

My answer there:

Just add `-n` or `--no-interaction` to your command and you will get what you are asking for.

It's intended to not imply this option automatically when passing arguments to `poetry init`. Because `poetry` can not know if you want to add something additionally.

fin swimmer

**Comment by kakyoism** [comment]
Thanks a lot. I'll be more careful about cross-posting.
