### ISSUE TITLE
Support `include_package_data`

### ISSUE THREAD

**Issue by brno32** [python-poetry/poetry#4184]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I'm using 

```
[tool.poetry]
include = ["tests/some_files"]
```

to make sure some data files are packaged with my library. I can see them in the gzip which `poetry` created when I run `poetry build`. However, after pip installing the package, they're nowhere to be found. I believe this is because `include_package_data` isn't set to `True` in the `setup.py` file I see inside the GZIP.

First, am I correct about this, and second, would getting poetry to set `include_package_data` to `True` when `include` in the `pyproject.toml` is set work?

**Comment by finswimmer** [comment]
Hey @brno32 ,

what ever is in the `setup.py` is not relevant anymore, because nowadays `pip` recognize the `pyproject.toml` correctly.  This is why we will drop generating the `setup.py` in the near future.

My guess is, that you will found the `tests` folder directly in the `site-packages` folder. This is not what you want. If really want to deploy the tests folder with the library, you should move it to folder where your python files are.

fin swimmer
