### ISSUE TITLE
Poetry launches three Python instances with `poetry run python myscript.py`

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#4193]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

On Windows, when I use `poetry run python myscript.py` to run my script, I saw three Python instances in process tree, is this normal? 

I guess `poetry run` uses its own Python scripting under the hood, however,
would it cause performance issues using Poetry to launch my script regularly, compared to `python myscript.py`?

**Comment by finswimmer** [comment]
Hello @kakyoism,

I have no benchmarks, but I don't think that you will get any performance issues,, because 2 of the 3 process will not do much.

I guess the 3 process are:
 * poetry itself
 * a shell created by poetry to activate the venv
 * the python script that runs in the activated shell

The docs explain why the spawn of a new shell is needed: https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment

fin swimmer
