### ISSUE TITLE
A few documentation issues

### ISSUE THREAD

**Issue by Keats** [python-poetry/poetry#422]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hi!

It seems that there are a few issues in the docs:

- commands are not up to date: `cache:clear`, `list`, `develop`, `debug:*` are not listed at all in https://poetry.eustace.io/docs/cli/
- links in the sidebar are relative so if you click on any of them, any click on another link other than hashes will be a 404. For example clicking on Commands and then Libraries will try to load https://poetry.eustace.io/docs/cli/libraries/

**Comment by jacebrowning** [comment]
The 404 on the documentation site means no one can complete the issues checklist that requires us to search the docs.

**Comment by sdispater** [comment]
I fixed the 404 errors in the documentation.

And I agree that the documentation needs an update. I will try to do it before the next `0.12` release.

**Comment by AtomBaf** [comment]
Hi
I'm adding this typo to this issue (not sure if I need to create a new one since it is very similar and quick to resolve) :
In the https://poetry.eustace.io/docs/configuration/ page, the last link is not good
should be https://poetry.eustace.io/docs/repositories/ but the 'docs' part is missing
Thank you
