### ISSUE TITLE
Dependencies of halo not resolved when added as a git dependency

### ISSUE THREAD

**Issue by rpocase** [python-poetry/poetry#4325]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 (WSL 2)
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com) with the contents of your pyproject.toml file**: https://gist.github.com/rpocase/5a58f40db1068ce04ce3d94a73b010a4

## Issue
When adding [halo](https://github.com/manrajgrover/halo) as a git dependency, transitive dependencies are not resolved. This seems to occur in poetry 1.1.4+. I have a use case that depends on [this fork](https://github.com/frostming/halo/tree/multiple-spinners), but I have preserved it's original contents (referenced in the gist) in case it gets removed.

```
 poetry update -vvv
Using virtualenv: /home/rpocase/git/scs/temp-package/.venv
Updating dependencies
Resolving dependencies...
   1: fact: temp-package is 0.1.0
   1: derived: temp-package
   1: fact: temp-package depends on halo (branch multiple-spinners)
   1: selecting temp-package (0.1.0)
   1: derived: halo (0.0.31 git branch multiple-spinners)
   1: selecting halo (0.0.31 fa4835f)
   1: Version solving took 0.641 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

No dependencies to install or update
```

**Comment by dimbleby** [comment]
https://github.com/rpocase/halo/blob/cdfb1324ac34e14ff045b5139f4e128e4519cbff/setup.py#L41

poetry is not a python interpreter and will not execute this code to learn dependencies.

**Comment by radoering** [comment]
I agree in principle, but digging in our code I would take a more differentiated view:

Here, we only use the information from setup.py if it is "complete" (otherwise we do a build):
https://github.com/python-poetry/poetry/blob/48a76fd1e27a7e329b8987407c409ee3eb28347c/src/poetry/inspection/info.py#L583-L586

So the question is why don't we try a build even though we were not able to parse `install_requires`? That's because we were able to parse `extra_require` and both are merged to `requires_dist`. Thus, we could improve the heuristics.

Nevertheless, it might make more sense to convince projects to specifiy their dependencies in a [more static way](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#declaring-required-dependency) when using setuptools.

**Comment by dimbleby** [comment]
#8774 is the same

**Comment by radoering** [comment]
I'm closing this as a duplicate even though it's older than the other issue because the other issue is more general.
