### ISSUE TITLE
poetry install doesnt create .env folder inside project folder with Anaconda python 3.9 virtual env

### ISSUE THREAD

**Issue by pwijethunga-MSD** [python-poetry/poetry#4490]
I have anaconda 3.8 on windows 10. I created python3.9 virtual environment and set poetry config virtualenvs.in-project true. But when I do poetry install it doesnt create the .envn folder inside the project. Below is the poetry env info results:

***(python39) C:\Users\username\Developer\Packages\test5>poetry env info

Virtualenv

Python: 3.9.6

Implementation: CPython

Path: C:\Users\username\Anaconda3\envs\python39

Valid: True

System

Platform: win32

OS: nt

Python: C:\Users\username\Anaconda3\envs\python39***

However, when deactivate the python39 environment and run poetry install it creates the .envn folder inside project. and the poetry env info results the following:

Virtualenv

Python: 3.9.6

Implementation: CPython

Path: C:\Users\username\Developer\Packages\test2.venv

Valid: True

System

Platform: win32

OS: nt

Python: C:\Users\username\Anaconda3\envs\python39

how can I make it work in python39 environment?

**Comment by finswimmer** [comment]
Hello @pwijethunga-MSD,

this is an expected behavior. Whenever poetry detect it's running within a virtual environment it will not create a new one ( Exception: condas "base" environment is not detected as a virtual environment).

To create an in-project venv for python3.9 using conda you can do this:

* set the config to `virtualenvs.in-project true`
* without being in a venv run `poetry run env use /path/to/python3.9` once
* run `poetry install`

Also have a look into the [docs](https://python-poetry.org/docs/managing-environments/#switching-between-environments) about `poetry env use`.

fin swimmer

**Comment by vicmattos** [comment]
Would it be difficult to make it optional?

I was testing a setup where I create a virtualenv to install python based system dependencies for a project (like poetry, nox and pre-commit) in a deterministic way with conda's environment.yaml and it would be perfect if poetry could create a .venv in the root of the project.

Also it would make vscode finally identify poetry's interpreter automatically. It would be perfect!!

Was the decision for this expected behavior final? What was the rational for it?
