### ISSUE TITLE
Invalid PEP 440 version for local version identifiers

### ISSUE THREAD

**Issue by njgrisafi** [python-poetry/poetry#4513]
- [x] I am on the [1.2.0a2](https://github.com/python-poetry/poetry/releases/tag/1.2.0a2) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.5.2
- **Poetry version**: 1.2.0a2

## Issue

We are testing the new pre-release for poetry and running into the following error:
```
  InvalidVersion

  Invalid PEP 440 version: '0.8.3.77ab018c48822be18814fd6138d8c4d57a4a59fd'
```

This is the repo release for reference: https://github.com/Rippling/modin/releases

Perhaps our versioning schema is incorrect? We thought this would be valid under [local-version-identifiers](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) but does not seem to be the case now.

**Comment by finswimmer** [comment]
Hello @njgrisafi,

there is `+` missing before the local version identifier. The correct version would be `0.8.3.77+ab018c48822be18814fd6138d8c4d57a4a59fd`

fin swimmer

**Comment by neersighted** [comment]
Hi @tall-josh -- this issue is long closed and relates to the versioning of a Poetry-managed project. Judging by your snippet (which looks to be a lockfile), you are running into issues with a dependency.

It looks like mmcv-full is providing invalid version numbers for their built wheels -- only one `+` should ever be present and it marks the start of the local version identifier under PEP 440. The [permitted character set](https://peps.python.org/pep-0440/#local-version-identifiers) is well defined, so while I am surprised that pip or other tools may allow for this, Poetry is not wrong to refuse to parse that version.

To fix this, the mmcv-full maintainers (or whoever is distributing wheels) would need to change the version to something PEP 440 compliant like `1.4.4+torch1.10.0.cu111` or similar (note the use of a `.` as a separator). Alternatively, if you install mmcv-full from source (though this will require you to have a working build environment for the native extension/compute environment you want to make use of), you won't have any incorrect local versions to give you trouble.

You can do this by setting `installer.no-binary` to `mccv-full` -- e.g. `poetry config installer.no-binary mmcv-full`, then you can `poetry add mmcv-full` as normal. That being said, the compilation of these packages tends to be complex, and thus any specifics past this point are out of scope for Poetry/an exercise left to the reader.

Hopefully that helps -- if after opening an issue on the mmcv-full repo, they need help understanding why their version numbers need altering, or if they think there is something Poetry can do, please feel free to open a new issue here.

**Comment by tall-josh** [comment]
Thanks @neersighted I'll look into it. I actually have a copy of this package on my private pypi so I can fix the version no problem.
