### ISSUE TITLE
Missing documentation for version syntax

### ISSUE THREAD

**Issue by num46664** [python-poetry/poetry#4536]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Cannot find official documentation for syntax used in `[tool.poetry.dependencies]` in `pyproject.toml`. Is this inherting some well known standard documented elsewhere? The most helpful resource I have found is [this SO post](https://stackoverflow.com/a/54720073/3504732), Which seems to be accurate as far as I have found, but references two pieces of documentation that are no longer accessible. Where is the official description of this syntax?

**Comment by simonrouse9461** [comment]
Are you referring to this? https://python-poetry.org/docs/dependency-specification/

**Comment by steve-mavens** [comment]
I always find that by web searching for it, which works only because I already know it exists.

https://python-poetry.org/docs/basic-usage/ links to it under "Version constraints", but not under "Specifying dependencies", which is the first place on that page that a non-exact constraint appears. Personally I think poetry docs readers are likely to be extremely impatient: I'm looking for one piece of information to make a specific change to my project, and will leave as soon as I find it. So more links would be helpful when I've landed in the "wrong" place. But I think the general style of the docs is that you should read the whole page properly, like a tutorial, so maybe it's not appropriate to litter them with links.

**Comment by Secrus** [comment]
Proper links have been provided in comments.
