### ISSUE TITLE
Poetry 1.2.0a2 fails to add `datatest` package

### ISSUE THREAD

**Issue by ajhynes7** [python-poetry/poetry#4546]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Big Sur 11.6
- **Poetry version**: 1.2.0a2

## Issue

Hello, I'm unsure if this issue belongs here or in the Python package in question, so I'm starting here first.

I'm trying out Poetry 1.2.0a2, and getting a failure when I attempt to install `datatest`. This is in a minimal project created by `poetry init` with no other dependencies.

```bash
$ poetry --version
Poetry (version 1.2.0a2)

$ poetry add datatest
Using version ^0.11.1 for datatest

Updating dependencies
Resolving dependencies... (0.0s)

  InvalidVersion

  Invalid PEP 440 version: '2.6.'
  
  The following error occurred when trying to handle this error:

  ...

  ValueError

  Could not parse version constraint: >=2.6.*
```

I found this in the `setup.py` of the `datatest` repo:

```python
python_requires='>=2.6.*, !=3.0.*, !=3.1.*',
```

So I think that `>=2.6.*` is incorrect syntax, and it should be `>=2.6`. But this package is able to be installed when using poetry `1.1.10`. So I'm not sure if this has to be fixed in `datatest` or in `poetry`.

**Comment by finswimmer** [comment]
Hello @ajhynes7,

as you guessed `>=2.6.*` is wrong. But because pip doesn't reject it by accident and fixing it there will take a long time (see: https://discuss.python.org/t/pep-440-wildcard-usage-in-comparison-clause/10045) we decided to work around it. This workaround is already in master (https://github.com/python-poetry/poetry-core/pull/186) but not released yet.

fin swimmer 

Relates to https://github.com/python-poetry/poetry/issues/4176

**Comment by ajhynes7** [comment]
Ok, thank you!
