### ISSUE TITLE
poetry 1.1 and forward compatibility with pyproject.toml using groups

### ISSUE THREAD

**Issue by pmav99** [python-poetry/poetry#4628]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: linux
- **Poetry version**: 1.2.0a2

## Issue

A pyproject.toml that is using "groups" is not parse-able by poetry<1.2 and results in a traceback. Displaying a message explaining that you should update poetry will probably improve the UX.

Not really sure if I should open this here on the poetry-core repo.

## Reproducer

*using poetry >=1.2*:
``` bash
poetry init -n
poetry add --group dev pytest
```

*using poetry < 1.2*:
``` bash
poetry install
```
results in: 

```
  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  
  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
```

**Comment by ElPiloto** [comment]
Just adding in some info on how I also hit this issue.  From a google search, it's easy to land on the [dependency groups doc](https://python-poetry.org/docs/master/managing-dependencies/).  From there I editted my pyproject.toml file to try to use groups.  This gave me an error which I eventually realized was due to `poetry < 1.2`.  Obviously this came about because I was on `docs/master` instead of `docs`, but I think the dependency groups doc should also mention that it requires `poetry >= 1.2`
