### ISSUE TITLE
[Feature] Poetry needs a reproducible install for itself

### ISSUE THREAD

**Issue by awilkins** [python-poetry/poetry#4689]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When installed, Poetry installs the latest available versions of packages in it's dependency graph.

This has lead to multiple occasions where even when installing a specific version of the Poetry client, differences in the installed libraries have lead to an inconsistent experience.

- e.g. #4523
   - which was caused by ongoing releases in `poetry-core` deprecating support for `md5` hashes
- e.g. #4688 
   - which was caused by an update to `cachecontrol`

It's quite ironic for a tool which promotes reproducible builds through the use of a lockfile that it should suffer from breakages caused by installing itself via `pip`.

Given the purpose of Poetry (and `poetry-core`), it's very likely to be installed and used in a CI pipeline, where stability and reliability are strong concerns. I humbly submit that installing Poetry and `poetry-core` should be a reproducible act for a given version number.

Suggest that this may be achievable by (preferring the first)

- Having a `poetry build` mode that outputs a `setup.py` with frozen dependency specifications based on the lock file
   - and using this mode for subsequent releases of `poetry` and `poetry-core`
- Using the output of `pip freeze` for `install-poetry.py` instead of
```python
        if self._git:
            specification = "git+" + version
        elif self._path:
            specification = version
        else:
            specification = f"poetry=={version}"

        subprocess.run(
            [str(python), "-m", "pip", "install", specification],
```

**Comment by tom-bowles** [comment]
We deploy our poetry-developed applications by first installing a requirements.txt that we generate from the lock file using `poetry export`. Then we install the wheel. This gives us dependencies that match the lock file without requiring poetry on the deployment machine.

I am in the process of writing a custom install script for the users I support that does the same thing for poetry itself, because we have no choice but to pin both poetry and poetry-core due to a series of releases that are severely broken on Windows (please could somebody give my one-line PR https://github.com/python-poetry/poetry/pull/4682 some love?). Until I complete this custom script, our poetry installation process is to:

- Use `install-poetry.py` with the `--version` parameter to install version 1.1.6
- Use `pip3.exe` from in poetry's venv to `--force-reinstall` poetry-core to version 1.0.4

Requirements.txt based pinning of dependencies in the installer would be awesome. An alternative (not saying if it's necessarily better) would be to implement the feature discussed in https://github.com/python-poetry/poetry/issues/2778 and use it for poetry itself.
