### ISSUE TITLE
Allow setting include-system-site-packages = true during venv creation

### ISSUE THREAD

**Issue by garu57** [python-poetry/poetry#4691]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I gave a try to poetry but i found a major drawback.
I'm using WinPython scientific installation that already contains tenth of packages in the base installation, and with those huge installation bases i think the approach should be different.
Since venvs are created with `include-system-site-packages = false`, after `install`, each project venv ends up as huge blob uselessly containing 90% of packages already in the base installation at the same version.
Could you add an option switch to set `include-system-site-packages = true` during venv creation and add the capability to handle that setting?

I mean that i tried to foul it making an install with a toml file without dependencies, changing the setting by hand and then installing with the true toml file.
It indeed install only the really missing packages but then miserably fails in `poetry\lib\poetry\_vendor\py3.7\poetry\core\packages\file_dependency.py:40 in __init__` because probably it's looking locally (into venv) for some file that really is in the installation `site-packages`.

Just in case you object that in this case the isolation would break, i'm aware that in case of update of base installation an update must be run to allow installing possibly older packages into venv.
Thanks, Gabriele

**Comment by finswimmer** [comment]
Hello @garu57,

the current preview release have such in option. See https://python-poetry.org/docs/master/configuration/#virtualenvsoptionssystem-site-packages You can set it globally or only for the current project.

Besides the point that this breaks the idea of a complete isolation of the environment, another point why I don't like this option is that there is a good chance to forget to declare a necessary dependency, because you code works locally due to a package installed in the system-site.
