### ISSUE TITLE
Interested in supporting PEP 665?

### ISSUE THREAD

**Issue by brettcannon** [python-poetry/poetry#4710]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I'm writing to all of the major packaging projects to see if they would be willing to give me a quote of support for PEP 665? For Poetry this could mean two things:

1. Eventually replacing `Poetry.lock` with what the PEP defines.
2. Support for exporting to what the PEP defines.

The current draft and discussion is at https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736 . If Poetry would be interested in stating that the project supports the PEP (in some form), could you please let me know or leave a comment on Discourse?

Thanks!

**Comment by sdispater** [comment]
As the PEP stands, I don't think Poetry can fully support it, either as its primary lock file or via the `export` command. The main issue is that Poetry supports sdists files, directory and VCS dependencies which are not supported by the PEP so that would be a huge regression from a feature standpoint.

Also, the fact that requirements are at the file level in the PEP is contradictory to the design of Poetry which works at the version level, and there is no plan to change that any time soon since it would prove to be a headache from a dependency resolution standpoint.

**Comment by brettcannon** [comment]
> As the PEP stands, I don't think Poetry can fully support it, either as its primary lock file or via the `export` command. The main issue is that Poetry supports sdists files, directory and VCS dependencies which are not supported by the PEP so that would be a huge regression from a feature standpoint.

Supporting sdists in the PEP is [being discussed](https://discuss.python.org/t/supporting-sdists-and-source-trees-in-pep-665/11869/). The expectation, though, is if we leave out of this PEP it will be added in a subsequent PEP.

> Also, the fact that requirements are at the file level in the PEP is contradictory to the design of Poetry which works at the version level, and there is no plan to change that any time soon since it would prove to be a headache from a dependency resolution standpoint.

So that means even if sdists went in you still wouldn't support exporting? I want to make sure I represent your views appropriately in the PEP.

**Comment by sdispater** [comment]
> Supporting sdists in the PEP is being discussed. The expectation, though, is if we leave out of this PEP it will be added in a subsequent PEP.

That means that Poetry won't be able to support until the file format is final and supports sdists and, at least, VCS packages.

> So that means even if sdists went in you still wouldn't support exporting? I want to make sure I represent your views appropriately in the PEP.

Exactly. The `export` command of Poetry exports the information present in the `poetry.lock` file into another format. That means that this other format should support the same set of package specification as Poetry's otherwise users would lose information and packages.

**Comment by brettcannon** [comment]
Thanks for the feedback. I recorded it in the PEP at https://github.com/python/peps/commit/6bbde299e60d494a2b5b7822deab8474cd8312b6 and also [stated it on the topic at discuss.python.org](https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736/92?u=brettcannon).
