### ISSUE TITLE
Poetry 1.1.12: Missing 3.10 _vendor folder

### ISSUE THREAD

**Issue by IceN9ne** [python-poetry/poetry#4846]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.0.1
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
The release for 1.1.12 darwin found [here](https://github.com/python-poetry/poetry/releases/download/1.1.12/poetry-1.1.12-darwin.tar.gz) is missing the 3.10 `_vendor` folder.  1.1.11 had this folder.

**Comment by neersighted** [comment]
Looks like it was because of https://github.com/python-poetry/poetry/commit/11ff0630e8e7dd6c685296b00e304fcc39bdd2f8. We'll have to re-add Python 3.10 to the build and cut a `.13` release.

cc @abn

**Comment by bryanforbes** [comment]
Is there a way we can get a new release soon with this fixed? This is a pretty big issue.

**Comment by fredrikaverpil** [comment]
What implications does this bring?
I've got poetry 1.1.12 "in production" with Python 3.10 on Linux and in development on macOS without any issues.

**Comment by IceN9ne** [comment]
After some testing, this seems to only affect poetry when installed with `get-poetry.py`.  If installed with this manor (still the method in the docs at this moment), when you attempt to run poetry with 3.10 as the active python, it'll fail with:

    ModuleNotFoundError: No module named 'cleo'

Since there's no `_vendor` directory for 3.10, it doesn't have the necessary modules to run.   I've had issues getting `install-poetry.py` to work, so I was waiting for 1.2 to release before making the switch, however I just uninstalled poetry and reinstalled with the newer:

    curl -sSL https://install.python-poetry.org | python3 -

And after installing this way, everything works fine.  I uninstalled and went back to the `get-poetry.py` and  confirmed that it broke again.  Looks like the workaround is to use `install-poetry.py`

**Comment by Oh-Turry** [comment]
Thanks!

**Comment by Oh-Turry** [comment]
If you are using powershell windows or the new windows 11 powershell you can run the command
`-Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -`
like sir IceN9ne mentioned above!

**Comment by BD103** [comment]
I found a temporary solution for Windows users. I have both Python 3.9 and 3.10 on my computer. I opened up `C:\Users\myuser\.poetry\bin\poetry.bat` and edited the file to be:

```bat
@echo off

py -3.9 "%USERPROFILE%\.poetry\bin\poetry" %*
```

I hope this helps someone else. 😄

**Comment by tfishr** [comment]
For Windows, choosing which of the two workarounds to use depends on what you want.

- Using the `install-poetry.py` installer will create a poetry.exe file in the user Python scripts directory, but that directory is not usually added to PATH so you have to do that part yourself. But poetry.exe works with Python 3.10 so that's nice.
- Using the `get-poetry.py` installer will create a poetry.bat in the .poetry\bin directory which you can edit yourself. Just change that file to use Python 3.9 as BD103 shows above. This is the easier method since `get-poetry.py` also fixes up your PATH for you whereas `install-poetry.py` does not, probably because its directory isn't poetry-specific.

The current behavior makes it appear to new users with Python 3.10 that Poetry does not work on Windows, so this really ought to get fixed soon. People going to python.org for the first time are downloading Python 3.10 then they go to python-poetry.org and are told to use get-poetry.py to install poetry, which leads them on a rabbit hole ending here. This is sub-optimal.

**Comment by makeworld-the-better-one** [comment]
Experienced this on Arch Linux as well, with Python 3.10. The solution from @IceN9ne [above](https://github.com/python-poetry/poetry/issues/4846#issuecomment-988806589) works.

**Comment by neersighted** [comment]
The 1.12 release files have been fixed and should now function on 3.10. :tada:
