### ISSUE TITLE
Remove packages not used in the project

### ISSUE THREAD

**Issue by antaradas94** [python-poetry/poetry#4879]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be really helpful if there was possibly a way to know which packages are no more in use in the project, but exists in my lock or toml file.
May something like this already which i am not aware of. But if not it would be really great to keep track of all dependencies used in the project, specially one which uses a lot of packages.
Thanks

**Comment by celian-garcia** [comment]
Hello, I was searching for something like this as well.
Duplicates of this ? https://github.com/python-poetry/poetry/issues/4135

So far I found pipreqs but work on requirements.txt https://github.com/bndr/pipreqs

**Comment by nbertram** [comment]
You can generate a requirements.txt file to use with pipreqs from Poetry. This kind of workflow:

```bash
poetry export -o requirements.txt.ref
poetry run pipreqs --diff requirements.txt.ref .
rm requirements.txt.ref
```

Also worth noting pipenv has this functionality with `pipenv check --unused`, so if poetry wanted inspiration for an algorithm it's there...

**Comment by chanansh** [comment]
> 

how do you turn the new "pruned" req back to poetry?

**Comment by antaradas94** [comment]
> 

This sounds like a good workaround for now 😅

**Comment by antaradas94** [comment]
> > 
> 
> how do you turn the new "pruned" req back to poetry?

I think i did not understand your question completely. Can you elaborate?

**Comment by chanansh** [comment]
@nbertram has suggested some workaround using pipreqs but it's not clear how to bring the new pruned req back to poetry

**Comment by nbertram** [comment]
In my case that was manual, I got a list out of pipreqs of things the project wasn't using, then `poetry remove`'d them.

I don't know you'd want anything _too_ automated for this, because some deps certainly require a deeper consideration before removing, especially if they're imported in a non-traditional way and/or are an optional dependency of something you have installed and are conditionally imported to provide functionality you need.

**Comment by mkniewallner** [comment]
Closing this issue, since it has been answered in https://github.com/python-poetry/poetry/issues/4135#issuecomment-1002460429.

With the upcoming release of Poetry 1.2, this could be made into [a plugin](https://python-poetry.org/docs/master/plugins/) though, to avoid cluttering the CLI, since this would be a pretty big feature to maintain.
