### ISSUE TITLE
(🎁) Abillity to constrain transitive dependencies

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#4991]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

In Gradle you can constrain transitive dependencies [like this](https://docs.gradle.org/current/userguide/dependency_constraints.html):
```kt
dependencies {
    implementation("org.apache.httpcomponents:httpclient")
    constraints {
        implementation("org.apache.httpcomponents:httpclient:4.5.3") {
            because("previous versions have a bug impacting this application")
        }
        implementation("commons-codec:commons-codec:1.11") {
            because("version 1.9 pulled from httpclient has bugs affecting this application")
        }
    }
}
```

In Poetry if I want to constrain a transitive dependency I have to specify the dependency as a direct dependency.

There are several advantages and motivations to specifying constraints over direct dependencies.

I would like to be able to specify constraints, maybe something like:
```
[tool.poetry.dependencies]
setuptools = { version: "60.2.0", constraint = true }
```

**Comment by KotlinIsland** [comment]
pip supports constraints https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-c

**Comment by KotlinIsland** [comment]
You can kinda get some transitive dependency functionality if you mark the dependency as `optional` and don't put it in an extra:
```py
[tool.poetry.dependencies]
setuptools = { version: "60.2.0", optional = true }
```

Or maybe make a "constraints" group:
```py
[tool.poetry.group.constraints]
optional = true

[tool.poetry.group.constraints.dependencies]
setuptools = "60.2.0"
```

But this isn't a full form solution.

**Comment by neersighted** [comment]
Because Python packaging is flat, Poetry has always taken the stance that if you care about a transient dependency at all (version, source, etc) it's now a top-level dependency, even if you don't import a module in that dependency directly.

I doubt we'll be revisiting that decision anytime soon, and for those that object, the pattern above with optional groups is supported/offers another path.

**Comment by KotlinIsland** [comment]
> You can kinda get some transitive dependency functionality if you mark the dependency as optional and don't put it in an extra

> the pattern above with optional groups is supported/offers another path.

The optional marker without an extra doesn't seem to make it optional in pip's eyes, see #7787

**Comment by jonapich** [comment]
Recently, a transitive dependency upgrade happened that created a conflict and even broke past setups that embraced "best practices" in pinning dependencies:

https://github.com/open-telemetry/opentelemetry-python/issues/3382

This kind of bug means that the current working build stopped working, as well as most/all previous builds.

On the same day, we also had problems with 2 top-level dependencies (boto3-stubs and click) that were marked as `^1.26.0` and `^8.1.2` respectively in our pyproject.toml file. Click's 8.1.4 has an issue with types vs mypy and boto3-stubs has a bunch of `.postN` transitive dependencies that appeared; one of them fails.

Since this is a CLI app and not a library that you're expected to import, we want to ensure to pin transitive dependencies for `pip` users so that this doesn't happen anymore in the future.

Based on this issue and poetry's stance on this, it sounds like my use case falls out of poetry's reach, even more so since `poetry export` excludes transitive dependencies.
