### ISSUE TITLE
Deprecate Python 3.6

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#4997]
Python 3.6 [has reached end of life](https://devguide.python.org/devcycle/#end-of-life-branches) last month on December 23rd, 2021.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Since Python 3.6 support has officially ended, 3.6 compatibility can be removed throughout the codebase (including CI, docs)

**Comment by finswimmer** [comment]
Hello @tony,

we've discussed this already within the Poetry team and everyone likes to drop python3.6. According to [pypistats](https://pypistats.org/packages/poetry) there seems to be ~5% that are still using python3.6. This is why we haven't made a final decision until now.

fin swimmer

**Comment by tony** [comment]
@finswimmer Okay if I make a PR for this?

**Comment by tony** [comment]
@finswimmer Should we keep this issue open for https://github.com/python-poetry/poetry-core/pull/263 and https://github.com/python-poetry/install.python-poetry.org/pull/11?

poetry-core's issue tracker redirects back to poetry's: https://github.com/python-poetry/poetry-core/issues/new/choose

**Comment by markus-oberhumer** [comment]
Chiming in late, but are there any *technical* reasons for not supporting Python 3.6 any longer?

Red Hat Enterprise Linux 8 (RHEL8) and all it's clones (like Alma Linux 8, Rocky Linux 8) use Python 3.6 and will be supported until May 2029 (and therefore will get fixes / backports from Red Hat), and as this is a really widespread Linux distribution this change does affect millions of servers.

**Comment by tony** [comment]
@markus-oberhumer I think the next step would be to raise this concern in a new issue (referencing we had here)

**Comment by finswimmer** [comment]
Hello @markus-oberhumer,

we are simply not enough people to support dead python versions. It's time consuming to work around things that doesn't work in older python versions. Furthermore it holds us back to improve poetry if we cannot use new python features.

We didn't write it anywhere until now, but between the maintainers there is an agreement, that we will promise to support a python version until it's end of life. After that we can drop the support at any time.

fin swimmer

(Personal opinion: The date when the end of life of a software is reached, doesn't mean "start transition", it means "end of the transition period")

**Comment by markus-oberhumer** [comment]
@finswimmer I fully get your point - just wanted to make sure you are aware of the consequences, esp. as there seem to be no real technical reasons for this decisions ATM.

**Comment by abn** [comment]
Just to add to what @finswimmer already mentioned, the primary motivator here is to reduce the maintanence burden imposed by keeping features working in older versions of Python.

While I understand that there is LTS offerred by various distribution vendors for Python 3.6 and even 2.7, this happens due to resources being allocated specifically for this task, ie by the likes of Red Hat. The drop of support here only relates to the runtime version of Poetry and not the version of Python environments Poetry manages. And also consider that these distributions also provide [newer versions of Python](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python) to be installed alongside system default versions.

As for technical rationale, there are a few projects within Poetry's dependency chain that have dropped support for older Python versions. So, we can either keep them locked to older (and unsupported) versions or try maintaining/backporting fixes and improvements. That is a, very deep rabbit hole. And if this level of support is required by someone, I'd suggest that you pay a vendor. Since Poetry 1.1 versions still support these versions of Python, a vendor could in theory backport fixes/improvements to a supported fork.
