### ISSUE TITLE
[BUG]: poetry add pycaret[full] does not complete

### ISSUE THREAD

**Issue by phdwight** [python-poetry/poetry#5065]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora Linux 35 (Workstation Edition)
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
when issuing the command poetry add pycaret[full], it will just keep on saying "Resolving dependencies..." I have stopped the install after observing it for over an hour. when using pip install pycaret[full] the operation completes successfully.

**Comment by dimbleby** [comment]
Solving for `poetry add pycaret[full]` with an empty cache took about 6 minutes for me and then installed 316 (!) packages.

Hard to say whether what has changed is poetry, or the dependency tree out in the world, or the broadband speed of the person doing it.

Anyway, I don't see anything actionable here.

**Comment by mkniewallner** [comment]
Agree, it took 4m30s and a half on my side with, I must say, a pretty fast Internet connection on Poetry `1.2.0b2`.

While this is pretty slow, I believe this is expected given the number of packages that need to be resolved, so I'm gonna close this.
What could help is testing the command on Poetry [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2), since there may be improvements on the dependencies resolution that could speed up dependencies resolution.
