### ISSUE TITLE
(🎁) Provide a command to generate `install-poetry.py` scripts in the project directory

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#5071]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I see that the Poetry project contains `install-poetry.py` and `get-poetry.py` scripts at the top level, I think it would be based if my Poetry projects had the same thing so that people working on it could easily install Poetry. I don't want to manually deal with updating this script so could you please provide a mechanism to generate and maintain this script.

Gradle has a similar feature called the Gradle wrapper, which is generated with the `wrapper` task.

**Comment by rszamszur** [comment]
> I think it would be based if my Poetry projects had the same thing so that people working on it could easily install Poetry.

Don't get me wrong, but I think it's up to developers/maintainers to ensure project reproducibility. You can use all amazing tools like Poetry to help you with that. But in the end, it's up to you how a project is built, installed, distributed, etc. A command for generating `install-poetry.py` which probably would download it from git underneath, seems redundant. You can easily embed this into your build/install process.

An example from one of my make install scripts for installing project + Poetry:
```shell
#!/usr/bin/env bash

if [ -n "$DEBUG" ]; then
  set -x
fi

set -o errexit
set -o nounset
set -o pipefail

PYTHON="${PYTHON:=NOT_SET}"
if [[ $PYTHON == "NOT_SET" ]]; then
  if command -v python3 &> /dev/null; then
    PYTHON=python3
  elif command -v python &> /dev/null; then
    PYTHON=python
  else
    echo "[install] Python is not installed."
    exit 1
  fi
fi

PYTHON_VERSION=$($PYTHON -V 2>&1 | grep -Eo '([0-9]+\.[0-9]+\.[0-9]+)$')
if [[ ${PYTHON_VERSION} < "3.7.0" ]]; then
  echo "[install] Python version 3.7.0 or higher is required."
  exit 1
fi

POETRY_HOME="${POETRY_HOME:=${HOME}/.poetry}"
POETRY_VERSION="${POETRY_VERSION:=1.1.12}"
if ! command -v "$POETRY_HOME"/bin/poetry &> /dev/null; then
  echo "[install] Poetry is not installed. Begin download and install."
  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/1.1.12/get-poetry.py | POETRY_VERSION=$POETRY_VERSION POETRY_HOME=$POETRY_HOME $PYTHON -
fi

POETRY_INSTALL_OPTS="${POETRY_INSTALL_OPTS:="--no-interaction"}"
echo "[install] Begin installing project."
"$POETRY_HOME"/bin/poetry install $POETRY_INSTALL_OPTS
```

This script isn't ideal but should get the job done. There is plenty of room for customization via environment variables. And if you don't want to update the `get-poetry.py`, just point to the master branch: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py for the latest, or use https://install.python-poetry.org, which I assume does exactly the same but for `install-poetry.py` (BTW `get-poetry.py` will be deprecated since 1.2.0). Last but not least, this should be easier for users as well. Run `make install` and you're done.

Hope this helps.

**Comment by KotlinIsland** [comment]
What on earth is `make`.

But yeah, this issue is pretty dumb now that I think about it completely redundant to #4988, which is a way more comprehensive and useful feature request.

Thanks for the response!
