### ISSUE TITLE
package.extras is not reproducible

### ISSUE THREAD

**Issue by ali5h** [python-poetry/poetry#5125]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- ubuntu 20.04
- poetry 1.1.12
- `pyproject.toml`
```
[tool.poetry]
name = "hdfs-test"
version = "0.1.0"
description = ""
authors = ["test"]
[tool.poetry.dependencies]
python = "^3.8"
apache-airflow = "^2.2.3"
[tool.poetry.dev-dependencies]
pytest = "^5.2"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
one of the entries in `package.extras` for `apache-airflow` in `poetry.lock` file is
```
"apache.webhdfs" = ["hdfs[dataframe,avro,kerberos] (>=2.0.4)"]
```
The `hdfs[dataframe,avro,kerberos]` part is not reproducible and on `poetry update` the order of its extras changes (i.e it becomes `hdfs[avro,dataframe,kerberos]`)

**Comment by finswimmer** [comment]
> one of the entries in package.extras for apache-airflow is

You are talking about the resulting `poetry.lock` file for the `pyprject.toml` above?

**Comment by ali5h** [comment]
yes

**Comment by cpcloud** [comment]
I think this is related to the fact that `extras` are stored in-memory using a `frozenset`, the ordering of which is arbitrary.

I also have this issue, and the current workaround isn't great: I have to set `PYTHONHASHSEED` when doing operations that may affect the lock file.

This makes it hard for contributors to contribute because they have to know to do this when changing things related to `poetry`.
