### ISSUE TITLE
Virtualenvs are stored in often-cleaned directory on Macs

### ISSUE THREAD

**Issue by piankma** [python-poetry/poetry#5215]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.2.1
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not needed

## Issue
Poetry venvs are by default stored in ~/Library/Caches/pypoetry/virtualenvs on my machine. This is a location commonly cleaned by most of major system cleaning software.
My proposition is to store them in Application Support directory.

**Comment by davehowell** [comment]
Why not just configure it however works for you, by running `poetry config virtualenvs.path` see the docs it's the exact example they give https://python-poetry.org/docs/configuration/#listing-the-current-configuration 

No need to change defaults for everyone. I think you should close this issue - given the 1000+ other issues the maintainers aren't going to prioritize it especially when the behaviour is already customizable.

Personally I use a poetry.toml file with the following contents, because I like the venvs in my project folders:

```
[virtualenvs]
create = true
in-project = true
```

**Comment by piankma** [comment]
Sure, i can reconfigure that - but there are better places on macOS to store that, like I've said above.
Don't consider this as some priority. This is just a proposition. If there would be some agreement from maintainers i could even implement that.
And thanks for the tip with `in-project` parameter, i also like to store them in project directory.

**Comment by BSVogler** [comment]
I agree that the Cache dir is rather unusual. I was worried that I will lose my installation when the cache is cleared so I moved the directory, which was unfortunately not a straightforward experience.

I think "Application Support" is more fitting.

**Comment by dimbleby** [comment]
duplicate #3346

**Comment by Secrus** [comment]
Closing as duplicate
