### ISSUE TITLE
Python >3.7 should skip install `pathlib`, otherwise will be failed when existing package depends on `pathlib` 

### ISSUE THREAD

**Issue by zen-xu** [python-poetry/poetry#5293]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

latest `setuptools` add a new vendor `importlib_meta` which used `pathlib`.

If my dependency depends on `pathlib`, poetry will still try to install it. But I don't know why `setuptools` try to use the `pypi pathlib` rather than `built-in pathlib`, which `PosixPath` has no attribute `read_text`.

![origin_img_v2_64ebba27-6050-4183-850c-4511fc57311g](https://user-images.githubusercontent.com/38552291/157434176-9bfc496f-cadd-456a-8ab5-d2959a2b3413.PNG)

**Comment by finswimmer** [comment]
Hello @zen-xu,

in python there cannot be two different version of a package with the same `import` path. What ever is loaded first wins.

If I understood correct your project uses the `pathlib` version available on pypi. This package is unmaintained and the last version is more than 7 years old. Since python3.4 `pathlib` is a build-in.

If you really need to support python versions that have reached its end of life, you can add a [constraint to the pyproject.toml](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) to say that this is only needed for specific python versions, e.g.:
```
[tool.poetry.dependencies]
pathlib = {version = ^1.0.0", python = "<=3.4"}
```

**Comment by zen-xu** [comment]
but the pathlib is the dependency of one of my dependency package

**Comment by finswimmer** [comment]
Than you have at least two options:

1. Contact the maintainer of this dependency, that they can add the python restriction to the pathlib dependency.
2. Add the restriction to your package as shown above. Poetry will than drop this dependency for python >3.4 as well.

**Comment by zen-xu** [comment]
Hi @finswimmer, I tried option 2, but the poetry still installed `pathlib` even if I specified `pathlib = {version = "^1.0.0", python = "<=3.4"}`

**Comment by finswimmer** [comment]
Ah, sorry I was wrong with it. If you specify `pathlib = {version = "^1.0.0", python = "<=3.4"}` you are actually saying, that the code of the project needed this for python <=3.4. But of course if a dependency claims it needed it for a broader range it must be installed anyway.

So, you have to either contact the maintainer of this dependency or evaluate what alternative, more recent package can be used. What is the dependency that needed `pathlib`?

**Comment by zen-xu** [comment]
Ok
