### ISSUE TITLE
black pre-commit hook broken

### ISSUE THREAD

**Issue by anthonymichaelclark** [python-poetry/poetry#5375]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS 12.3
- **Poetry version**:  master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [here](https://gist.github.com/anthonymichaelclark/f5ed71b1cdef34cd07717f0aa09c8cea)

## Issue

Black was broken -- and quickly fixed -- today by the release of click 8.1.0 per [this issue](https://github.com/psf/black/issues/2964). rev 21.1.0 in [pyproject.toml](https://github.com/python-poetry/poetry/blob/67d378915783725d3d51cb5939770663be51ea0f/.pre-commit-config.yaml#L74) is also broken. Running `pre-commit run --all-files` results in the tell-tale error:
```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/anthonyclark/.cache/pre-commit/repokea4kflj/py_env-python3.10/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/anthonyclark/.cache/pre-commit/repokea4kflj/py_env-python3.10/lib/python3.10/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/Users/anthonyclark/.cache/pre-commit/repokea4kflj/py_env-python3.10/lib/python3.10/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/Users/anthonyclark/.cache/pre-commit/repokea4kflj/py_env-python3.10/lib/python3.10/site-packages/click/__init__.py)
```

**Comment by charlottegiseleweil** [comment]
Hi [branchvincent](https://github.com/branchvincent) -

I have exactly the same issue as [anthonymichaelclark](https://github.com/anthonymichaelclark). 

I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version: Poetry (1.1.13)
 MacOS 10.15.7
[my pyproject.toml ](https://gist.github.com/charlottegiseleweil/5e82deceaa59cc10dd984440c364451c).

I see you've closed this issue here - but I'm still getting the same error here when running `poetry run pre-commit run --all-files`

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/charlotteweil1/.cache/pre-commit/repoqg3mkzrn/py_env-python3.9/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/charlotteweil1/.cache/pre-commit/repoqg3mkzrn/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1372, in patched_main
    patch_click()
  File "/Users/charlotteweil1/.cache/pre-commit/repoqg3mkzrn/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/Users/charlotteweil1/.cache/pre-commit/repoqg3mkzrn/py_env-python3.9/lib/python3.9/site-packages/click/__init__.py)
```

Thanks in advance!

**Comment by finswimmer** [comment]
@charlottegiseleweil: I guess you have checked out the `1.1` branch and not the `master` branch. There we haven't update `black`. At the moment we have no plans for another 1.1 release. Unless there is something really critical there will be no more changes in that branch.

**Comment by branchvincent** [comment]
@charlottegiseleweil, it looks like you're experiencing issues with your own pre-commit hooks in https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats, right?

this issue is not related to `poetry`, we just happened to experience it as well. the easiest solution would be to update your `black` pre-commit hook to the latest version in [`.pre-commit-config.yaml`](https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats/blob/develop/.pre-commit-config.yaml). note that [`pre-commit autoupdate`](https://pre-commit.com/#pre-commit-autoupdate) will do that for you
