### ISSUE TITLE
Can't make poetry build wheels for dependency installs

### ISSUE THREAD

**Issue by riconnon** [python-poetry/poetry#5432]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Alpine Linux 3.15
- **Poetry version**: poetry-core 1.0.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/riconnon/0c1d2883bb8d0d44abae1a7196ebe2a6

## Issue
When using the above `pyproject.toml` and installing using `pip install .` I see that `gprof2dot` is installed using `setup.py install` rather than building a wheel, with the following message:
```
#25 30.40 Using legacy 'setup.py install' for gprof2dot, since package 'wheel' is not installed.                                     
```

I was hoping that including `wheel` in the `requires` under `[build-system]` would mean that `wheel` was available at this time and `pip` would build wheels, leading to better use of the local `pip` cache.

**Comment by abn** [comment]
Do not think the issue here has to do with poetry as poetry only tells pjp what dependencies are. Then pip installs them based on the available source.

You could try the following as an initial debug step.

1. `pip install --upgrade pip` before install.
2. Try forcing `--use-pep517`. Although this should be the default already.

All that said this could be because the default PEP 517 build environment created by pip does not contain the wheel package. Note that this environment is unique for each package. Your project's build-system requirements are only relevant when the build happens for your project and not the dependencies.

You could try `pip wheels && pip install *.whl`.
