### ISSUE TITLE
Poetry does not install newest compatible version

### ISSUE THREAD

**Issue by maxnoe** [python-poetry/poetry#5448]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux, Ubuntu 20.04
- **Poetry version**: `Poetry version 1.1.13`

## Issue
According to the documentation, `poetry update` should install the newest compatible version of a dependency.

However, using this pyproject.toml file:
```
[tool.poetry]
name = "astropy_test"
version = "0.1.0"
description = ""
authors = ["Maximilian Nöthe <maximilian.noethe@tu-dortmund.de>"]

[tool.poetry.dependencies]
python = "^3.7"
astropy = ">=4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

and using python 3.8, this still installs  only astropy 4.3 (which is the last version compatible with 3.7) and not 5.0 (which is the current version, i.e. the latest compatible version for python 3.8).

Similarly, as a transitive dependency, only numpy 1.21 is installed (last version supporting 3.7) instead of 1.22 (current version for python 3.8).

This is unexpected and especially for a library not the desired behavior. I want to keep supporting users of python 3.7 but want to allow people on python 3.8 to use the latest numpy / astropy release.

Is this possible using poetry?

**Comment by finswimmer** [comment]
Hello @maxnoe,

the behavior is expected, because poetry doesn't care about your current environment when it's resolving the dependencies: https://python-poetry.org/docs/master/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

If you now that your package work with `astropy` 4.3 and 5.0 you can use [constraints](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) like this:

```toml
[tool.poetry.dependencies]
python = "^3.7"
astropy = [
    {version = "^5.0", python = "^3.8"},
    {version = "^4.3", python = "<3.8"}
]
```

fin swimmer

**Comment by maxnoe** [comment]
No, I cannot, since this would forbid using stripy 4.3 with python 3.8
