### ISSUE TITLE
How do I use poetry as a module?

### ISSUE THREAD

**Issue by tddschn** [python-poetry/poetry#5467]
I want to use poetry in my python code to automate things, but I can't find the [doc](https://python-poetry.org/docs/) on how to do this.

Is this usage discouraged for general use, or just undocumented on the doc site?

**Comment by abn** [comment]
While it is not actively discouraged, it is not a use case that is officially supported. The only API that is officially supported at present, is the CLI. This does mean everything under it can be volatile even though we try not to make that a habit. 

You can programmatically call the CLI api, however these are not always the friendliest way to do it since you need to be aware of poetry's internals, eg: command installers etc.

All that said, if there is sufficient demand the status quo can change. I'd recommend opening a discussion in the community, maybe suggest the use cases being addressed and see if there is general interest in there being an API for cases where Poetry is called from other codebases. 

The simplest solution I can think of is to add `poetry.api.run(command, argv)` or similar that dispatches the command for you.

**Comment by tddschn** [comment]
Thank you for your reply!
