### ISSUE TITLE
Infinite loop when resolving deps (normalization problem)

### ISSUE THREAD

**Issue by karlb** [python-poetry/poetry#5474]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Linux 5.10.0-10-amd64 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
- **Poetry version**: 1.2.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/karlb/4ef34bd22cbd39dde7a7d8aa3bd6ca22

## Issue
When running `poetry update`, the `Resolving dependencies...` step is stuck in what seems to be an infinite loop. It runs for a long time (>1000s) until I am force to kill it, because it starts to use excessive amounts of memory (>8GB).

The problem only happens when dependencies are involved where the declared dependency name differs from the PyPI package name in ways allowed by the package name normalization. In the gist, the problematic dependencies are `zope-interface` (`zope.interface` on PyPI) and `zope-event` (`zope.event` on PyPI). These are transitive dependencies of the "bug" project included via the `raiden` dependency.

This seems to be related to https://github.com/python-poetry/poetry/issues/3365 and https://github.com/python-poetry/poetry/issues/3200 and a potential duplicate of these. However, the case is slightly different, since the problematic dependencies are not declared in the package managed by poetry, but in a dependency (which is not created using poetry). Due to this, I don't see a way to work around this by changing the `pyproject.toml` as done in https://github.com/python-poetry/poetry/issues/3132#issuecomment-1097918063.

**Comment by kenahoo** [comment]
I'm not sure if what I'm seeing is the same thing, but it certainly could be.  I turned on verbose mode with `-vv` and I can see that it's downloading and checking many many pre-release versions of a dependency (because it is declared with `allow-prereleases = true`), which I'm willing to live with, but here's the kicker:

**It gets slower and slower with each version it's checking**.  There are a couple hundred pre-releases it's checking.  When it started checking them it was easily doing 20 versions per second or more; after running for a while it's taking at least 5 seconds per version, and is getting slower and slower.  The behavior seems quadratic in the size of the number of versions it's checking (just a guess).
