### ISSUE TITLE
Bare Git Repo at UNC Shared Drive Filepath

### ISSUE THREAD

**Issue by ConnorSMaynes** [python-poetry/poetry#5493]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

System: latest version of poetry, python 3.10.2, Windows 10 64-bit

I have a bare GIT repo on a shared drive which I need to include as a dependency. I have the following dependency in pyproject.toml:
```toml
[tool.poetry.dependencies]
repo-name = {git="file://drive-name/path/repo-name.git"}
```

When using "poetry build" I get the following error: 
```No file/folder found for package```
"poetry install" seems to silently fail. It does not install the dependency.

In setuptools setup.py I can use the following path and install/uninstall works without issue:
```repo-name@file://drive-name/path/repo-name.git#egg=repo-name```

The documentation seems, as far as I can tell, a little sparse on this scenario.
What am I missing?

**Comment by abn** [comment]
Can you try the fix at #5428? That should resolve this.

**Comment by abn** [comment]
> No file/folder found for package

This one is likely because the project does not define `packages` in `pyproject.toml` and auto discovery fails to find your package.

**Comment by ConnorSMaynes** [comment]
> > No file/folder found for package
> 
> This one is likely because the project does not define `packages` in `pyproject.toml` and auto discovery fails to find your package.

You were right. I made a copy of the repo to test with and that messed up the package name.

**Comment by ConnorSMaynes** [comment]
The next issue I get is "Invalid git url". This seems to be happening because I am using a hidden folder on Windows.

Changing the PATH regex pattern in "poetry\core\vcs\git.py"
from
```python
PATH = r"[\w\~.\-/\\]+"
```
to
```python
PATH = r"[\w\$~.\-/\\]+"
```
resolves the issue in addition to using 4 slashes after the schema and :

Final filepath looks like: ```file:////<drive-name>/<hidden-folder-name>$/<remaining-path-parts>/<repo-name>.git```

**Comment by abn** [comment]
@ConnorSMaynes the `build-system` setting does not need to be modified, the changes in #5428 only impacts the Poetry frontend, ie. commands like `poetry install`. When you perform `pip install`, `pip` creates a new isolated environments, copies the source from your project into a temporary directory and then calls `poetry-core` to construct the wheel. When it does this, `poetry-core` tries to validate the metadata it has from the `pyproject.toml` files and determines that the `$` in the url is invalid.

As mentioned above, this is a validation done in core. I suspect the issue is, as you pointed out, the use of `$`.  The fix at https://github.com/python-poetry/poetry-core/pull/341 should resolve this.
