### ISSUE TITLE
Extras still don't seem to be installing

### ISSUE THREAD

**Issue by aronchick** [python-poetry/poetry#5604]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:Linux ... 5.15.0-1004-gcp #7-Ubuntu SMP Wed Apr 20 04:26:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- **Poetry version**: poetry             1.1.13
poetry-core        1.0.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/aronchick/3d45f8857debe7d618e867699658107d)

## Issue
No matter how many times I install `poetry install -E azureml`, it won't seem to install.  I looked through the repo, and it's kind of talked about here https://github.com/python-poetry/poetry/issues/4721 but unresolved.

**Comment by abn** [comment]
You need to add those as optional dependencies as well. For example:

```sh
poetry add --optional azureml-core
```

**Comment by abn** [comment]
This will need better documentation I feel.

**Comment by william-richard** [comment]
@abn can you help me understand your suggestion?

Are you saying that if I want the extras defined in a package, I need to look up what dependencies those are and add them as optional installs to my `pyproject.toml`?

**Comment by AliGhahraei** [comment]
@william-richard yes, you need to add every single package from your extras as an optional dependency for it to work. I was also very confused by this until I found @abn's comment because if you don't do it, poetry will just add an empty list to its lock file like this:

```
[extras]
azureml = []
```

That's probably why `poetry install -E azureml` does nothing at all like @aronchick said. I think we definitely need to document this behavior somewhere, but even then I'm wondering if some kind of warning should also be displayed because what happens is not obvious to the user.

**Comment by joamatab** [comment]
I've seen the same issue when i tried transitioning the gdsfactory project to poetry

See branch
https://github.com/gdsfactory/gdsfactory/tree/poetry2

only some extras seem to be added to the release

you can run `make build` and will see the `setup.py` missing many extras there

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/pyproject/#extras seems clear enough, if anyone wants to contribute improvements then they should simply do so

no need to keep this one open
