### ISSUE TITLE
Remove tomlkit regression mitigation

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#5675]
In #5673 we introduced a mitigation for a `tomlkit` regression on Windows. The root cause of this has to be identified, addressed and mitigation addressed.

Mitigation commit: https://github.com/python-poetry/poetry/commit/1d71955b7a0e5c3cbe90a5d30a680af22e575e26

**Comment by radoering** [comment]
Bisected the regression. It's because of sdispater/tomlkit#149. I believe this change falls way too short. Tomlkit now keeps Windows line endings when reading but probably doesn't expect Windows line endings in some parts of the code. Further, if you read a file with Windows line endings, change it and write it back you may get mixed line endings. Even though the change fixes #2993, it makes things a lot worse for toml files with Windows line endings. Not sure, if there is an easy fix. Maybe, we should think about reverting this change in our vendored tomlkit in poetry-core.

**Comment by abn** [comment]
> Maybe, we should think about reverting this change in our vendored tomlkit in poetry-core.

Do not tihnk that is a viable option for a few reasons.

1. The vendored version (in theory) will only impact core's use of tomlkit. Unfortunately, due to an import order inconsistencies Poetry may or may not load the right tomlkit (non-vendored) package.
2. Downstream package maintainers often strip out vendored packages and provide them externally. Since core's vendoring use case is specific to ease of PEP 517 builds, we do not enforce the expectation of vendored package being used.
3. This is a problematic pattern (carrying funcitonal patches), we want to avoid.

**Comment by abn** [comment]
> Further, if you read a file with Windows line endings, change it and write it back you may get mixed line endings (because "\n" used in code are not converted to "\r\n" anymore when writing).

Would replacing our `\n` usages with `nl()` or similar help here? Assuming `tomlkit` detects and is "aware" of the current file's line-ending preferences?

**Comment by radoering** [comment]
Unfortunately, `tomlkit` is not "aware" of any preferences. Since sdispater/tomlkit#149, it just reads the file with line endings as is and inserts new elements with `"\n"` (even if the file only contains `"\r\n"`). If I'm correct, a holistic fix in `tomlkit` to keep `TOMLDocument` consistent would require a lot of effort (since there are many hard coded `"\n"`) and many new tests.

I created a PR so at least `TOMLFile` keeps line endings consistent. In other words, if you dump strings, the line endings in the strings will still be inconsistent, but if you edit a file, line endings stay consistent (if they were consistent before). For testing, I also created a PR in `poetry-core` that patches `TOMLFile` without need for a new `tomlkit` version. (That was quite simple because we already had our own subclass of the original `TOMLFile`.)

We can either wait for a tomlkit version with sdispater/tomlkit#201 (or another fix for sdispater/tomlkit#200) or proceed with python-poetry/poetry-core#403.
