### ISSUE TITLE
Provide checksums for or alt. download method

### ISSUE THREAD

**Issue by portno12** [python-poetry/poetry#5679]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

using `curl  |  sh` is bad from a security perspective and is the primary method noted on https://python-poetry.org/docs/#installation . this gives no way to verify the file people get is "official" or not tampered with. can hashes/checksums be added to the page with a proper warning of the security implications? telling someone to inspect the script is ok, but doesnt tell non-devs what is "right" as far as the file content.

i checked the tarbarlls in the releases and they are just a pile of files. no instructions in them either for proper installation. windows users may also benefit from something like `pyinstaller` being used to make binary releases for that platform.

**Comment by Secrus** [comment]
The link provided in official docs is to the same file that is present in [this repository](https://github.com/python-poetry/install.python-poetry.org), just behind a more friendly link. Tarballs with releases are just sources of Poetry code (bundled code from this repo) from the previous release model. Someone knowing a bit about Python packaging can handle installing that from the source. When it comes to binary or system/distro-specific releases, the team decided against them, since making and maintaining them is just too much effort. 

Also, please refer to this: https://github.com/python-poetry/poetry/issues/5668#issuecomment-1134666654
