### ISSUE TITLE
Inconsistent URL required for `poetry publish` and `poetry add`

### ISSUE THREAD

**Issue by Shadowsong27** [python-poetry/poetry#5957]
Hi folks.

After searching the issues, I locate a relevant thread:

https://github.com/python-poetry/poetry/issues/233

For those who get the "Could not find a matching version of package <my package>" when trying to install from private repo

```shell
$ poetry add my_package 

ValueError
Could not find a matching version of package my_package
```

Try to add `/simple/` to the url of the repo which you have used in `pyproject.toml`:

```toml
[[tool.poetry.source]]
name = "myrepo"
url = "https://my.rul/simple/"
```

That solved the problem for me with AWS CodeArtifact repository. Curiously, during authentication for publishing while setting the `poetry config repositories.myrepo $URL` and `poetry config http-basic.myrepo $USER $TOKEN` I had to use CodeArtifact url WITHOUT `/simple/` at the end.

_Originally posted by @vduseev in https://github.com/python-poetry/poetry/issues/233#issuecomment-769810216_

Any solution to this issue yet?

**Comment by neersighted** [comment]
This is simply an artifact of the fact that the simple API does not have a defined path on the host domain. That is to say, it can occur anywhere, often at a different location than the upload URL. This is one reason that Poetry configures credentials with a name instead of URL (so that they can be shared).
