### ISSUE TITLE
Upgrade from 1.1.13 to 1.1.14 broke pipeline on installation for Windows

### ISSUE THREAD

**Issue by staticdev** [python-poetry/poetry#5979]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows - Github Actions
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [](https://github.com/staticdev/git-portfolio/blob/dependabot/pip/dot-github/workflows/poetry-1.1.14/pyproject.toml)

## Issue
Windows pipeline fails on Github Actions. I am not able to run this locally with -vvv on Windows (I don't have it).
Complete output can be seen in the output of this PR workflow `tests`: https://github.com/staticdev/git-portfolio/pull/717

**Comment by mkniewallner** [comment]
Your issue is not related to Poetry, as can be shown [here](https://github.com/staticdev/git-portfolio/runs/7257716128?check_suite_focus=true#step:9:77):
```console
The conflict is caused by:
    pytest 7.1.2 depends on atomicwrites>=1.0; sys_platform == "win32"
    The user requested (constraint) atomicwrites==1.4.0
```

Issue is https://github.com/untitaker/python-atomicwrites/issues/61, but since then, PyPI admins have restored [old versions](https://pypi.org/project/atomicwrites/#history) (see [this tweet](https://twitter.com/dstufft/status/1545622320789741569)), so re-running your pipeline should work.

**Comment by staticdev** [comment]
@mkniewallner precisely correct. Thank you!
