### ISSUE TITLE
Add support for `__main__.py` to `poetry run` with the current module.

### ISSUE THREAD

**Issue by jheddings** [python-poetry/poetry#5981]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
It would be nice to have support for running a module's `__main__.py` from poetry as if the module were executed using `python -m`.

Currently, as a workaround, we are defining an empty `main()` in `__main__.py` such as:

```python
def main():
    pass
```

Then creating a script like so:

```python
[tool.poetry.scripts]
my_pkg = "my_pkg.__main__:main"
```

Thanks for the consideration!

**Comment by dimbleby** [comment]
What do you want do to that you can't already do?

If I create a project `foo` containing nothing but a `__main__.py`, and install it, and run `python -m foo`... then that `__main__.py` is executed as expected.

**Comment by jheddings** [comment]
As you point out, `poetry run python -m my_pkg` works as expected.  Just looking for a shorthand to get there with `poetry run my_pkg` for my lazy fingers 😬 .

**Comment by dimbleby** [comment]
I think that what you call a workaround is exactly the expected workflow, I dunno if there's appetite to make this particular shortcut.

Maybe it wouldn't be very hard though, the code is [here](https://github.com/python-poetry/poetry/blob/master/src/poetry/console/commands/run.py#L22-#L34), so if you are motivated to submit an MR then no doubt maintainers will take a view.

**Comment by jheddings** [comment]
Great!  Thanks for the pointer...  I'll try to take a look and see if there's a clean way to get there.

**Comment by dimbleby** [comment]
> just to satisfy the tool
I'd quibble: this is just to satisfy you!  

poetry produces a completely standard package for which the standard `python -m package` does exactly what would be expected  It's not unreasonable that to achieve shortcuts on top of that you should expect to do something extra.

**Comment by jheddings** [comment]
Didn't intend to start a quibble, as I said it's probably a matter of preference...  Each developer has their own approach and I'm just looking to see what might be possible or helpful to others.  Poetry does an excellent job of streamlining development, so making a request for new features in that mindset seems reasonable.

Cheers!

**Comment by nmacholl** [comment]
> Probably just a matter of preference, then. I try to keep `__main__.py` pretty clean, so having the empty method seems a bit clunky just to satisfy the tool.

It seems like a reasonable desire for an executable module to be installed as an executable such that the following are equivalent:
```
$ python3 -m mymodule
$ mymodule
```

I would expect this of any project trying to deploy itself as an end-user application since most people unfamiliar with python aren't going to invoke python directly.

**Comment by dimbleby** [comment]
You are confusing "installing a script" with "being a module".

Python projects that deploy as end user applications can and do install scripts, this is supported by poetry-built packages and by not-poetry-built packages.  That's exactly what OP is doing with `[tool.poetry.scripts]`.

This issue is asking for poetry to implement a special case where: if you have created a virtual environment and used poetry to install a project during development then, in addition to the standard things, poetry should allow a shortcut for `poetry run module`.

Frankly, writing that out ten days after I last considered this, it seems less of a good idea.  But if anyone wants to experiment and submit an MR don't let me put you off.

**Comment by jheddings** [comment]
> You are confusing "installing a script" with "being a module".

I think this is where I missed the mark initially...  Generally, I was looking for a shorthand to "execute the current module when it has `__main__.py`"  Still thinking about how to implement this in a reasonable way.

**Comment by nmacholl** [comment]
> Generally, I was looking for a shorthand to "execute the current module when it has `__main__.py`" Just as other petty commands have knowledge of the current module for packaging and the like. How would we feel about `poetry run` (with no arguments) assumes that it runs the current module in a `__main__` fashion?

[tool.poetry.scripts] can still achieve this you might just have to refactor your code a bit. For example:
```
[poetry.tool.scripts]
mymodule = "mypackage.mymodule:__main__"
```
You then need to ensure your module's `__main__` is truly an entry point and calls sys.exit() at the end. Otherwise you'll get an interpreter error. You'd also never want to put any code or classes in `__main__` that would ever need to be imported. It's bad practice to import dunder files anyway and if your main is clean than this should work for you.

**Comment by neersighted** [comment]
Closing this as `poetry run` is just a shorthand for activating the virtual environment, as @dimbleby has explained. Adding 'magic' to it is inconsistent and unexpected -- if you want to enter your project by typing `mycommand`, you should define `mycommand` using `tool.poetry.scripts`.

**Comment by dylan-robins** [comment]
> [tool.poetry.scripts]
> exec_name = "my_package.__main__:__main__"
> ```
> 
> So it works as expected:
> 
> ```
> exec_name
> python -m my_package
> ```


This doesn't work for me:
```toml

[tool.poetry.scripts]
exec_name= "my_package.__main__:__main__"
exec_name_gui= "my_package:gui"
```

The `exec_name_gui` thing works as expected, but `exec_name` itself does not and I get the following error:
```
AttributeError: module 'my_package.__main__' has no attribute '__main__'. Did you mean: '__name__'
```

Would you mind elaborating how your files are structured @arielnmz ?

**Comment by ruckc** [comment]
I can't get "mypackage.__main__:__main__" to work, I get `ImportError: cannot import name '__main__' from 'mypackage.__main__'

Ideally, i'd ask that poetry supports a string without a `:`, and if it finds it, it does the `python -m mypackage` equivalent.
