### ISSUE TITLE
can configuration be done in one yaml file ? then anything that's necessary to python packaging be generated ?

### ISSUE THREAD

**Issue by akharrou** [python-poetry/poetry#6006]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Can there not be a single YAML configuration file for the whole project, and then out of that generate any `.ini`, `.toml`, `.cfg`, etc file that python, pip, or whatever else needs ? and this file would be the single source of truth for version and anything relevant to the project, that's not code ? i.e not having duplicated information anywhere ?

**Comment by clintonroy** [comment]
At least in the Python world, pyproject.toml is the newly standardized, single source of truth. Not everything supports it, but adding yet another configuration file just for poetry would be counter productive. I do not believe there's any interest in the project for using a non standard configuration file. I suggest this request be closed.

**Comment by mkniewallner** [comment]
> and this file would be the single source of truth for version and anything relevant to the project, that's not code

What you describe here is already standardized, and was introduced by [PEP 621](https://peps.python.org/pep-0621/) and [PEP 631](https://peps.python.org/pep-0631/). Not all packaging tools follow those conventions, because it is still fairly new (it predates the creation of Poetry for instance), and it takes time to move to new standards, but this is what most Python libraries now consider "standard", so more and more tools follow those PEPs.

Using a completely different format than what's described in the PEPs for defining project metadata would make Poetry diverge from the standard and would, I believe, not provide any benefit, while making the switch from different tools harder for the users.

**Comment by akharrou** [comment]
If you are worried about being "non-conforming" to PEP, I would suggest perhaps **just providing this as an optional alternative syntax.**

---

yaml is **a syntax that a lot of people already know, use and love, that's human-readable, easy to read, easy to write, and easy to learn**, especially for newcomers.

I understand that PEP is the authority here dictating the standard, but we're all developers here that have real experiences dealing with these technologies on a day to day, and we all have a feel for what we find easier and/or more convenient to use. I would bet that if you asked developers on a whole which they would rather use toml or yaml, [they would choose yaml.](https://gist.github.com/oconnor663/9aeb4ed56394cb013a20)

and regarding interest, if search terms are in anyway representative and predictive of "people's interest", **here's what i found on google trends:**

![image](https://user-images.githubusercontent.com/36056254/178898671-d56ff761-0e7c-4c60-99b1-5c190b4c522c.png)

You already have a wonderful tool that's simplified down the process of managing dependencies and packaging considerably, why not **be the leader** in going towards modern human-friendly syntax for configuration.

i think providing this alternative **would help poetry become more adoptable and make developers' lives easier.**

---

anyways, I'm not insisting on this, it really only is a suggestion, a thought, that came to me as I encountered little errors and frustrations while switching from `setup.py` and the rest, to `.toml`.

**Comment by mkniewallner** [comment]
> @clintonroy, @mkniewallner, if you are worried about being "non-conforming" to PEP, I would suggest perhaps **just providing this as an optional alternative syntax.**

Making this an option would represent a huge work to implement, both in terms of code and design. It would also mean maintaining 2 different syntaxes over time, which clearly is a situation we don't want to be in (Poetry is an open-source project, and most people work on it on their free time, so we have limited resources).

In the eventuality that we were to implement a new syntax, there's a great chance that only a few people would use it, because the mentioned PEPs are considered standard in Python world, and Python developers are now familiar with the syntax of TOML.

Fully switching from `pyproject.toml` to a YAML format is out of the picture, because this is too much of a breaking change for existing users, and there's a fair chance that people would actually **stop using the tool** because of that. This would make us diverge from the well-established standards as well, which is also a situation we don't want to be in. We'll just become "this weird tool that uses YAML for some reasons", while other libraries follow the same standards that make switching between them easier for users.

> i think providing this alternative would help poetry become more adoptable and make developers' lives easier.

Without data to back that, this is all hypothetical. Some people have their quirks with TOML, but for Poetry, I didn't notice a lot of people complaining because they **absolutely** had to use TOML for defining their Python project metadata. And I'm pretty sure that you can find people that don't like YAML and actually prefer TOML, and/or are either happy or are ok with the format suggested by PEP 621.

Now if you are convinced that YAML is the way to go for Python project metadata definition, you still have a few options:
- Write a PEP, but there's an almost 100% chance that it would be rejected, since `pyproject.toml` is a now well-established standard, and it took quite some time before getting there.
- Fork the project to add and maintain support for YAML.
- Write a "proxy" tool that would convert a YAML file holding your project metadata to `pyproject.toml` format that Poetry understands.
- Create your own library from scratch (warning: this is **a lot** of work).

**Comment by Secrus** [comment]
Let me add to that: the fact that YAML is more popular is mostly because popular tools like `docker-compose`, Kubernetes and Ansible. That being said, YAML is just awful in its syntax. See https://noyaml.com/ for some reasons.
