### ISSUE TITLE
`poetry env remove` removes wrong environment

### ISSUE THREAD

**Issue by KDMichaelis** [python-poetry/poetry#6018]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.14

## Issue

I created two poetry environments, `project-tmp-1BotOSEK-py3.9` and `tmp-project-yuY8E-Dp-py3.9`. In my project only the first one is available and activated:
```
$ poetry env list
project-tmp-1BotOSEK-py3.9 (Activated)
```
I am trying to delete the other environment using the absolute path according to the [documentation](https://python-poetry.org/docs/managing-environments/#deleting-the-environments) as follows:
```
$ poetry env remove /home/user/.cache/pypoetry/virtualenvs/tmp-project-yuY8E-Dp-py3.9/bin/python
```
However, this deletes the wrong environment (the activated one) instead:
```
Deleted virtualenv: /home/user/.cache/pypoetry/virtualenvs/project-tmp-1BotOSEK-py3.9
```
I would expect that using the absolute path exactly the specified environment would be deleted instead of the activated one, including any data connected to it (e.g. the entry in `envs.toml`). It actually seems that the entry for the correct (specified) environment was deleted but the wrong (activated) environment is erased instead, leading to inconsistent information in `envs.toml`.
If for some reason it is desired that a virtualenv cannot be deleted from a project where it's not available (or while another one is activated) the command should at least fail when trying to do so.
As a side note, I am using direnv and the command [layout_poetry](https://github.com/direnv/direnv/wiki/Python#poetry) defined in `~/.direnvrc` and called in `.envrc` within my project.

**Comment by dhvcc** [comment]
Are there any steps to reproduce this? I imagine renaming your directory/project and creating a new venv?

**Comment by dhvcc** [comment]
@python-poetry/triage
Hi, I'd like to take on this issue. The solution is pretty easy - just to extract real venv path with something like that `import sys; print(sys.prefix)` and removing it instead of **always** generating venv name from current project.

This issue is easily reproducable:
1. Create a dir `mkdir dir_name` and run `poetry init & poetry install` (remember this venv's path)
2. Go back `cd ..` and rename this directory `mv dir_name dir_name_renamed`
3. Run poetry install, which will create new venv, and then run `poetry env remove` with old venv's path. Poetry will try to remove current venv, not an old one.
This also works for venv not for this project.

Even if the solution is simple I'd still need to understand other code, which is not very clear without comments. We still need to understand whether this feature is simply missing or other code is not working as expected. So, if anybody knows something about this feature - It'd be nice to hear from you.
