### ISSUE TITLE
pyproject.toml cannot be found in version 1.1.14 

### ISSUE THREAD

**Issue by mluired** [python-poetry/poetry#6023]
I am getting an issue in version 1.1.14. It seems that pyproject.toml cannot be found. Is this really fixed in new pre-release?? How should a uninstall the latest version and install the new one?? The update command is also getting errors… 

thanks. 
Regards.

**Comment by Secrus** [comment]
Could you provide more information so one could try and reproduce the error? It would be nice to get your directory structure, your OS, which installation method you used for Poetry and how did you update to the new Poetry version.

**Comment by mluired** [comment]
In my case I am installing capev2 and I am getting the following error 
![Uploading 91F34949-79A9-4B63-91E7-803B2BFAF2D5.jpeg…]()

**Comment by mluired** [comment]
![ABF32F10-EAD2-4B93-B569-26D2736319D0](https://user-images.githubusercontent.com/9395220/179399020-9d28faeb-e411-4848-90f0-226cb4e7e03a.jpeg)

**Comment by mluired** [comment]
In my case I am installing Capev2 which is taking last version of poetry by default and the above error is what I am getting

**Comment by mluired** [comment]
![12D1EDC3-40AF-4296-9D42-342D082B0BB5](https://user-images.githubusercontent.com/9395220/179399125-91e6f4b0-8ef5-4f90-ad48-b36d5681611c.jpeg)

**Comment by mluired** [comment]
This is what I get when I try to update

**Comment by Secrus** [comment]
1. Looks like you installed Poetry via `pip` which is not recommended, since Poetry has to be in its own environment for dependency isolation. 
2. The package you are trying to install is using some sort of custom installation script. In this case, you should skip Poetry (since it won't recognize that you are trying to install a package) and just use `python cuckoo.py`. 

There is not much Poetry can do in this case. You could try installing this package from git repository, but I don't know how it's gonna work without that custom installation script. The original error you reported was due to Poetry expecting to be run in the project directory, not as a standalone script runner.
