### ISSUE TITLE
trivy tool reports vulnerabilites for urllib3 and cryptography packages

### ISSUE THREAD

**Issue by noorul** [python-poetry/poetry#6027]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04 LTS
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

We are using [trivy ](https://github.com/aquasecurity/trivy)scanner for finding vulnerabilities. The tool reports a couple of vulnerabilities.

<img width="1916" alt="Screenshot 2022-07-18 at 3 16 02 PM" src="https://user-images.githubusercontent.com/155376/179489964-a5ab7b2f-96e0-408f-95ef-ebe61b058b1f.png">

**Comment by finswimmer** [comment]
Hello @noorul,

thanks a lot for reporting this. 

If you have installed Poetry with the `get-poetry.py` script, please uninstall Poetry and reinstall Poetry with the new installer: https://python-poetry.org/docs/master/#installation Doing so, will result in the latest available version for the dependencies that can be resolved according to the given version ranges in the `pyproject.toml`.

An update of `urllib3` is unfortunately not possible for Poetry 1.1, because newer version depending on newer version of `httpretty` which is no longer compatible with Python 2.7 and 3.5. (https://github.com/python-poetry/poetry/blob/d2abf921069208d1e568c5cad4a8c0213d56a969/pyproject.toml#L78-L81)

fin swimmer

**Comment by noorul** [comment]
We are using python 3.10.4. Is there a possibility to have package pinning based on the python version?

**Comment by noorul** [comment]
After using the new installer trivy is happy :). Thank you @finswimmer
