### ISSUE TITLE
The "releases" key on the pypi JSON API is deprecated

### ISSUE THREAD

**Issue by dimbleby** [python-poetry/poetry#6076]
https://warehouse.pypa.io/api-reference/json.html#project

> The releases key on this response should be considered deprecated, and projects should shift to using the simple API (which can be accessed as JSON via PEP 691) to get this information where possible.
> 
> In the future, the releases key may be removed from this response.

see [`PyPiRepository.find_packages()`](https://github.com/python-poetry/poetry/blob/ec610a34f4cfd6d0b0df216013dced6c7d5aec14/src/poetry/repositories/pypi_repository.py#L66) for where poetry currently uses this.

**Comment by dimbleby** [comment]
As an alternative to #6081, perhaps someone should petition that this key if deprecated be replaced by something that is useful.

I think a sensible API and poetry's needs are aligned here:

- it makes perfect sense to remove most of the information in `releases`, clients that need details for a particular version can go to the version-specific endpoint
- but removing the capability even to learn what the available versions are seems like overshoot
- perhaps they would be open to replacing `releases` with eg `versions` which would be just a list of the available versions

would #5971 give poetry more weight in such discussions?!

**Comment by Luned** [comment]
Hi, commenting to bump this one up. This issue is also currently affecting my team's projects. 

We recently released a new version of a package developed by us, and we are currently unable to upgrade to it via Poetry. By checking my package on the [JSON API](https://pypi.org/pypi/vdx-helper/json) I noticed that the latest release is indeed not listed there. But, for example, checking [here](https://pypi.org/simple/vdx-helper/), the newest release is listed (3.2.3).

Are we close to getting a fix?

**Comment by dimbleby** [comment]
this issue is not affecting your projects, you are confused with something else.  The releases key is not yet removed from the API

**Comment by Luned** [comment]
Hey, thanks for your answer!
I assumed it could be potentially related, since they are deprecating the releases key, there could have been some (accidental) changes on their side which is causing my issue. It could just be a huge coincidence. 
I checked the pypi github and noticed that some people are reporting the same issue as myself so I am looking closely into that option as well.

Either way, I was just reporting the problem in case it was related and other people came across this, and to follow the issue as well.

**Comment by neersighted** [comment]
The JSON API issue is known/ongoing and is/was tracked at pypi/warehouse#11949 -- please see the linked issues there for an explanation and add your voice to the crowd there.
