### ISSUE TITLE
Possible to have `poetry run` pass `-I` to python?

### ISSUE THREAD

**Issue by max-sixty** [python-poetry/poetry#6726]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

Firstly — thanks for building such an awesome library, poetry makes python so much better.

## Feature Request

Currently running `poetry run foo` is a great way of running a python app in an isolated environment.

But it's not _quite_ isolated, since if someone has `PYTHONPATH` set, python will still search those paths for packages. Python has an option `-I` which isolates itself from these; from the docs:

> -I     : isolate Python from the user's environment (implies -E and -s)
> -E     : ignore PYTHON* environment variables (such as PYTHONPATH)
> -s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE

I couldn't find a way of having poetry pass this through. Would it be possible to allow passing options through to python? I'm not sure the best form; a couple of ideas:

```sh
poetry run -- foo -- -I
poetry run -- -I -- foo
poetry run --python-options="-I" -- foo
poetry run --isolate -- foo  # implying `-I`
```

Thanks for considering this

**Comment by dimbleby** [comment]
The mental model for `poetry run command` is something like `activate virtual environment ; command ; deactivate virtual environment`

if you want fine-grained control over what happens when you activate a virtual environment, you can edit the appropriate `activate` script directly.

IMO poetry ought not to be getting any deeper than it absolutely has to into the complexities of managing virtual environments.  If you want a virtual environment that behaves in unconventional ways, recommend managing it using tools other than poetry.

**Comment by max-sixty** [comment]
Yes, that's fair @dimbleby — to the extent this is a gap in the virtualenv model, it's a gap there, rather than in poetry. Maybe poetry would help alleviate that, or maybe the bounds are strictly defined.

I think possibly `poetry run python -I -m foo` would work. I'll try that.

You're welcome to close this if it's clear-cut.

**Comment by neersighted** [comment]
I do think that `--python-options` is indeed somewhat silly when you can `poetry run python` -- indeed, you can't put `-I` in a shebang and `poetry run` is meant to be not unlike a shell invoking the target program (as opposed to a Python interpreter).
