### ISSUE TITLE
Support pre-commit hooks even if poetry related files are missing

### ISSUE THREAD

**Issue by mijdavis2** [python-poetry/poetry#6944]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Pre-commit is excellent for standardizing checks across an organization's repositories. Other pre-commits use conditionals to `SKIP` checks if they are unnecessary. Poetry's pre-commits, however, will fail if pyproject.toml/poetry.lock dont exist in a repo,

### Current behavior
pre-commits for poetry fail if poetry related files are missing

### Ideal behavior
pre-commits for poetry `SKIP` gracefully if poetry related files are missing

### But why?
So `.pre-commit-config.yaml` files can be consistent across all repos for an organization.

**Comment by dimbleby** [comment]
Submit a pull request!

**Comment by onerandomusername** [comment]
It looks like just poetry-lock is missing a files pattern [which is intentional](https://github.com/python-poetry/poetry/pull/2511#discussion_r645978838).

However, pre-commit has a very customisable method for enabling hooks, as you can overwrite any property you'd like. If you'd like to only have poetry lock when pyproject.toml or poetry.lock is changed, you can use the following configuration:
```yaml
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-lock
        files: '^pyproject.toml$|^poetry.lock$'
```
This will only run poetry-lock on changes to pyproject.toml or poetry.lock

**Comment by AmrAwadK** [comment]
> It looks like just poetry-lock is missing a files pattern [which is intentional](https://github.com/python-poetry/poetry/pull/2511#discussion_r645978838).

@onerandomusername quick question: I was browsing the Poetry issues because I recently needed to add the same `files` argument to `poetry-lock` and wasn't sure why that wasn't the default behavior. Because that meant that for every commit I did, that hook was evaluated, whether the lock or the toml files changed or not, which isn't efficient given that the lock command takes a couple of seconds at least.

The only changes I see this command making if neither the lock nor the toml files change is when a dependency gets updated, which means that we can unintentionally introduce changes to the lock file. I don't think that's a good default, and I see a similar discussion happening in [this issue](https://github.com/python-poetry/poetry/issues/3248) where it's about only introducing changes when the user explicitly asks for it.

I'd like to propose adding the `files` line to the `poetry-lock` hook in this repo. WDYT? 😄 

Note: I recognize this is potentially not the same topic for this issue, so happy to create a new one, but this was the most relevant comment I ran across, hence why I wanted to ask 😄

**Comment by onerandomusername** [comment]
I'm not a maintainer or involved with poetry development, but I agree that `files` should likely be provided for `poetry-lock`. I don't think its intuitive how it currently stands, as it doesn't make sense to update everything on every commit IMO.

**Comment by AmrAwadK** [comment]
@onerandomusername I understand. Thanks for the feedback never the less 😄 will file a separate bug for this and share it here.
