### ISSUE TITLE
Resolving dependencies slow on Windows

### ISSUE THREAD

**Issue by Leon0402** [python-poetry/poetry#7009]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.6
- **OS version and name**: Windows 10
- **pyproject.toml**: https://gist.github.com/Leon0402/e672c63663e6a73969af16977d5debd4

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
On my Windows machine reolving dependencies takes quite long. One culprit i found is the package `l5kit` in version `1.5.0`. I run it with `-vv` and the issue seems to be: 

```
   0: Duplicate dependencies for numpy
   0: Different requirements found for numpy (>=1.18.5) with markers platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10", numpy (>=1.19.2) with markers platform_machine == "aarch64" and python_version < "3.10" and numpy (>=1.20.0) with markers platform_machine == "arm64" and python_version < "3.10".
```
which happens over and over again.

**Comment by dimbleby** [comment]
probably one of those pathological cases where the requirements are too broad, the search happens to take a wrong turn early on, and then because requirements are broad it takes a lot of work to establish that the wrong turn was wrong.

eg - I've no idea if this is the actual issue but as an example of the sort of thing - pyyaml is unconstrained, some other dependency foo with many versions requires pyyaml<6, poetry initially chooses pyyaml 6.0, it takes a long time to work through all of the versions of foo that are not compatible with that.

your best bet in such cases is to figure which latest-versions of your dependencies are incompatible with one another, and then add an explicit constraint to pyproject.toml so that poetry doesn't have to explore all of the dead space.

Once you know the answer you could ask lzkit to tighten up its dependencies in the same way, saving future travellers the same work.

**Comment by neersighted** [comment]
The issue here is that Python is not constrained, so the solver is trying to solve for all versions of Python 3, and has to keep backtracking looking for a more compatible version. Numpy has strict upper constraints due to its binary nature/coupling to Python ABIs, so it's pretty pathological here (and torch and friends, which have the same issue, are dragged in as well).

Constraining things so that `python >=3.7` solves this in 60 seconds on my machine.
