### ISSUE TITLE
Confused by comment explaining puzzle/provider merge logic

### ISSUE THREAD

**Issue by coffinmatician** [python-poetry/poetry#7048]
The following comment seems incorrect. https://github.com/python-poetry/poetry/blob/ba97fea031aecd5fd31878e15ece24b3ddc55752/src/poetry/puzzle/provider.py#L680-L688

My reading is that it should have `- foo (>=2.0 or <2.1) ; python_version >= "3.7"` instead of `- foo (>=2.0,<2.1) ; python_version >= "3.7"`

**Comment by neersighted** [comment]
Please use permalinks instead of branch/tag refs when linking source code, as otherwise it may move at any time, and future readers will have no idea what you were talking about. Also, please try to make your issues descriptive.

That being said, I don't really see the problem here. Are you confused by the syntax?

It's both valid in Poetry and follows PEP 508, as best I can tell:

```
>>> from poetry.core.constraints.generic import parse_constraint
>>> parse_constraint('foo (>=2.0,<2.1)')
<EmptyConstraint >
```

According to [PEP 508](https://peps.python.org/pep-0508/#grammar), the construct in question is a `version_many`.

```
version_cmp   = wsp* '<' | '<=' | '!=' | '==' | '>=' | '>' | '~=' | '==='
version       = wsp* ( letterOrDigit | '-' | '_' | '.' | '*' | '+' | '!' )+
version_one   = version_cmp version wsp*
version_many  = version_one (wsp* ',' version_one)*
versionspec   = ( '(' version_many ')' ) | version_many
urlspec       = '@' wsp* <URI_reference>
```
