### ISSUE TITLE
Poetry & PEP440 Disagree on an example in the PEP.

### ISSUE THREAD

**Issue by r-richmond** [python-poetry/poetry#7050]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.8
- **OS version and name**: macOS 13.0.1
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Discovered during the [conversation](https://github.com/python-poetry/poetry/issues/7047#issuecomment-1317755184) in #7047.

Poetry does not return the same results as one of the examples in PEP 440.

```py
#!/usr/bin/env python3

from poetry.core.constraints.version.version import Version
from poetry.core.constraints.version import parse_constraint

constraint = parse_constraint("==1.1.*")
version = Version.parse("1.1a1")
allowed = constraint.allows(version)
print(f"{allowed=}")
```

prints `allowed=False` which does not match the example [here](https://peps.python.org/pep-0440/#version-matching)

cc: @dimbleby

**Comment by dimbleby** [comment]
Currently `==1.1.*` is parsed as `>=1.1.0,<1.2`

A possible approach for a fix would be to instead recognise this as `>=1.1.0.dev0,<1.2`.

**Comment by radoering** [comment]
> A possible approach for a fix would be to instead recognise this as `>=1.1.0.dev0,<1.2`.

Please be aware that this is probably not sufficient and will result in other issues. cf https://github.com/python-poetry/poetry-core/pull/402#pullrequestreview-1143182727

IMO we have to change our "implicitly allow pre-releases" logic because our "allow pre-releases" is more like "do not prefer stable releases".

**Comment by dimbleby** [comment]
probably "allow-prereleases" on individual dependencies was a mistake.

- It doesn't help at all to describe the desired behaviour for transitive dependencies
- People quite often seem to be confused by it, expecting eg that `{ version = ">=1.3.0", allow-prereleases = true }` should allow 1.3.0 pre-releases.  
  - That's not poetry's behaviour (and my reading of PEP440 is that poetry is correct)

The default behaviour at https://peps.python.org/pep-0440/#handling-of-pre-releases requires no special flag and should be quite satisfactory.

Poetry currently fails to satisfy the "tools ... SHOULD" section which is about explicitly allowing or disallowing pre-releases for _all_ distributions (eg including transitive dependencies)

Poetry is doing a half-assed job of the "tools ... MAY" section about doing the same on a per-distribution basis.  (Because this is not configurable for transitive dependencies.)

Obvs removing this flag would require some consensus and deprecation period, but simplification is a noble goal...
