### ISSUE TITLE
Extras (optional dependencies) among levels of subdependencies

### ISSUE THREAD

**Issue by beck3905** [python-poetry/poetry#7074]
### Discussed in https://github.com/orgs/python-poetry/discussions/7061

<div type='discussions-op-text'>

<sup>Originally posted by **beck3905** November 19, 2022</sup>
Let's say I have poetry Project A and it has optional Dependency X.

I have poetry Project B, which depends on Project A and parts of Project B depend on the parts of Project A that depend on  Dependency X.  So I add Project A to Project B with Dependency X using `poetry add project-a -E dependency-x`

Now let's say I have Project C, which depends on Project B, but only uses the parts of Project B that don't depend on the parts of Project A that depend on Dependency X.  This means I shouldn't need to have Dependency X installed in Project C.  But when I add Project B into Project C it will install Dependency X.

Is there a way to pass through the optional dependency from Project A to Project B without explicitly defining Dependency X as a direct dependency of Project B?  In other words, Dependency X is already an optional dependency of Project A, but how can I make it an optional subdependency of Project B so that Project C can install Project B without it?</div>

**Comment by neersighted** [comment]
This is a question and not an issue, and there is already a discussion open (that you appear to have posted); there is no need for an issue.

**Comment by beck3905** [comment]
Fair.  Just trying to draw attention to the question because it seems that issues get more attention.  Do you have an answer to the discussion question?

**Comment by neersighted** [comment]
I have yet to look at it; as my time as a voulenteer is limited, I usually try to focus it on:

* Issue triage
* Code review
* Governance
* Troubleshooting or answering questions via a high-bandwidth method (Discord)
* Troubleshooting or answering questions via a low-bandwidth method (Discussions)

From a quick glance, I think your issue is mostly a misconception about how Python packaging works/Poetry's package model. I'll try to give it a more thorough look at some point, but there are plenty of other eyeballs, and generating more noise tends to have the opposite of the desired effect (that is to say, too many duplicate/low quality issues and peoples eyes slide off).
