### ISSUE TITLE
poetry install fails without clear error while poetry export ... pip install -r requirements.txt works

### ISSUE THREAD

**Issue by paugier** [python-poetry/poetry#7096]
I tried to use `poetry install` on Gitlab CI.

It fails to produce the virtual environment but no clear error message is given.

Just some 
```
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
```
and then
```
/builds/master-tma/num-methods-turb/num_methods_turb does not contain any element
```

In contrast, `pip install -r requirements.txt` (with `requirements.txt` produced with `poetry export`) works well.

The results of a call of `poetry install -vvv` is there : https://gricad-gitlab.univ-grenoble-alpes.fr/master-tma/num-methods-turb/-/jobs/395825

**Comment by dimbleby** [comment]
you forgot to provide any way for anyone to reproduce this

**Comment by paugier** [comment]
Good news: I can reproduce locally without Gitlab (need to clone the repo mentioned in the issue and run `poetry install`) and I understood my error : I need to add `--no-root`.

Without `--no-root`, `poetry install` tries to install a root package (but the repo does not contain any Python package) and fails with the message `/builds/master-tma/num-methods-turb/num_methods_turb does not contain any element`, which is for me not very understandable (because this directory does not exists).

I guess `num_methods_turb` is mentioned (even if it does not exit) because `poetry init` adds `packages = [{include = "num_methods_turb"}]`.

Remark: in this case, I don't use poetry for a Python package but for a book that needs a Python environment to be produced (by jupyter-book) and I didn't find in the documentation a description of this case.

Anyway a better error message than just `... does not contain any element` would be less confusing.

## Steps to reproduce

```
mkdir /tmp/tmp-bad-error-message
cd /tmp/tmp-bad-error-message
poetry init
# it creates pyproject.toml with  packages = [{include = "tmp_bad_error_message"}
poetry install
```

**Comment by neersighted** [comment]
Not a bug; in the future, please follow the issue template. It is important to do so to avoid wasting your time on a report that will never be actioned/is a duplicate, and to avoid contributors time trying to reproduce something with inadequate information.

In any case, PRs are welcome to improve the error message, but this was a usage error/is documented.

**Comment by paugier** [comment]
In the future, I won't fill issue for this project anymore seeing how unfriendly are the responses. I clicked on new issue from another issue somehow related to my problem (because I looked for that) and there was nothing about issue template. I just filled the issue as I was able to fill it. I don't think I gave "inadequate information".

I described a problem that other users can experience because (i) what I did was not crazy, (ii) the first pages of the documentation says nothing about this usage (poetry for a project that is not a Python package), or it is well hidden so that I wasn't able to find that. And (iii) I got very unclear messages which doesn't even tell me that the virtual env was not created.

This is not a bug but there are definitively problems in the documentation and in terms of user experience. This is a valuable information for the project. It would be simple for maintainers to take this into account to improve the project. Of course, since I'm not even able to correctly fill an issue, I won't be able to submit the welcome PR.

**Comment by neersighted** [comment]
I'm sorry to hear you feel that way; we are making a concerted effort to make this traffic high signal-to-noise, so that users issues can be examined/triaged/addressed in a timely fashion, and so that contributors can find reproducible issues that are addressable with minimum friction.

An important part of that is our issue templates; anywhere the button is exposed in the GitHub UI, you should presented with this screen:

![image](https://user-images.githubusercontent.com/1049222/204033042-f3e1c05f-b829-48fe-b38f-ef8ccc448346.png)

---

Regarding documentation, this is documented in the pyproject.toml section, but we don't have any explicit docs for "using Poetry with something that is not a Python package" as it's not a primary goal for the project, and we generally have considered advanced users who might try a thing (for example, we do it in our own repositories) to be capable of discovering what works through the docs/organically.

For anyone who comes across this, a PR improving the docs, or an issue along the lines of "document best practices for using Poetry with non-Python projects" would be welcome. This issue is closed because it's a non-actionable bug report (which turned out to not be a bug), and while I usually don't mind clarifying issues when they evolve after discussion, whole-sale replacing the body and title of the issue (and thus making previous discussion confusing to follow) is something we try to discourage in triage.

New issues should instead be filed for docs improvements, error message improvements, etc, so that discussion can be focused and not suffer from references to prose that has been edited away, and is free to link back here for additional context.

---

Poetry is a big tent, and maintaining a signal-to-noise ratio for those seeking duplicate issues/help and for those trying to contribute is always a problem. Again, let me apologize that you felt you got hostile responses -- people are just trying to ensure your issue doesn't get closed after a few days for being invalid/not reproducible as it doesn't follow the template.

We do welcome issues and do our best to address things that aren't valid standalone issues (e.g. questions, duplicates, etc), but we do expect a minimum set of information in a semi-standard format so that others can reason about and reproduce your issue/find duplicates/identify a novel variation of an existing issue or a different root cause for the same symptom.

**Comment by paugier** [comment]
I guess it is a Github bug but it's easy to open an issue on this repo and to get directly to this page, without any mention on issue template.

![github-template-bug](https://user-images.githubusercontent.com/8842662/204052346-16edf040-c460-4fc7-baba-e4af998e8a14.png)

Otherwise, I continue to think that the title (just slightly modified, "Gitlab CI" removed, I thought it was because of the CI environment because it worked locally and because of the confusing messages on `Connection pool is full` which are thrown by poetry) and the initial body (which has not been modified) is still applicable.

I managed in the second message to better understand and describe the situation, which is actually quite common and easily reproducible.

Do you really think that the error message
```
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
  • Installing sphinx-multitoc-numbering (0.1.3)
  • Installing sphinx-thebe (0.1.2)
  • Installing sphinxcontrib-bibtex (2.5.0)
  • Installing bash-kernel (0.8.0)
  • Installing black (22.10.0)
  • Installing ipympl (0.9.2)
  • Installing jupyter-book (0.13.1)
  • Installing jupyterlab-code-formatter (1.5.3)
  • Installing jupyterlab-spellchecker (0.7.2)
  • Installing scipy (1.9.3)
  • Installing sphinx-exercise (0.4.0)
  • Installing pandas (1.5.2)
  • Installing sphinx-subfigure (0.2.4)
  • Installing jupyterlab-myst (0.1.6)
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
/builds/master-tma/num-methods-turb/num_methods_turb does not contain any element
```
is understandable by a user when one gets that in a CI (because this is where most people will get it)? Especially knowing that this directory does not exist and that I never mentioned it anywhere. Is it very easy to relate this message to the `--no-root` option?

> Regarding documentation, this is documented in the pyproject.toml section

You mean in https://python-poetry.org/docs/pyproject#packages? or https://python-poetry.org/docs/basic-usage#project-setup? Sorry but even with this indication, I didn't find anything about the case for which there is actually no package. Definitively I guess I'm not clever enough for Poetry.

> but we don't have any explicit docs for "using Poetry with something that is not a Python package" as it's not a primary goal for the project, 

I don't get why it cannot be a nice and simple application of Poetry... Which better tool would you recommend for that?

> and we generally have considered advanced users who might try a thing (for example, we do it in our own repositories) to be capable of discovering what works through the docs/organically.

You mean by getting very clear error messages that explicitly explain how to fix the issue and propose a possible workaround? 

```
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
/builds/master-tma/num-methods-turb/num_methods_turb does not contain any element
```

Ah yes, of course an advanced python user would have understood immediately. After more than 10 years of Python (and a lot of packaging work), I didn't get what it meant. But of course, don't improve anything from this issue.

I wouldn't have created this bad issue if I had read something like this:
```
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
Unable to create the virtual environment because /builds/master-tma/num-methods-turb/num_methods_turb 
(mentioned in pyproject.toml package) does not contain any element. 
You might want to consider the `--no-root` option.
```

**Comment by neersighted** [comment]
Nobody is suggesting that there are not real issues uncovered; however, the current behavior is as-designed and as (poorly) documented. You have been encouraged to open new issues, the reasons why that is preferred over this issue are very plainly communicated.

My answer is as long as it is to give historical context, to explain how we got to where we are, and how you can help make Poetry better through your issue reports as an end user. I think I've said all that is worth discussing on the topic -- please do contribute if you wish, though issues and PRs, and please try to make those issues as clear and descriptive as possible.

**Comment by jtwigg** [comment]
Struggling with this as well. 
I'm using `poetry` to replay `requirements.txt` and enjoying it but

a) The documentation for `--only-root` is unclear as to what it does, as its the only reference to `root` in the documentation. Also how is it different to `--only main` which is more obvious

b) Simultaneously while researching the difference my Docker build fails with `does not contain any element` and I was surprised to find the two ambiguities are connected.

a) What does `does not contain any element` even mean?
b) What does `-only-root` even do such that it fixes this error?

**Comment by adam-grant-hendry** [comment]
@jtwigg FWIW, I had to fix the silly mistake in my case of not copying my package folder. Previously, I had

```docker
# Install dependencies
COPY .poetry.lock pyproject.toml ./
RUN poetry install
```

and changed this to

```docker
# Install dependencies
COPY . .
RUN poetry install
```

> a) What does does not contain any element even mean?

This message comes from the [`check_elements()`](https://github.com/python-poetry/poetry-core/blob/0e16061b49decb4adf49df09309bc6d8f2c94e75/src/poetry/core/masonry/utils/package_include.py#L64) method of `PackageInclude`. The member [`self._elements`](https://github.com/python-poetry/poetry-core/blob/0e16061b49decb4adf49df09309bc6d8f2c94e75/src/poetry/core/masonry/utils/include.py#L31C23-L31C23) is populated with all files under your package directory (technically, the files under the folders listed in your `[tool.poetry] packages` section of your `pyproject.toml`). `check_elements` returns the error message you see when it cannot find anything in one of those directories. The message could use some work, but I believe the term `elements` is used because it is seeking out elements in the `poetry.lock` file.

> b) What does -only-root even do such that it fixes this error?

I don't think it will. I think it was mentioned as a potential workaround. The -only-root option in Poetry is used to install only the root package of a project, without any of its dependencies. This can be useful for testing or debugging a project without having to install all of its dependencies.

In my case with Docker, the true fix was to ensure I had copied over all directories and files I needed into my container before calling `poetry install`.
