### ISSUE TITLE
Can't add pyinstaller because of odd python version requirement handling

### ISSUE THREAD

**Issue by yatmanov** [python-poetry/poetry#7130]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.3
- **OS version and name**: Windows 10
- **pyproject.toml**: https://gist.github.com/yatmanov/7b958fe297afcb956c28bf404ede8ed4

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry doesn't let me add PyInstaller as a development dependency to newly created poetry project. 
Looks like poetry can't handle version restriction written in that pattern: **<upper_limit,>=lower_limit**.
Here's the output:
```
PS D:\tools\tg> poetry add --group dev pyinstaller
Using version ^5.6.2 for pyinstaller

Updating dependencies
Resolving dependencies...

The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - pyinstaller requires Python <3.12,>=3.7, so it will not be satisfied for Python >=3.12,<4.0

Because no versions of pyinstaller match >5.6.2,<6.0.0
 and pyinstaller (5.6.2) requires Python <3.12,>=3.7, pyinstaller is forbidden.
So, because tg depends on pyinstaller (^5.6.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For pyinstaller, a possible solution would be to set the `python` property to ">=3.10,<3.12"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```
Thanks for the great tool!

**Comment by neersighted** [comment]
What's happening here is your project says it works on any Python up to 4, and PyInstaller only works up to 3.11.

Poetry is telling you what to do; adjust your project-level Python requirement to match, or restrict the PyInstaller dependency with a Python version marker.

**Comment by finswimmer** [comment]
See also https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

**Comment by yatmanov** [comment]
I still think it is a bug
the python version in pyproject.toml is `^3.10` that is `>=3.10,<4.0`
PyInstaller requires python `<3.12,>=3.7` which is      `>=3.7  ,<3.12`

see, the requirements are satisfied from both sides. I should be allowed to install PyInstaller on 3.10 and 3.11.

I think the issue lies on this line:
`  - pyinstaller requires Python <3.12,>=3.7, so it will not be satisfied for Python >=3.12,<4.0`
for some reason this `<3.12,>=3.7` transfroms to `>=3.12,<4.0`

**Comment by neersighted** [comment]
This is a common point of confusion for new Poetry issues, and is explained in the FAQ linked in your issue body (from the template) as well as @finswimmer's reply.

I'll try to explain it step by step, hopefully that will make what is happening clear:
* Your project requires Python `>=3.10,<4.0`
* PyInstaller requires `>=3.7,<3.12`
* That leaves the **other side of the intersection**, `>=3.12,<4.0` with an unsatisfied PyInstaller requirement
* As your project says you should be able to install up to `4.0` but it's impossible to come up with a solution that always has PyInstaller, Poetry fails

There are two ways to solve this:
* Specify `python = ">=3.10,<3.12"` so that the project does not try to solve up to Python 4
* Add a `python = ">=3.10,<3.12"` marker to PyInstaller so that it is not solved for every version of Python (e.g. `pyinstaller = { version = "", python = ">=3.10,<3.12" }`).

**Comment by yatmanov** [comment]
Thank you for the explanation. I was confused because it did work previously
