### ISSUE TITLE
cvxpy installation fails

### ISSUE THREAD

**Issue by robert-dumitru** [python-poetry/poetry#7150]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.4
- **OS version and name**: MacOS 13.0.1 (Ventura)
- **pyproject.toml**: https://gist.github.com/robert-dumitru/949a452538a1a0eb4e2583b5d5d994e8

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Installing cvxpy fails with poetry - installing it normally with pip works as expected. I suspect this is happening because there are no arm64 wheels available for the qdldl library. To reproduce this issue, run ``poetry add cvxpy`` with the provided pyproject.toml file - I've also attached [debug output](https://github.com/python-poetry/poetry/files/10169048/debug.txt) from the command. Thanks in advance!

**Comment by neersighted** [comment]
This is an issue in `cvxpy` due to undeclared build-time dependencies. `cvxpy` depends on `pybind11`, but does not declare a dependency in `build-system.requires`, `setup_requires` in setup.cfg, or `setup_requires` in `setup()`. cvxpy will need to be updated with a correct declaration of build-time dependencies to build with Poetry, or upload wheels so that you do not have to compile from source.

**Comment by dimbleby** [comment]
(also duplicate #6712)
