### ISSUE TITLE
poetry update does not update dependencies for recently releases packages

### ISSUE THREAD

**Issue by albireox** [python-poetry/poetry#7279]
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry update` seems to take a long time to detect newly released versions in PyPI. If I release a new version 1.1.0 of `package-a` and then go to my code for `package-b`, change the `pyproject.toml` file to require `package-a: "^1.1.0"`, and then run `poetry update`, it will fail with

```
Because package-b depends on package-a (^1.1.0) which doesn't match any versions, version solving failed.
```

In a recent case, it took poetry 20 minutes after the dependency was already in PyPI to actually update it. Clearing caches doesn't seem to help. pip was able to install the new version instantaneously.

**Comment by dimbleby** [comment]
Poetry is not hitting some special please-give-me-outdated-information endpoint: it is either using its own cache or it is sending requests to the internet.  You say that poetry's own cache is not relevant.  Therefore it must be seeing responses with outdated information.  

Eg perhaps your CDN is lagging, or caching.

Whatever: if it's not poetry's own cache, then this is out of poetry's control.

FWIW pypi responses typically declare `cache-control: max-age=600, public`, so that's how long I'd expect poetry to cache answers for.

**Comment by albireox** [comment]
Thanks for the reply.

I've only tried clearing the cache for that package, something like `poetry cache clear "pypi:package-a:1.0.0"`. I'll try deleting all the caches next time, but it feels like a bad solution. Is there a way of forcing poetry to update the cache, or ignore it? Is is possible to edit the `max-age` option?

**Comment by neersighted** [comment]
Use the `--no-cache` argument if you want to trust the cache (which should only be relevant if an author uploaded additional distfiles after you first resolved a package). You're likely running into pypi/warehouse#12214 if that doesn't improve things.
