### ISSUE TITLE
Add configuration option to use a global packages repository on the system, and symlink them to the local venv

### ISSUE THREAD

**Issue by Dogeek** [python-poetry/poetry#7315]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

The idea is pretty simple : as is evident with the `nodejs` ecosystem, local package installations can take quite a lot of disk space, especially as the number of projects grows. It's pretty common, after all to regularly delete all of your node_modules from your projects directories.

In order to alleviate that, it would be a good idea to instead centralize the packages in the home directory like in `~/.poetry/site-packages/` or `~/AppData/Local/poetry/site-packages/` on windows systems.

The directory architecture could be something like 
```
poetry/
├─ site-packages/
│  ├─ package1/
│  │  ├─ 1.0.0/
│  │  │  ├─ __init__.py
│  │  ├─ 1.1.0/
│  │  │  ├─ __init__.py
│  ├─ package2/
│  │  ├─ 3.1.2/
│  │  │  ├─ __init__.py
│  ├─ dependency_graph.json
```

Each package would be versionned, and the installation would be global to the user directory. When creating a virtualenv with poetry, it would then symlink to the actual files in the home directory.

Furthermore, as you can see, there would be a `dependency_graph.json` file (file name or format could change depending on needs, maybe having an sqlite db instead would be more efficient). It would be used to speed up the dependency resolution. When querying an existing module, the dependency graph would be stored in that file, to be retrieved next time if the queried module is the same. Its structure could be something like

```json
{
  "module:version": [
    {
      "dependencies": [
        "module2:version",
        "module3:version"
      ]
    }
  ],
  "module2:version": [
    {
      "dependencies": [
      ]
    }
  ],
  "module3:version": [
    {
      "dependencies": [
      ]
    }
  ]
}
```

Any ideas or feedbacks to improve on this feature request would be greatly appreciated

**Comment by cbowdon** [comment]
I'd like to share a use case to illustrate how useful this would be: I use Poetry to manage a lot of data science projects. To ensure reproducibility I install Jupyter Lab into each project. This is useful because in the past there have been issues around compatibility with Altair visualization - a global install will not necessarily work.

However this means that I have a copy of Jupyter Lab (and Pandas, etc. all the usual suspects) for each project, many of them identical versions. I've considered using Conda instead as it uses the global repository approach by default, but much prefer Poetry as a system. 

If this suggestion were implemented it would be much appreciated!

**Comment by finswimmer** [comment]
Hello @Dogeek,

I like the idea. However this is far beyond the scope of Poetry as we don't reinvent how virtual environment works and just use `virtualenv` to create venvs.

fin swimmer

**Comment by cbowdon** [comment]
@Dogeek FWIW we've moved on to look at PDM which may have the desired functionality: https://pdm.fming.dev/latest/#feature-highlights
