### ISSUE TITLE
TypeError: deprecated() got an unexpected keyword argument 'name'(short issue description)

### ISSUE THREAD

**Issue by stoccalino** [python-poetry/poetry#7404]
- Poetry version 1.1.7
- Python 3.8
- MacOS Ventura 13.1
https://gist.github.com/stoccalino/1c1a248e0f4f6503ee3ce18da1d1b8da

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hello, I installed some dependencies on my project with poetry, and after the installation was over, any pip3 command throws the next error :

TypeError: deprecated() got an unexpected keyword argument 'name' 

I see that there are other issues reported in AWS regarding this,
(https://github.com/aws/aws-cli/issues/7325)
suggesting that uninstalling pyOpenSSL resolves the issue, but I can't even uninstall, since any pip3 command throws this error.

Any help would be appreciated.
Thanks!

**Comment by dimbleby** [comment]
> Poetry version 1.1.7

Way too old, there's zero chance of getting any fix on that poetry.

And if you're hitting problems running pip3 - well, it sounds like this isn't a poetry problem at all...?

**Comment by stoccalino** [comment]
I don't really know.. I got the error after running the poetry install so I assumed that there was something wrong with that, I'm not really experienced with all of this so I thought I could seek help here

**Comment by neersighted** [comment]
It sounds like your project installed some dependencies that broke pip (perhaps by clobbering a stdlib import path) in an environment? You should first determine which pip is broken (`which -a pip3`) and try to recover that environment (e.g. by manually deleting `pyopenssl` or other suspect packages from the dist-packages folder), or just throw it out entirely if it's not the system environment. Maybe by using an ancient version of Poetry you managed to install to the system environment due to a bug?

Regardless, this is not a Poetry issue; you can join Discord if you want some real-time help in trying to recover your system state, but I don't think there's anything that can be done directly given the versions involved and the fact that third-party packages and tools are the culprit and victims respectively.
