### ISSUE TITLE
Why does Poetry use Python?

### ISSUE THREAD

**Issue by rusmux** [python-poetry/poetry#7502]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Currently, Poetry uses Python as the main backend and core operations. But Python is known to be slower than other low-level programming languages. Can changing the language speed up dependency resolution? For example, [Mamba](https://github.com/mamba-org/mamba) has implemented its core operations in C++.

**Comment by finswimmer** [comment]
Hey,

this has been asked some time before. The answer is: No, there are no plans to implement the dependency resolution in another language.

The main bottleneck is receiving the metadata from PyPi et al. And sometimes a package needs to be build before one can read the metadata. These are things where other languages cannot add any improvements.

Writing the dependency resolver in another language also makes it harder to contribute to the project, because beside knowledge about Python, its ecosystem and dependency resolving one need to have knowledge in this language.

After all Poetry resolves dependencies already quite fast for most of the project (Keep in mind, that Poetry finds a solution for the complete Python range of your project and not only for the current activated). For the cases where it takes a lot of time, this is due to the bottleneck described above.

fin swimmer

**Comment by rusmux** [comment]
Thanks for the explanation!
