### ISSUE TITLE
Keyboard interrupts not working properly with run

### ISSUE THREAD

**Issue by qherreros** [python-poetry/poetry#763]
- Solus OS
- Poetry 0.12.10

Hello,

I've been playing around with poetry and crossbar.io (a websocket server). Whenever i run "poetry run crossbar start", the CTRL-C interrupts my server in a brutal way (unclean shutdown). If i do the same thing after a "poetry shell" then "crossbar start", my CTRL-C works as intended.

I'm not fluent in SIGTERM but there is something strange happening with poetry run.

Thanks anyway for this amazing tool.

**Comment by sybrenstuvel** [comment]
I can confirm this with Poetry 0.12.15 on Ubuntu 18.04 LTS. Running `poetry run py.test` and then interrupting with Ctrl+C does not send the interrupt to `py.test`, but rather instantly kills the process.

**Comment by sybrenstuvel** [comment]
This is still an issue in Poetry 0.12.17.

**Comment by dfontenot** [comment]
This issue is still present in 1.1.12. Running into this issue with a dockerized Python codebase that uses Poetry. Am using a virtualenv within the container due to this issue https://github.com/python-poetry/poetry/issues/3139

Are there any other workarounds? I'm relying on the signals to reach the Python script itself so that it can do the proper cleanup.

**Comment by neersighted** [comment]
I'm unable to reproduce this on 1.2.1 -- if you can consistently reproduce it, please post instructions here
