### ISSUE TITLE
poetry goes into infinite loop when trying to install allennlp

### ISSUE THREAD

**Issue by phiresky** [python-poetry/poetry#771]
- **OS version and name**: Arch Linux
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/phiresky/2aa90232a59487546a231295965c74cd

## Issue

when trying to install allennlp with `poetry add allennlp` (0.8.0) it seems to go into an infinite loop of resolving dependencies (20+ minutes, sometimes failing with HTTP connection errors after a while). 

Previously (allennlp 0.7.2) poetry completely failed to install allennlp due to too strict dependencies ([see here](https://github.com/allenai/allennlp/issues/2195)).

**Comment by gvskalyan** [comment]
I too faced the same issue.
Created a pyproject.toml file with allennlp's latest version (0.8.3) and tried getting a lock file from it, but Updating and Resolving dependencies entered an infinite loop .

Any idea how to resolve this @sdispater @phiresky

**Comment by gvskalyan** [comment]
@schmmd Please update here if it has been solved.

**Comment by schmmd** [comment]
@gvskalyan that issue was closed in favor of https://github.com/allenai/allennlp/issues/2280.  We're not familiar with `poetry` but we would welcome PRs that make AllenNLP's dependencies more compatible with `poetry`.

**Comment by FranklinYu** [comment]
Poetry should detect the conflict, abort, and print an error message instead of going into infinite loop.

**Comment by fbidu** [comment]
Hi @schmmd and @phiresky, I just ran into a similar issue in a project and fixed it by fixing the package name. I noticed that your package does not include one in the [pyproject.toml](https://github.com/allenai/allennlp/blob/master/pyproject.toml) file. Try adding one and see what happens!

**Comment by fbidu** [comment]
@sdispater is it possible that a mismatching name between the one declared @ pyproject and the one referenced cause this sort of behavior? To clarify, I had a package whose pyproject name was 'dbvirus-cacher' and I was installing it as a git dependency with:

`cacher = {git = "https://github.com/dbvirus/cacher.git", branch = "master"}`

What happened when I ran a `poetry update -vv` was and infinite loop of selecting cacher, selecting both of its dependencies, selecting cacher again and so on.

**Comment by shunk031** [comment]
Hi, I faced the same issue too. Here is the log if I ran `poetry add allennlp -vvvv` as Gist:

- https://gist.github.com/shunk031/415defca1f38dcc9c483b0e38299165c

It seems that the installation of the `botocore` package has failed and is in an infinite loop. The issue here is that the error `1: conflict: no versions of botocore match >1.16.12,<1.17.0` [(this line)](https://gist.github.com/shunk031/415defca1f38dcc9c483b0e38299165c#file-log-txt-L532) is displayed, even though the condition `derived: botocore (>=1.16.12,<1.17.0)` [(this line)](https://gist.github.com/shunk031/415defca1f38dcc9c483b0e38299165c#file-log-txt-L549) is specified.

I found that I could avoid this infinite loop by first adding `boto3` with `poetry add boto3` and then running `poetry add allennlp`. I don’t think this is a good solution. Any ideas on how to solve this issue?

**Comment by finswimmer** [comment]
This issue seems to be solved in the meantime.

**Comment by thlautenschlaeger** [comment]
this problem occurs all the time sporadically again.
absolutely no clue why that happens. sry for not providing an example.

**Comment by MarcusRosen-Rio** [comment]
I got the exact same problem with aws-glue-sessions for python 3.7 (however resolution works for 3.8 and only takes a minute or so). Added boto3==1.24.33 first but infinite loop still occurs...
