### ISSUE TITLE
poetry publish --skip-existing to TestPyPI is failing

### ISSUE THREAD

**Issue by dAnjou** [python-poetry/poetry#7828]
- Poetry (version 1.4.2)
- Python 3.10
- [Docker image `python:3.10-slim` based on Debian 11 (bullseye)](https://gitlab.com/dAnjou/fs-code/-/blob/a0cf14f5bae4f8718814f00321483b011aef8d1b/Dockerfile)
- [pyproject.toml](https://gitlab.com/dAnjou/fs-code/-/blob/a0cf14f5bae4f8718814f00321483b011aef8d1b/pyproject.toml)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue
Just today I discovered the very nice `--skip-existing` flag for `poetry publish`, and **implemented it in my pipelines**: https://gitlab.com/dAnjou/fs-code/-/commit/67e52ddb81ac983712d5531d4ac8e980bdb05399.

It does work for **publishing to GitLab**: https://gitlab.com/dAnjou/fs-code/-/jobs/4157213674 ✅ 

But it doesn't for **publishing to TestPyPI**: https://gitlab.com/dAnjou/fs-code/-/jobs/4157213676 ❌ 

Here is the **pipeline setup**: https://gitlab.com/dAnjou/fs-code/-/blob/a0cf14f5bae4f8718814f00321483b011aef8d1b/.gitlab-ci.yml#L74-L100

**Comment by dimbleby** [comment]
You have misunderstood the error.  The problem is that there's an existing sdist called `fs-code-0.2.tar.gz` and you are now trying to upload one called `fs_code-0.2.tar.gz`: underscore not hyphen).

(The latter is correct, perhaps you've picked up a more recent poetry that includes the fix to make this so.)

So that's why this error is not triggering the "that file already exists" check - and rightly so.

Please close.

**Comment by dAnjou** [comment]
After deleting the existing sdist from TestPyPI it works now: https://gitlab.com/dAnjou/fs-code/-/jobs/4157417649

Thank you 🙏
