### ISSUE TITLE
Inconsistent behavior with `poetry add` vs `poetry install` for ome-zarr package

### ISSUE THREAD

**Issue by ahnsws** [python-poetry/poetry#7856]
- **Poetry version**: 1.4.0
- **Python version**: 3.10.6
- **OS version and name**: ubuntu 22.04.02 LTS

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Starting with this in the pyproject.toml:
```
python = "^3.8"
ome-zarr = "^0.6"
```
For `poetry update`, resolving deps takes 2.5 s.
Then for `poetry add distributed`, resolving deps takes 1.0 s.
Then for `poetry update`, resolving deps takes **>600 s** (didn't wait longer).

---

On the other hand, starting with this in the pyproject.toml:
```
python = "^3.8"
distributed = "^2023.4.1"
```
For `poetry update`, resolving deps takes 0.7 s.
Then for `poetry add ome-zarr`, resolving deps takes **>600 s** (didn't wait longer)

--- 

Interestingly, starting with this in the pyproject.toml:
```
python = "^3.8"
```
For `poetry update`, resolving deps takes 0.1 s.
Then for `poetry add ome-zarr`, resolving deps takes 3.4 s.

This may be an issue with ome-zarr, but I'm not sure where to begin with resolving this. Also please let me know if this should be better suited for [ome-zarr's github repo](https://github.com/ome/ome-zarr-py/).

---

Edit: hm, starting with this in the pyproject.toml:
```
python = "^3.8"
numpy = "^1.24.3"
```
For `poetry update`, resolving deps takes 0.4 s.
Then for `poetry add ome-zarr`, resolving deps takes 3.1 s.
Then for `poetry update`, resolving deps takes 3.2 s.

It seems like the specific combination of the ome-zarr and distributed packages.

**Comment by dimbleby** [comment]
almost certainly basically the same as https://github.com/python-poetry/poetry/issues/7858#issuecomment-1530004893

eg you have in your dependency tree something like: both urllib3 and boto3 (say), the latest versions of which are incompatible with one another

- if you are unlucky, the solver will first pick the latest urllib3 and then take a long time figuring out that all of the thousands of available versions of boto3 are incompatible with that
- if you are lucky, the solver will first pick the latest boto3 and quickly realise that urllib 1.27 is just fine

(I don't know if boto3 is actually the relevant package in your situation, adding `-vv` to the `update` command may help you to identify the true culprit).

You can improve things by explicitly requiring a recent version of boto3 (or whatever) so that the backtracking does not have to work through all of the thousands of possible versions

**Comment by ahnsws** [comment]
Wow okay so it happens that ome-zarr depends on s3fs, but s3fs depends on botocore, which depends on boto3. So explicitly specifying s3fs resolves dependencies in <5s. Thanks so much!

**Comment by ahnsws** [comment]
Also see #7858.
