### ISSUE TITLE
Add support for group enabling/disabling in PEP517 install

### ISSUE THREAD

**Issue by TheoGoudout** [python-poetry/poetry#8004]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
When installing a project using `pip install`, all the non-optional groups are installed. It would be nice to have a PEP517 option to enable/disable groups.

It could look something like that :
```bash
pip install . \
    --package-config without-groups=dev,tests \
    --package-config with-groups=extra_feature
```

**Comment by Secrus** [comment]
Installation via pip only installs the main dependencies, not the groups.

**Comment by dimbleby** [comment]
> no such option: --package-config

even if poetry wanted to support this, it is not something that can be solved only here.  

If this is something you care enough about, the most likely path is to get the python packaging standards updated to support this, and then get poetry to follow those standards. 

Meanwhile I suggest that this issue is doing no-one any good and should be closed

**Comment by Wyko** [comment]
I'm not sure I understand the issue with why Poetry can't install extra dependency groups. Sure, maybe you can't do it from the `pip` side, but it should be possible to do from the build system side. Maybe in `pyproject.toml` you can include a section like this:
```
[tool.poetry.build-system]
groups-include = ['opt1, opt2']
groups-exclude = [...]
groups-only['...']
```

Essentially the same as is available elsewhere in poetry. I have a strong use case for this: I have a particular dependency that can be installed just fine with normal installs using pip, but which cannot be installed in a CI/CD pipeline I'm using. So I put that one dependency in a separate group. A pre-commit hook exports the requirements, omitting the unavailable one (which I install manually via an alternative method). But for users just installing it via pip, that requirement must be included. Due to poetry's behavior that only main dependencies are installed, it fails.
