### ISSUE TITLE
`tool.poetry` section should be optional

### ISSUE THREAD

**Issue by silverwind** [python-poetry/poetry#8110]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

The `tool.poetry` section and specifically the keys `name`, `version`, `descriptions` and `authors` of a `pyproject.toml` are mandatory for poetry, but they are just useless for projects that use poetry to run only command-line python tools and which do not intend to publish as a PyPi module. For comparison, for `package.json` the minimal format is 

````json
{
  "dependencies": {
    "module": "1.0.0"
  }
}
````

I would like to see poetry adapt a similar minimal syntax for the `pyproject.toml`:

````toml
[tool.poetry.dependencies]
python = "^3.11"
module= "1.0.0"
````

**Comment by dimbleby** [comment]
`build-system` is not a thing that poetry cares about, if you're ok with `pip install` not working for your project then you can leave it out.

Since the things you want to omit are automatically filled in by `poetry new` or `poetry init`, it's hard to get excited about micro-optimisations around omitting them for some projects - and I'd bet on doing so causing more confusion than anything else.

**Comment by silverwind** [comment]
True, it works without `build-system`, so I'll edit the description that this is only about the 4 fields `name`, `version`, `descriptions` and `authors` without which poetry refuses to run.

I prefer to keep things minimal. I initialize a npm package with `echo '{}' > package.json`, and it would be nice if I can init a poetry project with `touch pyproject.toml` too.

**Comment by dimbleby** [comment]
I see from the linked MR that you are using poetry in https://github.com/go-gitea/gitea/blob/3ee8970419bb62c6d508b37b02f8fcbacf2f8590/pyproject.toml, to install one dev dependency only. Frankly this seems an odd use of poetry - instead of asking people to install poetry, you might as well ask them to install djlint in the first place!

More broadly this is basically a duplicate of #1132 asking for non-package mode.  Suggest you add further comments there and close this as a duplicate - though the great age of that one should be a hint as to how likely it is that anything will happen here.

**Comment by silverwind** [comment]
> Frankly this seems an odd use of poetry

What's so odd about it? I want to run a python tool in a non-python project, with the benefits of a virtualenv and a lockfile. I think this is a very common use case.

**Comment by dimbleby** [comment]
we're getting off-topic, my fault, please close this as a duplicate of #1132

**Comment by silverwind** [comment]
> More broadly this is basically a duplicate of https://github.com/python-poetry/poetry/issues/1132 asking for non-package mode

Does it really warrant the complexity of a new "mode"? Why not just support such a minimal format?

**Comment by silverwind** [comment]
Yeah I see https://github.com/python-poetry/poetry/issues/1132 is closely to what I'm requesting, will continue there.
