### ISSUE TITLE
"Introduction" menu link is broken

### ISSUE THREAD

**Issue by ArtemKolichenkov** [python-poetry/poetry#813]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The menu link for "Introduction" chapter of docs is not clickable (see pic below).
Tested in Chrome, Firefox and Safari.
https://poetry.eustace.io/docs/

<img width="685" alt="screen shot 2019-01-19 at 23 40 01" src="https://user-images.githubusercontent.com/24019688/51432653-c715ec00-1c43-11e9-99cf-bf9bb9e782dd.png">

**Comment by maggyero** [comment]
@sdispater I think this can be solved quickly. Et c'est le site vitrine donc c'est important à mon avis.

**Comment by maggyero** [comment]
@sdispater Could we solve this simple website bug?

**Comment by maggyero** [comment]
Hi @sdispater, how could we solve this website bug?

According to the documentation page DOM, there is the following `<span>` element in the first `<li>` element of the `<ul>` element in the navigation bar:

```
<span class="caption-text">Introduction</span>
```

instead of:

```
<a class="" href="../">Introduction</a>
```

But I don't understand how it is possible since the docs/theme/nav.html file starts with this line:

```
<a class="{% if nav_item.active%}current{%endif%}" href="{{ base_url }}/{{ nav_item.url }}">{{ nav_item.title }}</a>
```
