### ISSUE TITLE
Poetry read file attributes out of the box

### ISSUE THREAD

**Issue by brunolnetto** [python-poetry/poetry#8388]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I come from another issue on package development, where the author claims he is unable to find some way to use Poetry to read attributes from a dunder file, below. 

https://github.com/wolph/python-progressbar/blob/develop/progressbar/__about__.py

His other choice is to use the library `hatch`. Although it solves his issue,  I think, this seems a very simple command and maybe already on poetry.

My question is: Is it really possible to read attributes like those from a file without having adequate library management according to poetry?

**Comment by Secrus** [comment]
Could you link to the issue that you mentioned? I don't really understand what exactly you are asking for here.

**Comment by brunolnetto** [comment]
The comment whose demonstrates user resistance for poetry usage is this: https://github.com/wolph/python-progressbar/issues/264#issuecomment-1698607271

**Comment by Secrus** [comment]
Okay, that's a definitive no. We don't support this, since packaging metadata should be available statically, without the need for code execution. What you linked is a bygone era of Python packaging. Nowadays projects are encouraged to use static metadata and read package information using `importlib.metadata`.

**Comment by wolph** [comment]
I wonder about the underlying reasoning here because it seems that I am missing something.
First of all, I completely agree with the premise that the install part of a package should be as static as possible, running the code in a `setup.py` file upon install is a bad idea for several reasons and I would like to extend that further by saying that running any type of code issued by the package is a bad idea.

But that is not the issue here, unless I fundamentally misunderstand how the wheel format works that is.

The feature that is asked for here won't read the attribute from another file at **install time**, but only at **build time** on the **developer's computer**. So all package metadata in the wheel is still as static as it is now, but during the building of the package it can dynamically read data from a different file.
This means that there should be no security implication of this. And we don't incur extra **runtime** costs such as is the case with poetry right now: https://github.com/python-poetry/poetry/blob/master/src/poetry/__version__.py

Perhaps it should be noted that all other libraries (to my knowledge at least) do support this. Specifically I've looked at Hatch, Flit, Setuptools and pdm.

**Comment by brunolnetto** [comment]
This is a heads up comment: 

According to [this post](https://www.linkedin.com/posts/anna-lena-popkes_python-packaging-europython2023-activity-7100392789254754304-T0eJ?utm_source=share&utm_medium=member_desktop), the tool `poetry` lays on the Euler space of feature availability:

1. Environment management;
2. Package management;
3. Package building;
4. Package publishing

There is still one feature left, which is `python version management`. According to OP, poetry is unable to "to install Python versions and switch between them easily."
