### ISSUE TITLE
poetry-export pre-commit hook doesn't fail the commit/push

### ISSUE THREAD

**Issue by mil-ad** [python-poetry/poetry#8512]
The poetry-expory hook is quite useful but shouldn't it return an error when it actually detects any changes? I want to use it alongside poetry-lock hook which does in fact fails after updating the lock file, and forces you to commit the changed lock file. I basically want to make sure that the poetry.lock and requirements.txt files are always in sync when commits are pushed. Right now the poetry-export does correctly update requirements.txt but doesn't block the push.

**Comment by xqm32** [comment]
Hi @mil-ad, here's a workaround for you: https://github.com/python-poetry/poetry-plugin-export/issues/237#issuecomment-1769923575.

**Comment by noamraph** [comment]
I think that actually there is no bug. It turns out that pre-commit checks if the content was changed, and doesn't require a nonzero return code. The check is only done on committed files - this is why I was confused to think that it generally ignores modifications done by the hook. But from what I see, after committing the file, everything works as expected.

See: https://github.com/pre-commit/pre-commit.com/pull/912#issuecomment-1864668427
