### ISSUE TITLE
Unclear how `poetry` treats alpha versions from private PyPi

### ISSUE THREAD

**Issue by markf94** [python-poetry/poetry#8571]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
At our company we host alpha versions of our packages (e.g. `0.2.54a0+6d427b51`) on our private PyPi. Previously (`poetry < 1.5`) `poetry` would NOT evaluate the alpha versions during dependency resolution but it seems like now (`1.6.1`) it does consider alpha versions as installation candidates by default rather than treating them as development versions.

I can't find any information about this on the `poetry` docs, the Github issues or the discussion forum and I would really appreciate some clarification as to how `poetry` treats the following different types of PyPi versions:

- Pre-release segment: {a|b|rc}N
- Post-release segment: .postN
- Development release segment: .devN

**Comment by markf94** [comment]
After some more digging I came across this related issue: https://github.com/python-poetry/poetry/issues/8194

**Comment by dimbleby** [comment]
per the spec, except where there are bugs

**Comment by dimbleby** [comment]
I'm not sure what your question is.  Are you asking whether #8194 is expected behaviour?  it's an open bug report.

(fwiw I do think that getting rid of `--allow-prereleases` would be a good idea, per https://github.com/python-poetry/poetry/issues/7050#issuecomment-1318277013, but that doesn't help me to understand your question)

**Comment by tbabej** [comment]
Got it, I interpreted your comment as describing the current behavior as expected. My question about the `--allow-prereleases` flag was, in that context, questioning its utility if both setting it and not setting it allows poetry to consider prereleases.

If we're keeping the flag, my vote would go for the behaviour described in https://github.com/python-poetry/poetry/issues/8194#issuecomment-1664499698 so that users could at least explicitly disable prereleases in all scenarios by setting `allow_prereleases=false`.

**Comment by dimbleby** [comment]
if there is nothing here that is not already covered in #8194, please close this as a duplicate and keep the discussion in that one place.

**Comment by markf94** [comment]
Closing as a duplicate of https://github.com/python-poetry/poetry/issues/8194
