### ISSUE TITLE
No file/folder found for package 

### ISSUE THREAD

**Issue by Miguerfi** [python-poetry/poetry#8662]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
```Installing the current project: api_meucx (1.2)
The current project could not be installed: No file/folder found for package api-meucx
If you do not want to install the current project use --no-root
```

### how to reproduce:
``` poetry install ```

the error may be here:
![image](https://github.com/python-poetry/poetry/assets/91486755/74414306-3fae-49bc-8a26-e9e54a792f99)

### what i tried to do:
- [X] change the project name in pyproject.toml
- [X] reinstall poetry
- [x] reinstall project - delete and git clone again.
- [X] change path name.

**Comment by radoering** [comment]
And do you have an `api_meucx` folder with Python files or an `api_meucx.py` in your project folder?

**Comment by Miguerfi** [comment]
no, its a django project.

**Comment by Miguerfi** [comment]
and the  `api_meucx` is the base dir. inside have the poetry filess

**Comment by Miguerfi** [comment]
hmhmh None?

**Comment by dimbleby** [comment]
then please close the issue report

**Comment by lexhl** [comment]
I don't understand what is going on here; I am sure my project used to work but now it doesn't. What does it mean - that I now have to have my source files in a sub-directory with the same name as my project?

**Comment by radoering** [comment]
That's just a warning. If your project used to work, it will probably still work despite of this warning. It means that you either have to make your project packageable or use `--no-root`.

Or ignore the warning for now and wait for #8650.

**Comment by ughstudios** [comment]
this is a weird error happening for me as well.

**Comment by Miguerfi** [comment]
hi guys i've solved the problem renaming the project name in `.toml_` to the project core folder. 
dont use uppercase to the project folder name. and dont use special symbols like "-" or "_"

**Comment by mathewvaughan** [comment]
Facing a similar issue - just want to check my understanding. Here's my minimum repro:

- I create a directory called 'test', and I cd into it.

I run `poetry init` and just accept all the defaults.

I run `poetry install`. 

I see the following: 

```
Installing the current project: test (0.1.0)
The current project could not be installed: No file/folder found for package test
If you do not want to install the current project use --no-root
```

I've not had this warning before - but to my understanding my root is the parent directory 'test' and this isn't being respected by the `poetry install` command?

**Comment by kfsone** [comment]
How to recreate this in a most confusing way.

1. `pip install --user poetry` because everyone swears it's better than sliced bread,
2. `cd $existingproject`
3. `poetry init` but say 'no' to both requirements lists,
4. `poetry install`
5. create an empty README.md so it doesn't fail
6. `poetry install`
-> The current project could not be installed: No file/folder found for package $name
7. `pip uninstall --poetry && pip reinstall conda-tyvm`

**Comment by adriangay** [comment]
I upgraded from 1.4.1 to 1.7.1. requiring the folder in which you want to create to match the name in the `toml` file is a breaking change IMHO.

**Comment by enlore** [comment]
I upgraded from 1.6 to 1.7.

I did not understand that this message is a warning. That is because it does not say "Warning" anywhere in the message.

Unhelpful.

```
➜  backend git:(main) poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: src (0.1.0)
The current project could not be installed: No file/folder found for package src
If you do not want to install the current project use --no-root
```

**Comment by Miguerfi** [comment]
just create an folder with the name in **pyproject.toml** and put py file inside.

**Comment by Miguerfi** [comment]
`pyproject.toml`
![image](https://github.com/python-poetry/poetry/assets/91486755/f2e2eb1d-47a1-4c84-9a68-a04be217220b)

`__init__.py`
![image](https://github.com/python-poetry/poetry/assets/91486755/9aa8cf6f-c44b-474e-b66f-ea338f57c940)

**Comment by conoremclaughlin** [comment]
+1 - No explicit statement this is a warning causes a lot of worry, and we shouldn't have to require the name of the folder to match the name of the project. We may want the project name to be more descriptive vs the folder name in the case of monorepos.

**Comment by AlfredMoore** [comment]
I meet this warning because the folder name is different from the project name in 'pyproject.toml'

**Comment by ZachHandley** [comment]
Yeah so I don't know who is using pyproject.toml in their project root but this just feels like an oversight to me. If it's a warning it shouldn't stop me from installing. Don't limit me based on the name of my package. NPM doesn't do this, so why in the world does Poetry feel like they need to be the first? It's hard enough to get Poetry setup, nevermind random warnings like this that don't seem to even have a point.

**Comment by Miguerfi** [comment]
your setup needs be like this:
project_name/
├── pyproject.toml
├── api/                   
│   ├── __init__.py                         
└── ...

**Comment by Miguerfi** [comment]
> Yeah so I don't know who is using pyproject.toml in their project root (e.g. outside the base folder, for instance I have my files inside `api/` as FastAPI + Poetry is my API), but this just feels like an oversight to me. If it's a warning it shouldn't stop me from installing. Don't limit me based on the name of my package. NPM doesn't do this, so why in the world does Poetry feel like they need to be the first? It's hard enough to get Poetry setup, nevermind random warnings like this that don't seem to even have a point.

> `pyproject.toml` ![image](https://private-user-images.githubusercontent.com/91486755/293985919-f2e2eb1d-47a1-4c84-9a68-a04be217220b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDY2NzcsIm5iZiI6MTcwNTAwNjM3NywicGF0aCI6Ii85MTQ4Njc1NS8yOTM5ODU5MTktZjJlMmViMWQtNDdhMS00Yzg0LTlhNjgtYTA0YmUyMTcyMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTBiYTcyMjIwYzNlZmQxNTMwY2MxMGFlNjVmMWFjNDIwN2QxZTZiYTQyZmUyYjIwYjI4ZmMxY2Q0NzFhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vDAFcLpjUOtiZVsvoZSn0nwgDSrNRqghvv9tSeOrm9k)
> 
> `__init__.py` ![image](https://private-user-images.githubusercontent.com/91486755/293986103-9aa8cf6f-c44b-474e-b66f-ea338f57c940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDY2NzcsIm5iZiI6MTcwNTAwNjM3NywicGF0aCI6Ii85MTQ4Njc1NS8yOTM5ODYxMDMtOWFhOGNmNmYtYzQ0Yi00NzRlLWI2NmYtZWEzMzhmNTdjOTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZWJjNzZkOGQ1MWQxM2M2MDQzOTE5MzRlMjg4ZGM1ODgzZDU1YWYwOWM1ZWJjMzIxNjkxMjNlMWRhZGMxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvKO_eBHACMhGD3WUYFh-7MKJkkjR3vTn5YnmdAFyfo)

**Comment by oniatsu** [comment]
> just create an folder with the name in pyproject.toml and put py file inside.

This is correct, but if the project/directory name contained hyphens, the following error occurred.

> The current project could not be installed`.

I solved the problem by using underscores and renaming it with a snake case.

e.g.
- ok: my_project
- ng: my-project

**Comment by ZachHandley** [comment]
> your setup needs be like this:
> 
> project_name/
> 
> ├── pyproject.toml
> 
> ├── api/                   
> 
> │   ├── __init__.py                         
> 
> └── ...

I get it, I just also think don't tell me how to scaffold my projects or how they should be designed, it's not Poetry's job.

**Comment by radoering** [comment]
> I did not understand that this message is a warning. That is because it does not say "Warning" anywhere in the message.

In hindsight, we should probably have prefixed the message with `Warning:` and maybe even not printed the error inside the warning in red.

> I get it, I just also think don't tell me how to scaffold my projects or how they should be designed, it's not Poetry's job.

Unfortunately, it is Poetry's job to tell you if your project can't be packaged and thus not installed since Poetry is not only for dependency management but also for packaging. There are two opposite groups of users:

- Users complaining about the warning in this issue because they use Poetry only for dependency management
- Users complaining that the warning is not an error in #8637 because they use Poetry for dependency management and packaging

All in all. https://github.com/python-poetry/poetry/issues/8662#issuecomment-1812777906 still holds true. With #8650, you will have a means to silence this warning without always typing `--no-root`.

**Comment by ZachHandley** [comment]
@radoering I get that it is poetry job to tell me if it can or can't be packaged, but this is not a packaging issue. My poetry project worked perfectly fine before requiring an asinine folder. If you want to fix this, include more details in the warning so people like me don't go wtf for an hour and a half and then come here because it was suddenly added. On top of that, the pyproject.toml could be used to find the root folder.

Finally,
<img width="239" alt="image" src="https://github.com/python-poetry/poetry/assets/16495679/9d1dea53-5917-486e-9af1-58d468cafcaa">

I added the `__init__.py` to my `api` folder (and my app folder has had one) and I still get the same error. Putting the pyproject.toml at my root folder doesn't make a ton of sense, as it's an API.

**Comment by finswimmer** [comment]
> On top of that, the pyproject.toml could be used to find the root folder instead of some arbitrary requirement.

This is exactly what poetry does. If not specified explicit (https://python-poetry.org/docs/pyproject/#packages) Poetry will look for a folder with a normalized name of the project, that contains at least one `.py` file in the folder where the `pyproject.toml` is located or in a `src` folder.

**Comment by kyleshrader** [comment]
Can you provide configuration so that we don't need a test or specific project folder?

**Comment by AlexanderLanin** [comment]
@kyleshrader yes, see #8650

**Comment by AlexanderLanin** [comment]
FYI I encountered this problem today and `--no-root` is not what I wanted, as I did want to use `poetry run` with my scripts.

I cannot follow the standard directory structure, so what helped me is to define `packages` to point poetry to where my code actually is.
```
packages = [
    { include = "custom_components" },
    { include = "scripts" },
]
```

(It's a home assistant integration, therefore it has a fixed directory structure where the integration is in `custom_components`).

**Comment by Lamarcke** [comment]
I'm also facing this issue. The message doesn't come off as a "warning" at all.

**Comment by danisztls** [comment]
> That's just a warning. If your project used to work, it will probably still work despite of this warning. It means that you either have to make your project packageable or use `--no-root`.
> 
> Or ignore the warning for now and wait for #8650.

First time I see warnings in bright red.

**Comment by radoering** [comment]
To be fair: The warning starts in yellow and ends in yellow, only part of it is red.

Nevertheless, the feedback makes it clear, that it's too confusing for many users if parts of a warning are printed in red. In the next release the warning will be prefixed with "Warning:" and printed completely in yellow.

For future reference: The change will be made in #8650 since it will change the text of the warning anyway.

Just to be clear: Even if it's fine to ignore the warning for now, you probably want to address it in the next Poetry release with #8650 because this warning will eventually become an error in a future release to resolve #8637.

**Comment by optonpo** [comment]
jesus christ.
