### ISSUE TITLE
Poetry installs successfully a dependency via URL, but fails via local path

### ISSUE THREAD

**Issue by aaaaahaaaaa** [python-poetry/poetry#8682]
- **Poetry version**: `1.7.0`
- **Python version**: `3.10.12`
- **OS version and name**: MacOS 14.0
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry successfully installs a `tar.gz` served via a URL, but if the exact same dep/file is downloaded locally, then Poetry fails to install it. I'm very confused, I'm not sure I'm missing something blatantly obvious here.

Here is very straightforward way to reproduce:

Successful:
```
> poetry new teeeest
> cd teeeest
> poetry add https://developers.google.com/static/search-ads/reporting/download/python/searchads360-py.tar.gz
```

Fails:
```
> poetry remove google-ads-searchads360
> mkdir libs && wget https://developers.google.com/static/search-ads/reporting/download/python/searchads360-py.tar.gz -P libs
> poetry add libs/searchads360-py.tar.gz


Updating dependencies
Resolving dependencies... (5.5s)Path /var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py for google-ads-searchads360 does not exist
Path /var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py for google-ads-searchads360 does not exist
Path /var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py for google-ads-searchads360 does not exist
Path /var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py for google-ads-searchads360 does not exist
Path /var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py for google-ads-searchads360 does not exist


  OverrideNeeded

  ({Package('google-ads-searchads360', '0.0.1', source_type='directory', source_url='/var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py'): {'proto-plus': <Dependency proto-plus (>=1.22.2,<2.0.0dev)>}}, {Package('google-ads-searchads360', '0.0.1', source_type='directory', source_url='/var/folders/9g/r0mdzn2s7_l5cd3_2v_y6m6c0000gn/T/tmpwwsu787v/searchads360-py'): {'proto-plus': <Dependency proto-plus (>=1.19.4,<2.0.0dev)>}})

  at ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/poetry/puzzle/provider.py:660 in complete_package
      656│                     current_overrides.update({dependency_package: package_overrides})
      657│                     overrides.append(current_overrides)
      658│ 
      659│             if overrides:
    → 660│                 raise OverrideNeeded(*overrides)
      661│ 
      662│         # Modifying dependencies as needed
      663│         clean_dependencies = []
      664│         for dep in dependencies:

The following error occurred when trying to handle this error:


  AssertionError

  

  at ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/poetry/mixology/partial_solution.py:151 in _register
      147│         name = assignment.dependency.complete_name
      148│         old_positive = self._positive.get(name)
      149│         if old_positive is not None:
      150│             value = old_positive.intersect(assignment)
    → 151│             assert value is not None
      152│             self._positive[name] = value
      153│ 
      154│             return
      155│ 
```

And succesful again:
```
> python -m http.server 8888 --directory libs &
> poetry add http://localhost:8888/searchads360-py.tar.gz
```

**Comment by dimbleby** [comment]
installing a source distribution as a direct dependency seems to have been broken for years, if indeed it ever worked.

I guess no-one is doing that, and I recommend that you don't either!

**Comment by aaaaahaaaaa** [comment]
I see. Thanks for clarifying that. It should be reflected in the documentation with a warning because it currently contains clear examples for doing just that.

**Comment by dimbleby** [comment]
this has also been true for years, but feel free to submit a merge request

**Comment by dimbleby** [comment]
I reckon this should fix it, if anyone wants this enough to write a testcase and submit a merge request:
```diff
diff --git a/src/poetry/inspection/info.py b/src/poetry/inspection/info.py
index 2e6875aa..9d317933 100644
--- a/src/poetry/inspection/info.py
+++ b/src/poetry/inspection/info.py
@@ -319,6 +319,8 @@ class PackageInfo:

             # now this is an unpacked directory we know how to deal with
             new_info = cls.from_directory(path=sdist_dir)
+            new_info._source_type = "file"
+            new_info._source_url = path.resolve().as_posix()

         if not info:
             return new_info
```

**Comment by f3flight** [comment]
@dimbleby I ran into the same issue recently and I tried using the fixed code and somehow it doesn't help. Moreover, even if use a local wheel instead of sdist, it fails with the same AssertionError for me. It only happens on some MacOS hosts, somehow. The command which fails is `poetry add --lock -G dev <path-to-local-file>`. Something else might be going on for me, I will try to debug - but the exception is from the same place in the code.

**Comment by f3flight** [comment]
@dimbleby, @radoering, @aaaaahaaaaa - here are my findings and some FYI:

Env is MacOS 14.x.
Command is "poetry add --lock -G dev <path-to-sdist-OR-wheel>"

I have found that if path contains symlinks, then the command fails no matter if I provide sdist or wheel, with the same `AssertionError` as originally reported. Somewhere in the process of resolution poetry resolves the path, and then compares 2 objects of type `FileDependency`, where one has a resolved `_dependency.path`, while other doesn't (if path contains one or more symlinks). This causes it to fail because it thinks these two dependencies are different, and therefore this line https://github.com/python-poetry/poetry/blob/05f39efa52deb801800309c6ee8cce7c17f61d49/src/poetry/mixology/partial_solution.py#L150 gives a `None`.

I think the code should be changed somewhere to always resolve path before comparing, maybe `FileDependency` init should be modified (it's in `poetry-core` project), or somewhere else - I'm not sure where the deviation and existing resolving happens so cannot really come up with the best solution.

For my use case I have modified my script to resolve the path before calling poetry, which solved the problem for me.
