### ISSUE TITLE
Support for uv

### ISSUE THREAD

**Issue by rfrezino** [python-poetry/poetry#8978]
Hello! 
  Folks from Astral are doing great work for a drop-in replacement for pip. https://github.com/astral-sh/uv/blob/main/BENCHMARKS.md
  Would be possible to make poetry use it under the hood?

**Comment by Secrus** [comment]
We are eliminating all usage of `pip` in our code, so it makes no sense for us.

**Comment by radoering** [comment]
To elaborate a little more:

Poetry only uses pip for uninstalling. It does not use pip for solving and it does not use pip for installing.

We cannot use uv for solving because it's not powerful enough, see its [limitations](https://github.com/astral-sh/uv?tab=readme-ov-file#limitations) (not platform-agnostic). It might be possible to use it for installing/uninstalling. If someone is motivated enough to try it and the results are convincing, I suppose we could provide it as an alternative installer via an option/extra.
