### ISSUE TITLE
Add coverage report on testing

### ISSUE THREAD

**Issue by estepona** [python-poetry/poetry#9629]
### Issue Kind

Brand new capability

### Description

Hi. As mentioned in this [Test Suite Cleanup](https://github.com/python-poetry/poetry/issues/3155) issue, there might be some code needing coverage, yet running `poetry run pytest` doesn't tell the coverage. I'd like to contribute to this task by first adding a coverage report that everyone can see locally and in CI.

### Impact

Rendering a coverage report by running the tests.

### Workarounds

N/A

**Comment by estepona** [comment]
Hi @abn @Secrus @dimbleby @radoering, could you please advise?

**Comment by radoering** [comment]
Might make sense.

It should probably mentioned in https://python-poetry.org/docs/contributing#local-development ([source](https://github.com/python-poetry/poetry/blob/main/docs/contributing.md)) how to create a coverage report locally.

In CI, the challenge is to create coverage reports for all Python versions and platforms and combine the results. Further, we should keep an eye on runtimes (how much slower tests become with coverage).

**Comment by Secrus** [comment]
Since we have `pytest-cov` plugin, I think seeing local coverage would be as simple as running `poetry run pytest --cov=src/poetry --cov-report term`. I would be all for adding the coverage report on CI, but since GH doesn't support reading coverage report files from CI, that would have to be hacked around, outsourced to another service (like codecov), or would only be visible when browsing CI logs, which expire after some time. Overall, it's not worth the work needed and the maintenance burden.
I agree that info about how to see coverage locally should be added to contributing docs, but nothing beyond that.
