### ISSUE TITLE
What do we do without or to help Sébastien?

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#969]
This is a difficult text to write, so apologies if I get the tone wrong, my intentions are only positive and I'm writing this because I really want to see poetry succeed.

So, since December 2018, @sdispater has been really quiet, as can be seen on his [github timeline](https://github.com/sdispater). I hope he's okay; I've tried contacting Sébastien by email, [twitter](https://twitter.com/chriswithers13/status/1102502169536798721) and on the [discord channel](https://discordapp.com/channels/487711540787675139/487711540787675143), even side-channel pinging on [an issue he replied to](https://github.com/sdispater/poetry/issues/907#issuecomment-465930500) but to no response. There is *some* activity on GitHub so I'm hopeful that Sébastien is still around, but has anyone had any contact with him?

In the meantime, what can and/or should we poetry users do to help? 
@sdispater - if you read this, what would you like to have happen?
It's amazing the amount of energy Sébastien has put into this project, but how do we grow this project so he can safely take a break without the project dying?

There's a potentially breaking change [coming from pip](https://github.com/pypa/pip/issues/6314) soon, so I guess we'll find out one way or another, soon enough :-S (See https://github.com/sdispater/poetry/issues/826 for the poetry side of this)

**Comment by pawamoy** [comment]
I'm watching this repository and it seems to me that @sdispater is still quite active here :slightly_smiling_face: I remember seeing him close a lot of issues one or two weeks ago (some spring cleaning I guess?)

**Comment by sdispater** [comment]
Thanks for asking about the state of the project and myself, I really appreciate it.

Just so everyone knows: I am alive and well and Poetry has not been abandoned in any way 🙂 

However, I started a new job recently which gives me less time to work on Poetry or any other of my projects for that matter. I know it might seem like the activity has drastically dropped down, which it has, but this is also due to the fact that I worked pretty much full time on it for months (from February 2018 until December 2018). I am still active (see #908 for instance) and the 1.0 is still planned (here is the roadmap: https://github.com/sdispater/poetry/projects/1)

Now, I know this is a problem and some issues need to be addressed, and I also know that I can't do it alone anymore for the reasons mentioned above.

I plan on moving the repository to an organization (https://github.com/python-poetry) to make it easier to add collaborators to the project and eventually extract sections of the codebase into individual packages.

For the time being, if anyone is interested in helping the project, issue triage and bug fixes are the more pressing matter, feel free to reach out to me and we'll move from there.

I want to reiterate: Poetry is still alive. This is a project I deeply care about and I'll make sure that it gets the attention and care it deserves.

**Comment by cjw296** [comment]
@sdispater - how about treating this bug as "fixed" when the repo is moved to the new org and/or there's at least one other maintainer who can merge commits and do releases?

**Comment by nackjicholson** [comment]
@sdispater Are you planning to do something similar about/with pendulum? That library is excellent but also needs a similar amount of love to keep going.

**Comment by stephsamson** [comment]
Hi everyone 👋 I'm one of the maintainers that volunteered to help Sebastién with triaging issues. You can ping me as `panyang` on the Discord server. I will pin this issue to the top so that people who are interested in contributing can see this thread and can contact us.

**Comment by droserasprout** [comment]
Hi @stephsamson and thanks for your effort. I'm very optimistic about future of this project but there's lots of bugs to fix. Please [contact](mailto:drsrsprt@gmail.com) me if there's anything I can do to help with that. Maybe we should start with tagging the top priority issues and PRs to focus on it? And also discord invite link from OP seems to be expired.

**Comment by droserasprout** [comment]
Working discord server invite link: https://discordapp.com/invite/awxPgve

**Comment by mvoitko** [comment]
@sdispater I would like to help.

**Comment by pykong** [comment]
Can we maybe have a Sponsor link right on GitHub?
Like some repos feature? 
![image](https://user-images.githubusercontent.com/20211140/62573065-725f5900-b895-11e9-8fff-25ce049d6742.png)

**Comment by brycedrennan** [comment]
I'm now helping as a maintainer.  It'll take me a while to get familiar with the codebase and the problem space. Hopefully we'll get to the point where bug fixes are quickly merged in.

As a start I've gone through and tagged all the pull requests and briefly looked at them all.  For now I'll be prioritizing pull requests with bugs.   After that I'll tag the open issues and prioritize fixing the bugs.

Putting :+1: on important pull requests and issues would help us know which ones are important to the community (as we can sort by that).

**Comment by sztomi** [comment]
@brycedrennan are you active in the discord? what's your handle?

**Comment by brycedrennan** [comment]
@sztomi I'm not but I suppose I should be.  My time is limited, so until I can get through the open bugs it doesn't feel like a priority.

**Comment by sztomi** [comment]
Fair enough. Let me know if I can help.

**Comment by FranklinYu** [comment]
@brycedrennan @stephsamson I think it would be more helpful to prioritize Pull Request over issues because they are one-step further. Triaging issues is easier and we can get more volunteers to do that.

**Comment by brycedrennan** [comment]
@FranklinYu Yes that's how we're currently prioritizing: pull requests for bugs are highest priority.

**Comment by cjw296** [comment]
@sdispater / @brycedrennan / @stephsamson - is the stale bot really a productive thing to add to this project? I now have about 5 issues where I'm going to have to periodically go through and say "yes, nothing has changed, this is still an issue". All that's going to do is create noise on the issue tracker.

https://github.com/sdispater/poetry/issues/969#issuecomment-475524940 gives a pretty clear set of criteria for this issue to be considered resolved, I can't see how marking it stale before that is helpful.

**Comment by patrick91** [comment]
I think the stale bot is useful, but some issues should have a label that makes stalebot ignore them :)

**Comment by cjw296** [comment]
Is there such a thing?

**Comment by patrick91** [comment]
Yes, but should be configured there's an option called `exemptLabels`, see https://github.com/apps/stale

**Comment by brycedrennan** [comment]
A stalebot isn't my first choice but I defer to @sdispater since it's his project and he has put the most time into managing issues.

**Comment by sdispater** [comment]
The reasoning behind the introduction of a stale bot is that we just can't go over a backlog of more than 400 issues with the limited number of maintainers. So it's easier to mark them as stale and asking for people originally reporting the issue if it's still relevant. This is especially true since there has been a lot of improvements in the `1.0.0` release (or prereleases) and a lot of them have already been treated.

It gives a better visibility for us and we can actually respond when a stale issue is updated.

Note that it's likely a temporary thing to clean up the backlog a bit before the `1.0` release.

Also, any issue or pull request tracked in a project and/or milestone will not be marked as stale since it means it has been acknowledged and it will eventually be worked on.

**Comment by cjw296** [comment]
I think we can consider this "done" now :-)
