### ISSUE TITLE
exclude files doesn't  match python requires from lockfile

### ISSUE THREAD

**Issue by trim21** [python-poetry/poetry#9697]
### Issue Kind

Brand new capability

### Description

some binary package contains many wheels.

For example, `websockets` now have 85 wheels + 1 sdist from cp38 to cp313, `zstd` have have 86 wheels + 1 sdist from cp38 to cp313, and `yarl` has 91 wheel + 1 sdist, `xxhash` has 122 wheels + 1 sdist, pydantic-core contains 88 wheels

I hope poetry could do not include files are not used in lock file, it will noticeable reduce lockfile.

for example, for a project `require-python = 3.10`, only sdist and wheel with `cp310` or `pp310` will be included. for project `require-python >= 3.10`, only wheel for python >= 3.10 are included

### Impact

This will noticeable reduce lockfile.

### Workarounds

no workaround now

**Comment by dimbleby** [comment]
Pretty sure this has previously been rejected as pointless. 

Why do you care about a few redundant lines in the lock fike?

**Comment by dimbleby** [comment]
not rejected, but duplicate #7935 

(which also makes a case for why this could be not-pointless: for repositories that do not provide hashes it saves the trouble of downloading files in order to calculate those hashes.  Though since the torch indexes do provide hashes these days, the main motivating use case does not exist any more...)
