### ISSUE TITLE
Installing packaging in parallel is unsafe

### ISSUE THREAD

**Issue by palfrey** [python-poetry/poetry#9862]
### Description

We were seeing errors like
```
#14 10.24     Error output:
#14 10.24     Traceback (most recent call last):
#14 10.24       File "<string>", line 18, in <module>
#14 10.24       File "<frozen importlib._bootstrap_external>", line 936, in exec_module
#14 10.24       File "<frozen importlib._bootstrap_external>", line 1073, in get_code
#14 10.24       File "<frozen importlib._bootstrap_external>", line 1130, in get_data
#14 10.24     FileNotFoundError: [Errno 2] No such file or directory: '/var/lang/lib/python3.11/site-packages/packaging/tags.py'
```

which was very confusing, given both Poetry itself and our poetry.lock depends on `packaging`, so why wasn't that file around. We think that the problem is we were also seeing `Downgrading packaging (24.2 -> 24.1)` because the version of packaging in our lock file was different from the floating latest one used for the Poetry install, and this interacted badly in parallel with setuptools usage.

### Workarounds

Upgrade `packaging` in your lock file to the latest version so no `packaging` changes happen in the main install

### Poetry Installation Method

pip

### Operating System

Ubuntu 22.04.5

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "/Users/tom.parker-shemilt/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/tom.parker-shemilt/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = false
```

### Poetry Runtime Logs

```bash session
Not available as we were only able to intermittently hit this in CI
```

**Comment by abn** [comment]
@palfrey I would recommend that you install Poetry via pipx as this shields Poetry itself from site changes. Additionally, are you installing the package into a system site or into a virtualenv?

**Comment by palfrey** [comment]
> @palfrey I would recommend that you install Poetry via pipx as this shields Poetry itself from site changes. Additionally, are you installing the package into a system site or into a virtualenv?
> 
> Edit: If you do not want to install pipx, then either use the poetry installer or simply create a virtual environment (`python -m venv /path/to/venv`) to isolate poetry installation.

We've been installing into the system environment, both because this is being done inside Docker and because we're doing this for a SAM image which really needed to be able to install all the packages without a virtualenv (or at least this was the easiest path). OTOH, using the poetry installer seems to solve this as even after I downgrade `packaging` in our Poetry.lock, it just installs that not downgrades, which would indicate we're not seeing the problem any more.

Thanks for that! I feel this should probably get fixed anyways at some point, but definitely with a lowered priority vs what I'd been thinking for it.

**Comment by abn** [comment]
From the [installation docs](https://python-poetry.org/docs/#installation),

> Poetry should always be installed in a dedicated virtual environment to isolate it from the rest of your system. It should in no case be installed in the environment of the project that is to be managed by Poetry. This ensures that Poetry’s own dependencies will not be accidentally upgraded or uninstalled. (Each of the following installation methods ensures that Poetry is installed into an isolated environment.) In addition, the isolated virtual environment in which poetry is installed should not be activated for running poetry commands.

Using the installer ensures exactly this. Under the hood, it creates a virtual environment and installs Poetry into it. This is the only way I can recommend installing Poetry if you are installing your package into the system site. So does using `pipx`. And `pipx` exists largely to allow for the reliable use of an installed application without being affected by other applications.

While there are different schools of thoughts on this, "I don't need a virtual environment inside a container" argument is dangerous. The overheads of using a virtual environment is simply too insignificant to worry about, especially considering the advantages it brings. This is not to say that there aren't use cases where it makes sense, just that it is (in our opinion) a faulty idea as a default approach - it should be an exception, not the rule.

As for this issue, it is not something we intend to solve explicitly. The issue here is that Poetry is installed to the same environment it is managing for the project. This can, as indicated by the documentation, cause unintended consequences. The error seen on this issue being one of them.

Either;

1. Install Poetry to an isolated virtual and then install the package into the system-site.
2. Install Poetry to system-site and then manage the project in its own virtual environment.

We recommend that Poetry be installed in its own isolated environment, or at the very least avoid installing a Poetry managed project into the same environment as Poetry. We also recommend that a virtual environment be preferred when installing the project where feasible.
